### ISSUE TITLE
[Bug] Converting Keras H5 model to intermediate representation IR 

### ISSUE THREAD

**Issue by MuaadhS** [openvinotoolkit/openvino#10333]
#####Question
I have developed a model to perform image segmentation and saved it in keras .hdf5 (h5) format. Currently I'm trying to convert the model into IR format but I am getting the error provided. 

##### System information (version)
- OpenVINO => 2020.4
- Operating System / Platform => Windows 64 Bit
- Problem classification: Model Conversion
- Framework: Keras and TensorFlow
- Model name: U-Net

##### Steps to reproduce

I started by converting the .hdf5 model into tensorflow .pb model using the following code:
\\\\  model = tf.keras.models.load_model('.hdf5_model_path')
\\\\  tf.saved_model.save(model,'.pb_save_location')

This generated .pb file and 2 folders > assets (which is an empty folder) and variables.

Next I installed Tensorflow prerequisites (install_prerequisites_tf2.bat) then ran this command in model optimizer:
\\\\  python mo_tf.py --saved_model_dir <SAVED_MODEL_DIRECTORY> --output_dir <OUTPUT_MODEL_DIR>  

This generated the message shown next. I am guessing it is an issue related to input shape which from my code is:
Input_1=(None, 512, 512, 1)

##### error message

Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      None
        - Path for generated IR:        P:\model.pb-20220130T125025Z-001
        - IR output name:       saved_model
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         Not specified, inherited from the model
        - Output layers:        Not specified, inherited from the model
        - Input shapes:         Not specified, inherited from the model
        - Mean values:  Not specified
        - Scale values:         Not specified
        - Scale factor:         Not specified
        - Precision of IR:      FP32
        - Enable fusing:        True
        - Enable grouped convolutions fusing:   True
        - Move mean values to preprocess section:       None
        - Reverse input channels:       False
TensorFlow specific parameters:
        - Input model in text protobuf format:  False
        - Path to model dump for TensorBoard:   None
        - List of shared libraries with TensorFlow custom layers implementation:        None
        - Update the configuration file with input/output node names:   None
        - Use configuration file used to generate the model with Object Detection API:  None
        - Use the config file:  None
        - Inference Engine found in:    P:\Program Files (x86)\Intel\openvino_2021.4.752\python\python3.7\openvino
Inference Engine version:       2021.4.2-3974-e2a469a3450-releases/2021/4
Model Optimizer version:        2021.4.2-3974-e2a469a3450-releases/2021/4
2022-02-02 00:47:09.538901: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
C:\Users\moaat\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\autograph\impl\api.py:22: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
2022-02-02 00:47:17.003869: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-02-02 00:47:17.005088: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2022-02-02 00:47:17.763582: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:02:00.0 name: NVIDIA GeForce GTX 960M computeCapability: 5.0
coreClock: 1.176GHz coreCount: 5 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 74.65GiB/s
2022-02-02 00:47:17.763862: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2022-02-02 00:47:18.428891: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2022-02-02 00:47:18.429106: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2022-02-02 00:47:18.564543: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2022-02-02 00:47:18.622847: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2022-02-02 00:47:18.624526: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cusolver64_10.dll'; dlerror: cusolver64_10.dll not found
2022-02-02 00:47:18.928138: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2022-02-02 00:47:18.957024: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2022-02-02 00:47:18.957257: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1757] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2022-02-02 00:47:18.958392: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-02-02 00:47:18.960469: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-02-02 00:47:18.960538: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]
2022-02-02 00:47:18.969019: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-02-02 00:47:20.988206: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-02-02 00:47:20.988658: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2022-02-02 00:47:21.000416: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:02:00.0 name: NVIDIA GeForce GTX 960M computeCapability: 5.0
coreClock: 1.176GHz coreCount: 5 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 74.65GiB/s
2022-02-02 00:47:21.000632: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2022-02-02 00:47:21.001129: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2022-02-02 00:47:21.008654: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2022-02-02 00:47:21.009189: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2022-02-02 00:47:21.009896: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2022-02-02 00:47:21.013067: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cusolver64_10.dll'; dlerror: cusolver64_10.dll not found
2022-02-02 00:47:21.013318: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2022-02-02 00:47:21.013859: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2022-02-02 00:47:21.014746: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1757] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2022-02-02 00:47:21.081751: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-02-02 00:47:21.081953: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0
2022-02-02 00:47:21.083479: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N
2022-02-02 00:47:21.091138: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-02-02 00:47:21.113787: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:928] Optimization results for grappler item: graph_to_optimize
  function_optimizer: Graph size after: 284 nodes (234), 383 edges (333), time = 10.884ms.
  function_optimizer: function_optimizer did nothing. time = 0.49ms.

[ ERROR ]  Shape [ -1 512 512   1] is not fully defined for output 0 of "input_1". Use --input_shape with positive integers to override model input shapes.
[ ERROR ]  Cannot infer shapes or values for node "input_1".
[ ERROR ]  Not all output shapes were inferred or fully defined for node "input_1".
 For more information please refer to Model Optimizer FAQ, question #40. (https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=40#question-40)
[ ERROR ]
[ ERROR ]  It can happen due to bug in custom shape infer function <function Parameter.infer at 0x000001C3BB6BBEE8>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ ERROR ]  Run Model Optimizer with --log_level=DEBUG for more information.
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "input_1" node.
 For more information please refer to Model Optimizer FAQ, question #38. (https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=38#question-38)

**Comment by zulkifli-halim** [comment]
Hello @MuaadhS. Please share with us your Keras model for further investigation.

**Comment by MuaadhS** [comment]
Hello @zulkifli-halim, thank you for your response. this is the link to my Keras model:
[https://github.com/MuaadhS/U-Net-segmentation/blob/main/fibroblast.hdf5](url)

**Comment by zulkifli-halim** [comment]
Hi @MuaadhS, I'm able to convert the model to IR.

```
C:\Python\Python37\lib\site-packages\numpy\core\__init__.py:29: UserWarning: loaded more than 1 DLL from .libs:
C:\Python\Python37\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\Python\Python37\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
C:\Python\Python37\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  stacklevel=1)
C:\Python\Python37\lib\site-packages\scipy\__init__.py:140: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.16.4)
  UserWarning)
Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      None
        - Path for generated IR:        C:\Users\model
        - IR output name:       saved_model
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         Not specified, inherited from the model
        - Output layers:        Not specified, inherited from the model
        - Input shapes:         [1,512,512,3]
        - Mean values:  Not specified
        - Scale values:         Not specified
        - Scale factor:         Not specified
        - Precision of IR:      FP32
        - Enable fusing:        True
        - Enable grouped convolutions fusing:   True
        - Move mean values to preprocess section:       False
        - Reverse input channels:       False
TensorFlow specific parameters:
        - Input model in text protobuf format:  False
        - Path to model dump for TensorBoard:   None
        - List of shared libraries with TensorFlow custom layers implementation:        None
        - Update the configuration file with input/output node names:   None
        - Use configuration file used to generate the model with Object Detection API:  None
        - Use the config file:  None
Model Optimizer version:
2022-02-15 23:18:05.153939: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-02-15 23:18:05.154239: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-02-15 23:18:10.739952: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-02-15 23:18:10.742341: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2022-02-15 23:18:10.743214: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2022-02-15 23:18:10.753015: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: zbinab5x-mobl3
2022-02-15 23:18:10.753213: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: zbinab5x-mobl3
2022-02-15 23:18:10.758157: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-02-15 23:18:10.768218: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-02-15 23:18:12.217370: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-02-15 23:18:12.221219: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2022-02-15 23:18:12.231841: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-02-15 23:18:12.272752: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:928] Optimization results for grappler item: graph_to_optimize
  function_optimizer: Graph size after: 282 nodes (233), 381 edges (332), time = 17.917ms.
  function_optimizer: function_optimizer did nothing. time = 0.245ms.


[ SUCCESS ] Generated IR version 10 model.
[ SUCCESS ] XML file: C:\Users\model\saved_model.xml
[ SUCCESS ] BIN file: C:\Users\model\saved_model.bin
[ SUCCESS ] Total execution time: 11.92 seconds.
It's been a while, check for a new version of Intel(R) Distribution of OpenVINO(TM) toolkit here https://software.intel.com/en-us/openvino-toolkit/choose-download?cid=&source=upgrade&content=2020_3_LTS or on the GitHub*
```

You need to specify the model input shape in order to convert the model to IR format. This is the MO command I used to convert the model:
`python mo_tf.py --saved_model_dir <SAVED_MODEL_DIRECTORY> --output_dir <OUTPUT_MODEL_DIR> --input_shape [1,512,512,3]`

**Comment by MuaadhS** [comment]
Hello @zulkifli-halim, Just like you suggested I specified the the input shape in my MO command. The previous error does not occur now, however the model was not converted into IR format and I am getting this new error:

``` 
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID (<class 'extensions.back.ConvolutionNormalizer.ConvolutionWithGroupsResolver'>)":
[ ERROR ]  Traceback (most recent call last):
  File "P:\Program Files (x86)\Intel\openvino_2021.4.752\deployment_tools\model_optimizer\mo\utils\class_registration.py", line 278, in apply_transform
    for_graph_and_each_sub_graph_recursively(graph, replacer.find_and_replace_pattern)
  File "P:\Program Files (x86)\Intel\openvino_2021.4.752\deployment_tools\model_optimizer\mo\middle\pattern_match.py", line 46, in for_graph_and_each_sub_graph_recursively
    func(graph)
  File "P:\Program Files (x86)\Intel\openvino_2021.4.752\deployment_tools\model_optimizer\extensions\back\ConvolutionNormalizer.py", line 112, in find_and_replace_pattern
    V7ConvolutionWithGroupsResolver().find_and_replace_pattern(graph)
  File "P:\Program Files (x86)\Intel\openvino_2021.4.752\deployment_tools\model_optimizer\extensions\back\ConvolutionNormalizer.py", line 78, in find_and_replace_pattern
    resolve_convolution_with_group(node, group, ir_version='V7')
  File "P:\Program Files (x86)\Intel\openvino_2021.4.752\deployment_tools\model_optimizer\extensions\back\ConvolutionNormalizer.py", line 25, in resolve_convolution_with_group
    assert weights_shape[0] % group == 0
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "P:\Program Files (x86)\Intel\openvino_2021.4.752\deployment_tools\model_optimizer\mo\main.py", line 394, in main
    ret_code = driver(argv)
  File "P:\Program Files (x86)\Intel\openvino_2021.4.752\deployment_tools\model_optimizer\mo\main.py", line 356, in driver
    ret_res = emit_ir(prepare_ir(argv), argv)
  File "P:\Program Files (x86)\Intel\openvino_2021.4.752\deployment_tools\model_optimizer\mo\main.py", line 252, in prepare_ir
    graph = unified_pipeline(argv)
  File "P:\Program Files (x86)\Intel\openvino_2021.4.752\deployment_tools\model_optimizer\mo\pipeline\unified.py", line 17, in unified_pipeline
    class_registration.ClassType.BACK_REPLACER
  File "P:\Program Files (x86)\Intel\openvino_2021.4.752\deployment_tools\model_optimizer\mo\utils\class_registration.py", line 328, in apply_replacements
    apply_replacements_list(graph, replacers_order)
  File "P:\Program Files (x86)\Intel\openvino_2021.4.752\deployment_tools\model_optimizer\mo\utils\class_registration.py", line 318, in apply_replacements_list
    num_transforms=len(replacers_order))
  File "P:\Program Files (x86)\Intel\openvino_2021.4.752\deployment_tools\model_optimizer\mo\utils\logger.py", line 111, in wrapper
    function(*args, **kwargs)
  File "P:\Program Files (x86)\Intel\openvino_2021.4.752\deployment_tools\model_optimizer\mo\utils\class_registration.py", line 306, in apply_transform
    )) from err
Exception: Exception occurred during running replacer "REPLACEMENT_ID (<class 'extensions.back.ConvolutionNormalizer.ConvolutionWithGroupsResolver'>)":

[ ERROR ]  ---------------- END OF BUG REPORT --------------
```

**Comment by zulkifli-halim** [comment]
@MuaadhS. I received the same errors when converting the model using OpenVINO 2021.4. As of this moment, please use the OpenVINO 2020.4 to convert the model.
