### ISSUE TITLE
converting tensorflow model to openvino 

### ISSUE THREAD

**Issue by Elio-hanna** [openvinotoolkit/openvino#10538]
##### System information (version)
- OpenVINO => 2021.4
- Operating System / Platform => ubuntu 18.04 and ubuntu 20
- Problem classification: Model Conversion
- Framework: TensorFlow 
- Model name: ssd_resnet50_v1

##### Detailed description
Model Optimizer arguments:
Common parameters:
  - Path to the Input Model:  None
  - Path for generated IR:  /tmp/model/openvino_models/tf_saved_model/
  - IR output name:   saved_model
  - Log level:  ERROR
  - Batch:  Not specified, inherited from the model
  - Input layers:   Not specified, inherited from the model
  - Output layers:  Not specified, inherited from the model
  - Input shapes:   Not specified, inherited from the model
  - Mean values:  Not specified
  - Scale values:   Not specified
  - Scale factor:   Not specified
  - Precision of IR:  FP32
  - Enable fusing:  True
  - Enable grouped convolutions fusing:   True
  - Move mean values to preprocess section:   None
  - Reverse input channels:   True
TensorFlow specific parameters:
  - Input model in text protobuf format:  False
  - Path to model dump for TensorBoard:   None
  - List of shared libraries with TensorFlow custom layers implementation:  None
  - Update the configuration file with input/output node names:   None
  - Use configuration file used to generate the model with Object Detection API:  /tmp/model/tf2_models/tf2_models/model/pipeline.config
  - Use the config file:  None
  - Inference Engine found in:  /opt/intel/openvino/python/python3.6/openvino
Inference Engine version:   2021.4.0-3839-cd81789d294-releases/2021/4
Model Optimizer version:  2021.4.0-3839-cd81789d294-releases/2021/4
2022-02-19 11:53:26.256810: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/intel/openvino/opencv/lib:/opt/intel/openvino/deployment_tools/ngraph/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/tbb/lib::/opt/intel/openvino/deployment_tools/inference_engine/external/hddl/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/omp/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/gna/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/mkltiny_lnx/lib:/opt/intel/openvino/deployment_tools/inference_engine/lib/intel64
2022-02-19 11:53:26.256847: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py:22: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
2022-02-19 11:53:30.242536: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-02-19 11:53:30.242892: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/intel/openvino/opencv/lib:/opt/intel/openvino/deployment_tools/ngraph/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/tbb/lib::/opt/intel/openvino/deployment_tools/inference_engine/external/hddl/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/omp/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/gna/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/mkltiny_lnx/lib:/opt/intel/openvino/deployment_tools/inference_engine/lib/intel64
2022-02-19 11:53:30.242920: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2022-02-19 11:53:30.242986: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (8e574948de7b): /proc/driver/nvidia/version does not exist
2022-02-19 11:53:30.243283: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-02-19 11:53:30.243743: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-02-19 11:53:43.548819: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-02-19 11:53:43.548969: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2022-02-19 11:53:43.549222: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-02-19 11:53:43.567485: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2599990000 Hz
2022-02-19 11:53:43.859715: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:928] Optimization results for grappler item: graph_to_optimize
  function_optimizer: Graph size after: 3928 nodes (3440), 4396 edges (3901), time = 134.534ms.
  function_optimizer: Graph size after: 3928 nodes (0), 4396 edges (0), time = 65.029ms.
Optimization results for grappler item: __inference_map_while_cond_813817_23994
  function_optimizer: function_optimizer did nothing. time = 0.003ms.
  function_optimizer: function_optimizer did nothing. time = 0.001ms.
Optimization results for grappler item: __inference_map_while_body_813818_23981
  function_optimizer: function_optimizer did nothing. time = 0.001ms.
  function_optimizer: function_optimizer did nothing. time = 0ms.

[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Exception occurred during running replacer "ObjectDetectionAPIPreprocessor2Replacement (<class 'extensions.front.tf.ObjectDetectionAPI.ObjectDetectionAPIPreprocessor2Replacement'>)": 
[ ERROR ]  Traceback (most recent call last):
  File "/opt/intel/openvino/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 276, in apply_transform
    replacer.find_and_replace_pattern(graph)
  File "/opt/intel/openvino/deployment_tools/model_optimizer/mo/front/tf/replacement.py", line 36, in find_and_replace_pattern
    self.transform_graph(graph, desc._replacement_desc['custom_attributes'])
  File "/opt/intel/openvino/deployment_tools/model_optimizer/extensions/front/tf/ObjectDetectionAPI.py", line 710, in transform_graph
    assert len(start_nodes) >= 1
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/intel/openvino_2021.4.582/deployment_tools/model_optimizer/mo/main.py", line 394, in main
    ret_code = driver(argv)
  File "/opt/intel/openvino_2021.4.582/deployment_tools/model_optimizer/mo/main.py", line 356, in driver
    ret_res = emit_ir(prepare_ir(argv), argv)
  File "/opt/intel/openvino_2021.4.582/deployment_tools/model_optimizer/mo/main.py", line 252, in prepare_ir
    graph = unified_pipeline(argv)
  File "/opt/intel/openvino/deployment_tools/model_optimizer/mo/pipeline/unified.py", line 17, in unified_pipeline
    class_registration.ClassType.BACK_REPLACER
  File "/opt/intel/openvino/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 328, in apply_replacements
    apply_replacements_list(graph, replacers_order)
  File "/opt/intel/openvino/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 318, in apply_replacements_list
    num_transforms=len(replacers_order))
  File "/opt/intel/openvino/deployment_tools/model_optimizer/mo/utils/logger.py", line 111, in wrapper
    function(*args, **kwargs)
  File "/opt/intel/openvino/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 306, in apply_transform
    )) from err
Exception: Exception occurred during running replacer "ObjectDetectionAPIPreprocessor2Replacement (<class 'extensions.front.tf.ObjectDetectionAPI.ObjectDetectionAPIPreprocessor2Replacement'>)": 

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------

##### Steps to reproduce
method 1:
1- run docker image:
- docker run -it -v $(pwd)/models:/tmp/model openvino/ubuntu18_dev:2021.4
2- cd deployment_tools/model_optimizer
3- ./mo.py --saved_model_dir /tmp/model/tf2_models/tf2_models/model/saved_model/ --transformations_config ./extensions/front/tf/ssd_support_api_v2.0.json --tensorflow_object_detection_api_pipeline_config /tmp/model/tf2_models/tf2_models/model/pipeline.config --reverse_input_channels --output_dir /tmp/model/openvino_models/tf_saved_model/

method 2:
1-clone git repository branch (releases/2021/4)
2- install tf2 requirements
3- ./mo.py --saved_model_dir /tmp/model/tf2_models/tf2_models/model/saved_model/ --transformations_config ./extensions/front/tf/ssd_support_api_v2.0.json --tensorflow_object_detection_api_pipeline_config /tmp/model/tf2_models/tf2_models/model/pipeline.config --reverse_input_channels --output_dir /tmp/model/openvino_models/tf_saved_model/

both methods returned the same bug error

**Comment by andrei-kochin** [comment]
Anyway @Elio-hanna  could you please try using ./extensions/front/tf/ssd_v2_support.json instead which seems to be suites more for ssd_resnet50_v1 and kindly update me with the results.

**Comment by Elio-hanna** [comment]
Hello @andrei-kochin thank you for your reply! the model is custom but based on ssd_resnet50_v1, when trying /extensions/front/tf/ssd_v2_support.json i got the following error:

[ ERROR ]  Failed to match nodes from custom replacement description with id 'ObjectDetectionAPIPreprocessorReplacement':
It means model and custom replacement description are incompatible.
Try to correct custom replacement description according to documentation with respect to model node names
[ ERROR ]  Failed to match nodes from custom replacement description with id 'ObjectDetectionAPISSDPostprocessorReplacement':
It means model and custom replacement description are incompatible.
Try to correct custom replacement description according to documentation with respect to model node names
2022-02-21 18:38:52.372193: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-02-21 18:38:52.374914: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:196] None of the MLIR optimization passes are enabled (registered 0 passes)
[ ERROR ]  Cannot infer shapes or values for node "StatefulPartitionedCall/map/TensorArrayV2_2".
[ ERROR ]  Tensorflow type 21 not convertible to numpy dtype.
[ ERROR ]  
[ ERROR ]  It can happen due to bug in custom shape infer function <function tf_native_tf_node_infer at 0x7fd721c68f28>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ ERROR ]  Run Model Optimizer with --log_level=DEBUG for more information.
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "StatefulPartitionedCall/map/TensorArrayV2_2" node. 


after this error i added --input_shape [1,640,640,3] but still same error

**Comment by andrei-kochin** [comment]
@Elio-hanna it's hard to shoot into the dark. Is it possible to share the model with fake/random weights to assist with conversion?
