### ISSUE TITLE
How to enable model caching during Auto-Device selection

### ISSUE THREAD

**Issue by ZachL1** [openvinotoolkit/openvino#11248]
I noticed that Auto-Device selection does not seem to work with model caching at the same time.

#### Detail
When I use it like the following, I get `ov::Exception`
```cpp
core.set_property(ov::cache_dir("cache"));

ov::CompiledModel compiled_model = core.compile_model(modle_path, "AUTO",
    ov::hint::performance_mode(ov::hint::PerformanceMode::THROUGHPUT));
```
I tried to use `ov::Core::get_property` to check `AUTO` support for model caching, however I get the same `ov::Exception`
```cpp
std::vector<std::string> caps = core.get_property("AUTO", ov::device::capabilities);
```
![core.hpp](https://s2.loli.net/2022/03/27/5RF42sWYH3egdbh.png)
Does this mean that `AUTO` does not support model caching?

However I would like model caching to reduce compile model time when using GPU. I also want Auto-Device selection to use CPU first to reduce the first inference latency when cache is not available. Also, sometimes the GPU may be unavailable, and I would like the CPU to be automatically invoked to deal with this situation.

How should I use OpenVINO for this?

**Comment by ilya-lavrenov** [comment]
Hi @ZachL1,

```c++
std::vector<std::string> caps = core.get_property("AUTO", ov::device::capabilities);
```
This does not work because `AUTO` does not `ov::device::capabilities` property (you have to query `ov::supported_properties` first and check whether `ov::device::capabilities` is in the returned list). The answer this property is not here - because `AUTO` don't have its own capabilities, everything depends on the selected device and we don't know the capabilities beforehand (before the `ov::Core::compile_model` call).

> I noticed that Auto-Device selection does not seem to work with model caching at the same time.

It should work. `AUTO` itself does nothing specific for model caching, how it actually works:
1. `AUTO` selects one or several devices
2. Compiled model on each of this device by transferring `ov::Core::compile_model` calls back to `ov::Core` object
3. Since the model cache is enabled in `Core` (you set `core.set_property(ov::cache_dir("cache"));`), the `Core` will cache models for later fast re-compilation.

So, the answer - whether `AUTO` supports model cache actually depends on the underlaying plugin selected by `AUTO`. For your specific case both `CPU` and `GPU` support this feature (see https://docs.openvino.ai/latest/openvino_docs_OV_UG_Working_with_devices.html#features-support-matrix)

> However I would like model caching to reduce compile model time when using GPU. I also want Auto-Device selection to use CPU first to reduce the first inference latency when cache is not available. Also, sometimes the GPU may be unavailable, and I would like the CPU to be automatically invoked to deal with this situation.

It's possible to limit the device list using [device candidate list](https://docs.openvino.ai/latest/openvino_docs_IE_DG_supported_plugins_AUTO.html#device-candidate-list):
```c++
ov::CompiledModel model4 = core.compile_model(model, "AUTO", ov::device::priorities("GPU,CPU"));
```

In this case if `GPU` on the system, `AUTO` will select it as an accelerator, otherwise fallback to `CPU` will be used (see [auto selection logic](https://docs.openvino.ai/latest/openvino_docs_IE_DG_supported_plugins_AUTO.html#automatic-device-selection) for details).

> When I use it like the following, I get ov::Exception

I have tried to enable more tests in the PR https://github.com/openvinotoolkit/openvino/pull/11249 and they have passed on my machine locally. Could you please share your topology? Maybe we can find some specifics in it.

@wangleis can we write about caching support in `AUTO` in our documents? 

Thanks,
Ilya.

**Comment by wangleis** [comment]
@ilya-lavrenov Will add caching support in AUTO 2022.2 release document

**Comment by ZachL1** [comment]
Hi @ilya-lavrenov  Thanks!

In my case, it doesn't work. I have limit the device list, like you suggested
```cpp
ov::CompiledModel compiled_model = core.compile_model(modle_path, "AUTO", ov::device::priorities("GPU,CPU"));
```

I'm not a native English speaker and I'm not quite sure what you mean by 'topology', but I'll share as much information as I can.

### Detail
- Latest openvino 2022.1
- Windows Visual Studio 2019 / Python 3.8.8

#### C++
I'm not doing anything else but trying to compile a model:
```cpp
Core core;
core.set_property(ov::cache_dir("cache"));
ov::CompiledModel compiled_model = core.compile_model(modle_path, "AUTO", ov::device::priorities("GPU,CPU"));
// or
ov::CompiledModel compiled_model = core.compile_model(modle_path, "AUTO:GPU,CPU");
```
Without exception, `ov::Exception` was encountered at `core.compile_model`. It points to `core.hpp`, see the [screenshot](https://s2.loli.net/2022/03/27/5RF42sWYH3egdbh.png) in my first comment.

However when I specify the device as GPU or CPU, they work fine:
```cpp
ov::CompiledModel compiled_model = core.compile_model(modle_path, "GPU"); // it worked
ov::CompiledModel compiled_model = core.compile_model(modle_path, "CPU"); // it worked
```

#### Python
To make sure it wasn't an error due to the environment configuration, I ran the same test with Python:
```python
core = ov.Core()
core.set_property({'CACHE_DIR': 'cache'})
compiled_model = core.compile_model(modle_path, "AUTO", config={"MULTI_DEVICE_PRIORITIES": "GPU,CPU"})
```
However it has the exact same problem, with an error at `core.compile_model`:
```
Traceback (most recent call last):
  File ".\inference_openvino.py", line 13, in <module>
    compiled_model = core.compile_model(weight, "AUTO", config={"MULTI_DEVICE_PRIORITIES": "GPU,CPU"})
  File "E:\software\anaconda3\lib\site-packages\openvino\runtime\ie_api.py", line 266, in compile_model
    super().compile_model(model, device_name, {} if config is None else config)
RuntimeError: CNNNetwork was not initialized.
```
As with C++, they work fine if I use the GPU or CPU instead of AUTO.

#### Model
Again, to make sure that my model was not causing the problem, I did the same test using [googlenet-v1](https://github.com/openvinotoolkit/open_model_zoo/tree/releases/2022/1/models/public/googlenet-v1) from the OpenVINO Model Zoo. It threw the same exception in the same place as my model.

Nevertheless, I'll share [my model](https://drive.google.com/drive/folders/1E2O1J5M66j_wK4guHbzaX4MxROpGRTAf?usp=sharing).

**Comment by wangleis** [comment]
Hi @ZachL1,

In 2022.1 release, AUTO only support model caching with CNN network input. 

Model_path input will be support by AUTO in following release.

Thanks,
Wanglei

**Comment by ZachL1** [comment]
Hi @wangleis 

Great, just like you said, using the CNN network input worked!

Thank you all, great OpenVINO!
