### ISSUE TITLE
[Bug] Error converting Google AutoML to OpenVino using mo

### ISSUE THREAD

**Issue by RogerMor** [openvinotoolkit/openvino#11600]
##### System information (version)

System 1:

- OpenVINO => 2022.1
- Operating System / Platform => Intel Dev Cloud notebooks: https://notebooks.edge.devcloud.intel.com/
- Intel Dev Cloud edge notebooks launcher => OPENVINO 2022.1 + tensorflow 2.4
- Problem classification: Model Conversion
- Framework: Google AutoML
- Model name: AutoML object detection

System 2:

- OpenVINO => 2022.1
- Operating System / Platform => Ubuntu 20.04.4 LTS
- Intel Dev Cloud edge notebooks launcher => OPENVINO 2022.1 + tensorflow 2.4.4
- Problem classification: Model Conversion
- Framework: Google AutoML
- Model name: AutoML object detection

##### Detailed description
Error when converting the model exported from Google AutoML  to OPENVINO using mo --saved_model_dir "saved_model_path"

Obtained Error:

**[ ERROR ]  Error while emitting attributes for layer key (id = 0). It usually means that there is unsupported pattern around this node or unsupported combination of attributes.**

```
[ 2022-04-28 09:00:30,353 ] [ DEBUG ] [ main:551 ]  Traceback (most recent call last):
  File "/dischdd/Pervasive/anaconda3/envs/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/back/ie_ir_ver_2/emitter.py", line 243, in serialize_element
    value = attr[1](node)
  File "/dischdd/Pervasive/anaconda3/envs/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/ops/parameter.py", line 60, in <lambda>
    ('element_type', lambda node: np_data_type_to_destination_type(node.data_type)),
  File "/dischdd/Pervasive/anaconda3/envs/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/middle/passes/convert_data_type.py", line 80, in np_data_type_to_destination_type
    raise Error('Data type "{}" is not supported'.format(np_data_type))
openvino.tools.mo.utils.error.Error: Data type "<class 'str'>" is not supported

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/dischdd/Pervasive/anaconda3/envs/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/back/ie_ir_ver_2/emitter.py", line 330, in serialize_node_attributes
    serialize_element(graph, node, s, parent_element, edges, unsupported)
  File "/dischdd/Pervasive/anaconda3/envs/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/back/ie_ir_ver_2/emitter.py", line 249, in serialize_element
    raise Error(
openvino.tools.mo.utils.error.Error: Cannot emit value for attribute element_type for layer key. Internal attribute template: ('element_type', <function Parameter.supported_attrs.<locals>.<lambda> at 0x7fdbac5ed280>).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/dischdd/Pervasive/anaconda3/envs/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/back/ie_ir_ver_2/emitter.py", line 330, in serialize_node_attributes
    serialize_element(graph, node, s, parent_element, edges, unsupported)
  File "/dischdd/Pervasive/anaconda3/envs/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/back/ie_ir_ver_2/emitter.py", line 268, in serialize_element
    serialize_node_attributes(graph, node, subelements, element, edges, unsupported)
  File "/dischdd/Pervasive/anaconda3/envs/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/back/ie_ir_ver_2/emitter.py", line 332, in serialize_node_attributes
    raise Error(
openvino.tools.mo.utils.error.Error: Error while emitting attributes for layer key (id = 0). It usually means that there is unsupported pattern around this node or unsupported combination of attributes.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/dischdd/Pervasive/anaconda3/envs/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/back/ie_ir_ver_2/emitter.py", line 444, in serialize_node
    serialize_node_attributes(graph, node, node.IE, layers, edges, unsupported)
  File "/dischdd/Pervasive/anaconda3/envs/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/back/ie_ir_ver_2/emitter.py", line 332, in serialize_node_attributes
    raise Error(
openvino.tools.mo.utils.error.Error: Error while emitting attributes for layer key (id = 0). It usually means that there is unsupported pattern around this node or unsupported combination of attributes.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/dischdd/Pervasive/anaconda3/envs/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/main.py", line 533, in main
    ret_code = driver(argv)
  File "/dischdd/Pervasive/anaconda3/envs/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/main.py", line 491, in driver
    ret_res = emit_ir(graph, argv)
  File "/dischdd/Pervasive/anaconda3/envs/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/main.py", line 423, in emit_ir
    prepare_emit_ir(graph=graph,
  File "/dischdd/Pervasive/anaconda3/envs/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/pipeline/common.py", line 245, in prepare_emit_ir
    generate_ie_ir(graph=graph,
  File "/dischdd/Pervasive/anaconda3/envs/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/back/ie_ir_ver_2/emitter.py", line 606, in generate_ie_ir
    serialize_network(graph, net, unsupported)
  File "/dischdd/Pervasive/anaconda3/envs/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/back/ie_ir_ver_2/emitter.py", line 567, in serialize_network
    serialize_node(graph, node, layers, edges, unsupported)
  File "/dischdd/Pervasive/anaconda3/envs/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/back/ie_ir_ver_2/emitter.py", line 446, in serialize_node
    raise Error(str(e).replace('<SUB-ELEMENT>', '{} (id = {})'.format(node.soft_get('name'), node.id))) from e
openvino.tools.mo.utils.error.Error: Error while emitting attributes for layer key (id = 0). It usually means that there is unsupported pattern around this node or unsupported combination of attributes.
```

##### Steps to reproduce

Train an object detection model (by default) with Google AutoML in Google Cloud Platform (https://cloud.google.com/vision/automl/object-detection/docs):

![image](https://user-images.githubusercontent.com/64934851/165701542-0379d293-91f8-4fa6-a0f8-7d9faa246503.png)

Create new dataset selecting "Object Detection"

![image](https://user-images.githubusercontent.com/64934851/165701325-3106d8b8-ca58-498c-b03e-d6a2bab41352.png)

Import dataset following the instructions:

![image](https://user-images.githubusercontent.com/64934851/165701952-58877edb-60d4-42ca-89dd-17db902b28f9.png)

Once the dataset is imported train new model:

![image](https://user-images.githubusercontent.com/64934851/165702161-8e66703e-5137-47aa-904d-bc0c7dbd91b3.png)

And select the Edge option:

![image](https://user-images.githubusercontent.com/64934851/165702266-be7ee95d-b8f6-4e42-a247-9d2a2b7f8b53.png)

Follow the instructions in web to start training the model.

Once the model is trained  go to Test & Use and export the model for Container:

![image](https://user-images.githubusercontent.com/64934851/165702630-d1e454a1-306b-498e-8c3b-29e335e52e90.png)

which creates a TesnorFlow Saved Model

**Finally:**

Once we have the saved_model we use the mo for optimizing as following:

$mo --saved_model_dir saved_model_path 

obtaining as a result:

**[ ERROR ]  Error while emitting attributes for layer key (id = 0). It usually means that there is unsupported pattern around this node or unsupported combination of attributes.**

and the full log:

[log4.txt](https://github.com/openvinotoolkit/openvino/files/8580722/log4.txt)

This last step has been tested in both environments system1 and system2 reported at the begining of the issue

##### Comments

There are around some partial information for old OpenVino releases but I have not find any documentation for OpenVino 2022.1 to adress this issue

**Comment by RogerMor** [comment]
Thanks a lot again!
