### ISSUE TITLE
[MO]RuntimeError: While validating ONNX node '<Node(Slice): Slice_65>': bad_weak_ptr while converting transformer model

### ISSUE THREAD

**Issue by luvwinnie** [openvinotoolkit/openvino#11733]
##### System information (version)
- OpenVINO => 2020.1.0
- Operating System / Platform => 46~20.04.1-Ubuntu
- Problem classification: Model Conversion
- Framework: Pytorch
- Pytorch Versions:
torch==1.13.0.dev20220522+cu113
torchaudio==0.12.0.dev20220522+cu113
torchinfo==1.6.6
torchvision==0.13.0.dev20220522+cu113
- Model name: TransformerEncoder

##### Detailed description
I'm trying to convert a dynamic inputs transformer encoder to openvino IR format however it seems like showing the following errors.

```
st_model_vino
	- IR output name: 	test_model
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	Not specified, inherited from the model
	- Source layout: 	Not specified
	- Target layout: 	Not specified
	- Layout: 	Not specified
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP32
	- Enable fusing: 	True
	- User transformations: 	Not specified
	- Reverse input channels: 	False
	- Enable IR generation for fixed input shape: 	False
	- Use the transformations config file: 	None
Advanced parameters:
	- Force the usage of legacy Frontend of Model Optimizer for model conversion into IR: 	False
	- Force the usage of new Frontend of Model Optimizer for model conversion into IR: 	False
OpenVINO runtime found in: 	/misc/home/usr16/cheesiang_leow/venv_hanamaruki/lib/python3.8/site-packages/openvino
OpenVINO runtime version: 	2022.1.0-7019-cdb9bec7210-releases/2022/1
Model Optimizer version: 	2022.1.0-7019-cdb9bec7210-releases/2022/1
[ WARNING ]
Detected not satisfied dependencies:
	numpy: installed: 1.22.4, required: < 1.20

Please install required versions of components or run pip installation
pip install openvino-dev
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  While validating ONNX node '<Node(Slice): Slice_65>':
bad_weak_ptr
[ ERROR ]  Traceback (most recent call last):
  File "/misc/home/usr16/cheesiang_leow/venv_hanamaruki/lib/python3.8/site-packages/openvino/tools/mo/main.py", line 533, in main
    ret_code = driver(argv)
  File "/misc/home/usr16/cheesiang_leow/venv_hanamaruki/lib/python3.8/site-packages/openvino/tools/mo/main.py", line 489, in driver
    graph, ngraph_function = prepare_ir(argv)
  File "/misc/home/usr16/cheesiang_leow/venv_hanamaruki/lib/python3.8/site-packages/openvino/tools/mo/main.py", line 394, in prepare_ir
    ngraph_function = moc_pipeline(argv, moc_front_end)
  File "/misc/home/usr16/cheesiang_leow/venv_hanamaruki/lib/python3.8/site-packages/openvino/tools/mo/moc_frontend/pipeline.py", line 147, in moc_pipeline
    ngraph_function = moc_front_end.convert(input_model)
RuntimeError: While validating ONNX node '<Node(Slice): Slice_65>':
bad_weak_ptr

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------
```
Similar [issue](https://github.com/openvinotoolkit/openvino/issues/11517)

##### Steps to reproduce
This is the model file and convert by following commands.

Please ask permission with messages/github account name in order to download the model.
https://drive.google.com/file/d/1TNwsKpetbZXVPPmC9QVLE9Qc3c20uYEG/view?usp=sharing
```
mo --input_model test_model.onnx -o test_model_vino
```

**Comment by Iffa-Meah** [comment]
@luvwinnie I had requested permission for your files.

![image](https://user-images.githubusercontent.com/79643476/169937752-f6fcab4c-f593-4bc2-849e-a26e3e47ff0b.png)

**Comment by luvwinnie** [comment]
@Iffa-Meah Thank you so much, I have just added the permission. Please comment to me, if it is not downloadable.

**Comment by Iffa-Meah** [comment]
@luvwinnie
 Starting from the 2020.4 release, OpenVINO™ supports reading [native ONNX models](https://docs.openvino.ai/2021.1/openvino_docs_IE_DG_ONNX_Support.html).
Therefore, if nothing's wrong with your model, you should be able to run it with OpenVINO.

I did a quick check on your model with [OpenVINO Benchmark App](https://docs.openvino.ai/latest/openvino_inference_engine_tools_benchmark_tool_README.html)
<img width="613" alt="11733benchmarkONNX" src="https://user-images.githubusercontent.com/79643476/170159503-ec5dded5-b9c4-4f92-87cd-7a8ad452f47b.png">

There's a prompt about the ONNX node. This originates from your native ONNX model instead of OpenVINO.
You'll need to check your original ONNX format.
[This](https://docs.openvino.ai/2020.2/_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_ONNX.html) is example of supported ONNX topology.

**Comment by luvwinnie** [comment]
@Iffa-Meah I knew that ONNX is supported by OpenVINO which converting the model from ONNX to nGraph. However, I hope to optimized the model by converting with MO to IR format. Is this mean I can't optimized the model to IR format?

**Comment by mitruska** [comment]
I've checked this with debugger and the error during ONNX Slice import comes from ov::v8::Slice constructor when `get_constant_from_source(input_value(2))` is called in `validate_and_infer_types` and the bad_weak_ptr is thrown by `shared_from_this()` in the `propagate_rt_info(node, output)` at the end of `evaluate_bound`.
https://github.com/openvinotoolkit/openvino/blob/da09272d9f887b3b28aa1e6bf3860cd2a3b2ad89/src/core/src/validation_util.cpp#L1206

We are working on proper fix.
Thank you for reporting this issue.

**Comment by mitruska** [comment]
We have merged PR #11773 to resolve this issue.
@luvwinnie Let us know, if it works for you. Thanks!

**Comment by luvwinnie** [comment]
@mitruska Thank you for fixing! This fix is already can be use by installing with pypi?

**Comment by mitruska** [comment]
This fix in on master branch, and will be available on pypi with next release (2022.2).
