### ISSUE TITLE
[Bug]  error doing ONNX IR conversion

### ISSUE THREAD

**Issue by fenaux** [openvinotoolkit/openvino#11760]
##### System information (version)
 OpenVINO runtime version: 	2022.1.0-7009-19bdd019745-refs/pull/1012/head

##### Detailed description

 
OpenVINO runtime found in: 	/data/venv/openvino_2022.1.0.643/lib/python3.6/site-packages/openvino
OpenVINO runtime version: 	2022.1.0-7009-19bdd019745-refs/pull/1012/head
Model Optimizer version: 	2022.1.0-7009-19bdd019745-refs/pull/1012/head
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Error during import of ONNX model provided as input stream  with binary protobuf message.
[ ERROR ]  Traceback (most recent call last):
  File "/data/venv/openvino_2022.1.0.643/lib/python3.6/site-packages/openvino/tools/mo/main.py", line 533, in main
    ret_code = driver(argv)
  File "/data/venv/openvino_2022.1.0.643/lib/python3.6/site-packages/openvino/tools/mo/main.py", line 489, in driver
    graph, ngraph_function = prepare_ir(argv)
  File "/data/venv/openvino_2022.1.0.643/lib/python3.6/site-packages/openvino/tools/mo/main.py", line 394, in prepare_ir
    ngraph_function = moc_pipeline(argv, moc_front_end)
  File "/data/venv/openvino_2022.1.0.643/lib/python3.6/site-packages/openvino/tools/mo/moc_frontend/pipeline.py", line 29, in moc_pipeline
    input_model = moc_front_end.load(argv.input_model)
RuntimeError: Error during import of ONNX model provided as input stream  with binary protobuf message.

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------

##### Steps to reproduce
mo --input_model "yolov5x.onnx" --input_shape "[1,3, 640, 640]" --mean_values="[123.675, 116.28 , 103.53]" --scale_values="[58.395, 57.12 , 57.375]" --data_type FP16 --output_dir "."

**Comment by brmarkus** [comment]
Can you provide more details about your environment, please?
Which HW, which operating system are you using?

Which model are you using, have you retrained the `yolov5x.onnx`, can you share the model or an URL to where to download it from?

Your system uses Python in version v3.6 ("OpenVINO runtime found in: /data/venv/openvino_2022.1.0.643/lib/python3.6/site-packages/openvino")?

**Comment by fenaux** [comment]
Environment and HW are the basic ones provided by IntelDevCloud
I started a Jupyter notebook with the kernel OpenVino2022.1
I too was surprise by Pyhton 3.6 but ti was the configuration provided.

Model is Yolov5x from Ultralytics  https://github.com/ultralytics/yolov5  converted to Onnx with these instructions
    torch.onnx.export(
        model,
        dummy_input,
        onnx_path,
        opset_version=11,
        do_constant_folding=False,
    )
Note that on my computer (Ubuntu 20.04, Python 3.9 Intel Core I5)
This conversion and the following one to IR model work
Inference with the IR model works too (but is slow 1.6 second for IR model compare to 1.2 with PyTorch model)

**Comment by jgespino** [comment]
@fenaux Could you try to convert the yolov5 model following these steps: https://github.com/violet17/yolov5_demo
Please note the steps are for 2021.4.2 but should work in 2022.1 release with minor changes such as directories and files locations.

**Comment by jgespino** [comment]
Update: I was able to convert YOLOv5x using the following steps:

```
git clone https://github.com/ultralytics/yolov5
cd yolov5
pip install -r requirements.txt
pip install onnx
wget https://github.com/ultralytics/yolov5/releases/download/v6.1/yolov5x.pt
python export.py  --weights yolov5x.pt  --img 640 --batch 1
```
Upload the yolov5x.onnx to DevCloud and convert using the following MO command:
`!mo --input_model models/yolov5x/yolov5x.onnx --data_type FP16 -s 255 --reverse_input_channels --output Conv_417,Conv_436,Conv_455`

![image](https://user-images.githubusercontent.com/18014973/173907450-5755a7e1-6f88-431f-8e9b-b6a5a27199a8.png)

**Comment by fenaux** [comment]
@jgespino , thanks for the help
Once again I work with default settings of devCloud

Wille runing pip install -r requirements.txt I got his error message

Installing collected packages: torch, torchvision, seaborn, thop
  Attempting uninstall: torch
    Found existing installation: torch 1.4.0
    Uninstalling torch-1.4.0:
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/data/venv/openvino_2022.1.0.643/bin/convert-caffe2-to-onnx'
Consider using the `--user` option or check the permissions.

I tried to continue and following
python export.py  --weights yolov5x.pt  --img 640 --batch 1
got 
Traceback (most recent call last):
  File "export.py", line 58, in <module>
    from torch.utils.mobile_optimizer import optimize_for_mobile
ModuleNotFoundError: No module named 'torch.utils.mobile_optimizer'

**Comment by jgespino** [comment]
@fenaux DevCloud does not allow you to install packages. Try the following on your local system and upload the .onnx file for conversion on DevCloud.

```
git clone https://github.com/ultralytics/yolov5
cd yolov5
pip install -r requirements.txt
pip install onnx
wget https://github.com/ultralytics/yolov5/releases/download/v6.1/yolov5x.pt
python export.py  --weights yolov5x.pt  --img 640 --batch 1
```

**Comment by fenaux** [comment]
@jgespino 
Sorry for the long delay but I had other wok ongoing

The original error in this post arrived when I uploaded the file I obtained on my computer. Note the inference worked on my computer but inference with transformed model was longer than inference with original model from ultralytics.

I tried your solution on google colab
I obtained both xml and bin files

but when I try to run on Dev Cloud
ie = Core()
model_ir = ie.read_model(model=ir_path)

I get
RuntimeError: Incorrect weights in bin file!

I am afraid there is no issue
