### ISSUE TITLE
how to mo --mean_values with 6 channels

### ISSUE THREAD

**Issue by ynjiun** [openvinotoolkit/openvino#11846]
Hi

I have a tensorflow model with input of [n,h,w,6] and when I tried to convert with mo command like:

`mo --input_model ../models/middlebury_d400.pb --input_shape [1,375,640,6] --disable_nhwc_to_nchw --data_type=FP16`

It works perfectly! But when I need to add --mean_values and --scale_values with 6 channels:

`mo --input_model ../models/middlebury_d400.pb --input_shape [1,375,640,6] --disable_nhwc_to_nchw --data_type=FP16 --mean_values=[0,0,0,0,0,0] --scale_values=[255,255,255,255,255,255]`

I encountered the following error:

```
(openvino) (base) paul@uai2:~/tf2.x/hitnet-test/openvino$ ./mo.bat 
[ WARNING ]  Use of deprecated cli option --disable_nhwc_to_nchw detected. Option use in the following releases will be fatal. 
Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	/home/paul/tf2.x/hitnet-test/openvino/../models/middlebury_d400.pb
	- Path for generated IR: 	/home/paul/tf2.x/hitnet-test/openvino/.
	- IR output name: 	middlebury_d400
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	[1,375,640,6]
	- Source layout: 	Not specified
	- Target layout: 	Not specified
	- Layout: 	Not specified
	- Mean values: 	[0,0,0,0,0,0]
	- Scale values: 	[255,255,255,255,255,255]
	- Scale factor: 	Not specified
	- Precision of IR: 	FP16
	- Enable fusing: 	True
	- User transformations: 	Not specified
	- Reverse input channels: 	False
	- Enable IR generation for fixed input shape: 	False
	- Use the transformations config file: 	None
Advanced parameters:
	- Force the usage of legacy Frontend of Model Optimizer for model conversion into IR: 	False
	- Force the usage of new Frontend of Model Optimizer for model conversion into IR: 	False
TensorFlow specific parameters:
	- Input model in text protobuf format: 	False
	- Path to model dump for TensorBoard: 	None
	- List of shared libraries with TensorFlow custom layers implementation: 	None
	- Update the configuration file with input/output node names: 	None
	- Use configuration file used to generate the model with Object Detection API: 	None
	- Use the config file: 	None
OpenVINO runtime found in: 	/home/paul/openvino/lib/python3.8/site-packages/openvino
OpenVINO runtime version: 	2022.1.0-7019-cdb9bec7210-releases/2022/1
Model Optimizer version: 	2022.1.0-7019-cdb9bec7210-releases/2022/1
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID (<class 'openvino.tools.mo.middle.AddMeanScaleValues.AddMeanScaleValues'>)": Incompatible layout, please specify correct layout for the node
[ ERROR ]  Traceback (most recent call last):
  File "/home/paul/openvino/lib/python3.8/site-packages/openvino/tools/mo/utils/class_registration.py", line 276, in apply_transform
    replacer.find_and_replace_pattern(graph)
  File "/home/paul/openvino/lib/python3.8/site-packages/openvino/tools/mo/middle/AddMeanScaleValues.py", line 150, in find_and_replace_pattern
    AddMeanScaleValues.apply_scale(graph, input_node, node_mean_scale_values)
  File "/home/paul/openvino/lib/python3.8/site-packages/openvino/tools/mo/middle/AddMeanScaleValues.py", line 93, in apply_scale
    AddMeanScaleValues.insert_pre_processing(graph, input_node, node_mean_scale_values, preprocessing_name='scale')
  File "/home/paul/openvino/lib/python3.8/site-packages/openvino/tools/mo/middle/AddMeanScaleValues.py", line 52, in insert_pre_processing
    assert compatible_dims(value.size, input_node.shape[features_dim_idx]) or value.size == 1, \
AssertionError: Incompatible layout, please specify correct layout for the node

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/paul/openvino/lib/python3.8/site-packages/openvino/tools/mo/main.py", line 533, in main
    ret_code = driver(argv)
  File "/home/paul/openvino/lib/python3.8/site-packages/openvino/tools/mo/main.py", line 489, in driver
    graph, ngraph_function = prepare_ir(argv)
  File "/home/paul/openvino/lib/python3.8/site-packages/openvino/tools/mo/main.py", line 407, in prepare_ir
    graph = unified_pipeline(argv)
  File "/home/paul/openvino/lib/python3.8/site-packages/openvino/tools/mo/pipeline/unified.py", line 13, in unified_pipeline
    class_registration.apply_replacements(graph, [
  File "/home/paul/openvino/lib/python3.8/site-packages/openvino/tools/mo/utils/class_registration.py", line 328, in apply_replacements
    apply_replacements_list(graph, replacers_order)
  File "/home/paul/openvino/lib/python3.8/site-packages/openvino/tools/mo/utils/class_registration.py", line 314, in apply_replacements_list
    apply_transform(
  File "/home/paul/openvino/lib/python3.8/site-packages/openvino/tools/mo/utils/logger.py", line 112, in wrapper
    function(*args, **kwargs)
  File "/home/paul/openvino/lib/python3.8/site-packages/openvino/tools/mo/utils/class_registration.py", line 302, in apply_transform
    raise Exception('Exception occurred during running replacer "{} ({})": {}'.format(
Exception: Exception occurred during running replacer "REPLACEMENT_ID (<class 'openvino.tools.mo.middle.AddMeanScaleValues.AddMeanScaleValues'>)": Incompatible layout, please specify correct layout for the node

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------
```

For system info and model download, please refer to [here](https://github.com/openvinotoolkit/openvino/issues/11824#issuecomment-1151651092_)

How could I fix the above error? 

Thanks.

**Comment by ynjiun** [comment]
fortunately enough, for this special case of 0 means, I can do this:

`mo --input_model ../models/middlebury_d400.pb --input_shape [1,375,640,6] --disable_nhwc_to_nchw --data_type=FP16 --scale=255`

for this specific case, case closed.

But for general 6 channel case, still open ; ))

**Comment by zulkifli-halim** [comment]
Hello @ynjiun, OpenVINO officially supports up to 5 channels, you may refer to [Supported Output Layout](https://docs.openvino.ai/latest/openvino_docs_OV_UG_supported_plugins_Supported_Devices.html#supported-input-layout).

Regarding the 6 channels issue, we are investigating this issue and will get it soon.

**Comment by microaisystems** [comment]
@jgespino

Thank you so much for your help. I am able to duplicate your success! Case closed.

However, my end goal is to get this model to run on Myriad, so I need to compile this IR into a VPU blob. I  tried the following command to convert the above success IR:

```
/opt/intel/openvino_2022/tools/compile_tool/compile_tool \
    -m ./middlebury_d400.xml \
    -d MYRIAD \
    -ip FP16 \
    -VPU_NUMBER_OF_SHAVES 8 \
    -VPU_NUMBER_OF_CMX_SLICES 8 \
    -op FP16 
```
But I encounter the following error message:
```
OpenVINO Runtime version ......... 2022.1.0
Build ........... 2022.1.0-7019-cdb9bec7210-releases/2022/1
Network inputs:
    input : f16 / [N,H,W,C]
Network outputs:
    reference_output_disparity:0 : f16 / [...]
[ GENERAL_ERROR ] 
/home/jenkins/agent/workspace/private-ci/ie/build-linux-ubuntu20/b/repos/openvino/src/plugins/intel_myriad/graph_transformer/src/frontend/frontend.cpp:592 Failed to compile layer "level0/shared/prop0/WarpImageWithHypotheses/get_warp1d_coordinates_from_tile_hypotheses/get_warp_disparity": [ GENERAL_ERROR ] 
/home/jenkins/agent/workspace/private-ci/ie/build-linux-ubuntu20/b/repos/openvino/src/plugins/intel_myriad/graph_transformer/src/model/model.cpp:198 duplicateData error: while duplicating level0/shared/prop0/WarpImageWithHypotheses/get_warp1d_coordinates_from_tile_hypotheses/get_warp_disparity@weights Const data got different desc and content byte sizes (24 and 96 respectively)
```

Could you help to check what am I missing? Thanks a lot again for your help!

**Comment by jgespino** [comment]
@microaisystems Could you check if all the ops in your model are supported by MYRIAD? 
https://docs.openvino.ai/latest/openvino_docs_OV_UG_supported_plugins_Supported_Devices.html#supported-layers

If they are, would you mind starting a new issue and filling out the issue template?
