### ISSUE TITLE
Facing a issue while training SSD for head detection

### ISSUE THREAD

**Issue by Saif0765** [openvinotoolkit/openvino#11919]
ValueError                                Traceback (most recent call last)
Input In [53], in <cell line: 1>()
----> 1 model.fit(
      2   train_ds,
      3   validation_data=val_ds,
      4   epochs=3
      5 )

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py:67, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     65 except Exception as e:  # pylint: disable=broad-except
     66   filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67   raise e.with_traceback(filtered_tb) from None
     68 finally:
     69   del filtered_tb

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\framework\func_graph.py:1147, in func_graph_from_py_func.<locals>.autograph_handler(*args, **kwargs)
   1145 except Exception as e:  # pylint:disable=broad-except
   1146   if hasattr(e, "ag_error_metadata"):
-> 1147     raise e.ag_error_metadata.to_exception(e)
   1148   else:
   1149     raise

ValueError: in user code:

    File "C:\Users\Asif Raza\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 1021, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\Asif Raza\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 1010, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\Asif Raza\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 1000, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\Asif Raza\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 859, in train_step
        y_pred = self(x, training=True)
    File "C:\Users\Asif Raza\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None

    ValueError: Exception encountered when calling layer "ssd_5" (type SSD).
    
    in user code:
    
        File "C:\Users\Asif Raza\AppData\Local\Temp\ipykernel_13856\2247770214.py", line 43, in call  *
            self.features[5] = self.conv4_2(self.conv4_1(self.features[4]))
        File "C:\Users\Asif Raza\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler  **
            raise e.with_traceback(filtered_tb) from None
    
        ValueError: Exception encountered when calling layer "SSD_conv_4_2" (type Conv2D).
        
        Negative dimension size caused by subtracting 2 from 1 for '{{node ssd_5/SSD_conv_4_2/Conv2D}} = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], explicit_paddings=[], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true](ssd_5/SSD_conv_4_1/BiasAdd, ssd_5/SSD_conv_4_2/Conv2D/ReadVariableOp)' with input shapes: [?,1,1,128], [2,2,128,256].
        
        Call arguments received:
          • inputs=tf.Tensor(shape=(None, 1, 1, 128), dtype=float32)
    
    
    Call arguments received:
      • inputs=tf.Tensor(shape=(None, 180, 180, 3), dtype=float32)

**Comment by brmarkus** [comment]
@Saif0765 would you mind moving your issue to e.g. the KERAS team?
Is this related to OpenVINO?

**Comment by Saif0765** [comment]
> @Saif0765 would you mind moving your issue to e.g. the KERAS team? Is this related to OpenVINO?

Yes please move,
Not related to OpenVINO

**Comment by jgespino** [comment]
@Saif0765 It's a separate repository. Please open a new issue here: https://github.com/keras-team/keras/issues
