### ISSUE TITLE
[Bug]Openvino example "hello_reshape_ssd" using readme.md model running failed.

### ISSUE THREAD

**Issue by Phoebus-Ma** [openvinotoolkit/openvino#12344]
##### Detailed description
using openvino python example "hello_reshape_ssd" readme.md model file, running python example failed.
openvino/samples/python/hello_reshape_ssd/hello_reshape_ssd.py

##### Steps to reproduce

Step [1]:

**Failed for using readme ssdlite_mobilenet_v2 model.**

```console
$ omz_downloader --name ssdlite_mobilenet_v2
$ omz_converter --name ssdlite_mobilenet_v2
$ python hello_reshape_ssd.py ssdlite_mobilenet_v2.xml banana.jpg GPU
[ INFO ] Creating OpenVINO Runtime Core
[ INFO ] Reading the model: ssdlite_mobilenet_v2.xml
[ INFO ] Reshaping the model to the height and width of the input image
Traceback (most recent call last):
  File ".\hello_reshape_ssd.py", line 120, in <module>
    sys.exit(main())
  File ".\hello_reshape_ssd.py", line 53, in main
    model.reshape({model.input().get_any_name(): PartialShape((n, c, h, w))})
RuntimeError: Check 'input_shape[1].compatible(filters_shape[1])' failed at C:\j\workspace\private-ci\ie\build-windows-vs2019@3\b\repos\openvino\src\core\shape_inference\include\convolution_shape_inference.hpp:265:
While validating node 'v1::Convolution FeatureExtractor/MobilenetV2/Conv/BatchNorm/batchnorm/mul_1 (Preprocessor/sub[0]:f32{1,1699,3,960}, FeatureExtractor/MobilenetV2/Conv/weights/read/_101__cf__104[0]:f32{32,3,3,3}) -> (f32{1,32,150,150})' with friendly_name 'FeatureExtractor/MobilenetV2/Conv/BatchNorm/batchnorm/mul_1':
Data batch channel count (1699) does not match filter input channel count (3).
```
----------------------------------------------------------------
Step [2]:

**Success for person-detection-retail-0013 model file.**

```console
$ omz_downloader --name person-detection-retail-0013
$ python hello_reshape_ssd.py person-detection-retail-0013.xml person_detection.png GPU
[ INFO ] Creating OpenVINO Runtime Core
[ INFO ] Reading the model: person-detection-retail-0013.xml
[ INFO ] Reshaping the model to the height and width of the input image
[ INFO ] Loading the model to the plugin
[ INFO ] Starting inference in synchronous mode
[ INFO ] Found: class_id = 1, confidence = 0.72, coords = (852, 187), (983, 520)
[ INFO ] Image out.bmp was created!
[ INFO ] This sample is an API example, for any performance measurements please use the dedicated benchmark_app tool
```

**Comment by zulkifli-halim** [comment]
Hi @Phoebus-Ma.

I tested the Hello Reshape SSD Python Sample on my end using OpenVINO 2022.1 and received a similar error as yours:
```
[ INFO ] Creating OpenVINO Runtime Core
[ INFO ] Reading the model: ssdlite_mobilenet_v2.xml
[ INFO ] Reshaping the model to the height and width of the input image
Traceback (most recent call last):
  File "C:\Program Files (x86)\Intel\openvino_2022.1.0.643\samples\python\hello_reshape_ssd\hello_reshape_ssd.py", line 120, in <module>
    sys.exit(main())
  File "C:\Program Files (x86)\Intel\openvino_2022.1.0.643\samples\python\hello_reshape_ssd\hello_reshape_ssd.py", line 53, in main
    model.reshape({model.input().get_any_name(): PartialShape((n, c, h, w))})
RuntimeError: Check 'input_shape[1].compatible(filters_shape[1])' failed at C:\j\workspace\private-ci\ie\build-windows-vs2019@3\b\repos\openvino\src\core\shape_inference\include\convolution_shape_inference.hpp:265:
While validating node 'v1::Convolution FeatureExtractor/MobilenetV2/Conv/BatchNorm/batchnorm/mul_1 (Preprocessor/sub[0]:f32{1,476,3,363}, FeatureExtractor/MobilenetV2/Conv/weights/read/_101__cf__104[0]:f32{32,3,3,3}) -> (f32{1,32,150,150})' with friendly_name 'FeatureExtractor/MobilenetV2/Conv/BatchNorm/batchnorm/mul_1':
Data batch channel count (476) does not match filter input channel count (3).
```


I also tested the sample using OpenVINO 2021.4 and it works fine.
```
[ INFO ] Creating Inference Engine
[ INFO ] Reading the network: ssdlite_mobilenet_v2.xml
[ INFO ] Configuring input and output blobs
[ INFO ] Reshaping the network to the height and width of the input image
[ INFO ] Input shape before reshape: [1, 3, 300, 300]
[ INFO ] Input shape after reshape: [1, 3, 363, 476]
[ INFO ] Loading the model to the plugin
[ INFO ] Starting inference in synchronous mode
[ INFO ] Found: label = 52, confidence = 0.78, coords = (122, 31), (362, 301)
[ INFO ] Image out.bmp was created!
[ INFO ] This sample is an API example, for any performance measurements please use the dedicated benchmark_app tool
```

I'm checking this out and will get back to you soon.

**Comment by zulkifli-halim** [comment]
Hi @Phoebus-Ma.

This is a known issue as the hello_reshape_ssd sample is designed to support models with NCHW layout, this is not a universal tool. If you need a universal app then please use the OMZ demo. The team is working to update the document. 

In the meantime, please use this command to run the sample:
```
omz_downloader --name mobilenet-ssd
omz_converter --name mobilenet-ssd
python hello_reshape_ssd.py mobilenet-ssd.xml banana.jpg GPU
```

**Comment by Phoebus-Ma** [comment]
Hi @zulkifli-halim 
Thanks for your help, I know it might be possible to use other model files.
As you did in the experiment: 
hello_reshape_ssd version 2022.1 is failed, but version 2021.4 is ok,
I think this is a problem caused by your code update, not a problem in itself.
So, What are you going to do next?

**Comment by zulkifli-halim** [comment]
Hi @Phoebus-Ma.

There are code modifications in hellp_reshape_ssd.py in the latest release. We will update the documentation to make it relevant with the current release.

**Comment by Phoebus-Ma** [comment]
Close the issue.
