### ISSUE TITLE
Postprocessor Replacer attempting to find `image_tensor` node not in graph

### ISSUE THREAD

**Issue by abroekhof** [openvinotoolkit/openvino#12765]
I'm attempting to convert a somewhat customized model which is essentially
- EfficientNet
- weight_shared_convolutional_box_predictor
- batch_non_max_suppression

I've been making somewhat steady process in squelching errors, but not sure how to get past this one. It appears that I'm mostly replacing the `batch_non_max_suppression` with `DetectionOutput`, but then in gets stuck trying to find a specific node in the graph. Is there someway to bypass this?

```
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Exception occurred during running replacer "ObjectDetectionAPISSDPostprocessorReplacement (<class 'openvino.tools.mo.front.tf.ObjectDetectionAPI.ObjectDetectionAPISSDPostprocessorReplacement'>)": Attempt to access node image_tensor that not in graph
[ ERROR ]  Traceback (most recent call last):
  File "openvino/openvino_env/lib/python3.9/site-packages/openvino/tools/mo/utils/class_registration.py", line 276, in apply_transform
    replacer.find_and_replace_pattern(graph)
  File "openvino/openvino_env/lib/python3.9/site-packages/openvino/tools/mo/front/tf/replacement.py", line 83, in find_and_replace_pattern
    self.replace_sub_graph(graph, match)
  File "openvino/openvino_env/lib/python3.9/site-packages/openvino/tools/mo/front/common/replacement.py", line 126, in replace_sub_graph
    new_sub_graph = self.generate_sub_graph(graph, match)  # pylint: disable=assignment-from-no-return
  File "openvino/openvino_env/lib/python3.9/site-packages/openvino/tools/mo/front/tf/ObjectDetectionAPI.py", line 1647, in generate_sub_graph
    priors_node = _create_multiscale_prior_boxes_node(graph, pipeline_config)
  File "openvino/openvino_env/lib/python3.9/site-packages/openvino/tools/mo/front/tf/ObjectDetectionAPI.py", line 302, in _create_multiscale_prior_boxes_node
    prior_box_node = prior_box_op.create_node([ssd_head_node, Node(graph, 'image_tensor').out_node(0)],
  File "openvino/openvino_env/lib/python3.9/site-packages/openvino/tools/mo/graph/graph.py", line 25, in __init__
    assert node in graph, "Attempt to access node {} that not in graph".format(node)
AssertionError: Attempt to access node image_tensor that not in graph

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "openvino/openvino_env/lib/python3.9/site-packages/openvino/tools/mo/main.py", line 533, in main
    ret_code = driver(argv)
  File "openvino/openvino_env/lib/python3.9/site-packages/openvino/tools/mo/main.py", line 489, in driver
    graph, ngraph_function = prepare_ir(argv)
  File "openvino/openvino_env/lib/python3.9/site-packages/openvino/tools/mo/main.py", line 407, in prepare_ir
    graph = unified_pipeline(argv)
  File "openvino/openvino_env/lib/python3.9/site-packages/openvino/tools/mo/pipeline/unified.py", line 13, in unified_pipeline
    class_registration.apply_replacements(graph, [
  File "openvino/openvino_env/lib/python3.9/site-packages/openvino/tools/mo/utils/class_registration.py", line 328, in apply_replacements
    apply_replacements_list(graph, replacers_order)
  File "openvino/openvino_env/lib/python3.9/site-packages/openvino/tools/mo/utils/class_registration.py", line 314, in apply_replacements_list
    apply_transform(
  File "openvino/openvino_env/lib/python3.9/site-packages/openvino/tools/mo/utils/logger.py", line 112, in wrapper
    function(*args, **kwargs)
  File "openvino/openvino_env/lib/python3.9/site-packages/openvino/tools/mo/utils/class_registration.py", line 302, in apply_transform
    raise Exception('Exception occurred during running replacer "{} ({})": {}'.format(
Exception: Exception occurred during running replacer "ObjectDetectionAPISSDPostprocessorReplacement (<class 'openvino.tools.mo.front.tf.ObjectDetectionAPI.ObjectDetectionAPISSDPostprocessorReplacement'>)": Attempt to access node image_tensor that not in graph

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------
```
**Command**
```
$ mo --saved_model_dir models/all_allsites7/saved_model/1660062231 --tensorboard_logdir .  --tensorflow_object_detection_api_pipeline_config models/all_allsites7/pipeline_mod.config --transformations_config models/all_allsites7/ssd_support_custom.json --input 0:ExpandDims_5 --input_shape [640,640,3] --log_level=DEBUG
```

**JSON file**
```
    {
        "custom_attributes": {
            "code_type": "caffe.PriorBoxParameter.CENTER_SIZE",
            "pad_mode": "caffe.ResizeParameter.CONSTANT",
            "resize_mode": "caffe.ResizeParameter.WARP",
            "clip_before_nms": false,
            "clip_after_nms": true
        },
        "id": "ObjectDetectionAPISSDPostprocessorReplacement",
        "include_inputs_to_sub_graph": true,
        "include_outputs_to_sub_graph": true,
        "instances": {
            "end_points": [
                "detection_boxes",
                "detection_scores",
                "num_detections"
            ],
            "start_points": [
                "Postprocessor/scale_logits",
                "Postprocessor/Tile",
                "Postprocessor/Reshape_1",
                "Postprocessor/Cast_1"
            ]
        },
        "match_kind": "points"
    }
```

**Relevant` portion of pipeline.config**
```
    anchor_generator {
      multiscale_anchor_generator {
        min_level: 3
        max_level: 7
        anchor_scale: 3.0
        aspect_ratios: 1.0
        aspect_ratios: 2.0
        aspect_ratios: 0.5
        scales_per_octave: 3
      }
    }
    post_processing {
      batch_non_max_suppression {
        score_threshold: 9.99999993922529e-09
        iou_threshold: 0.6000000238418579
        max_detections_per_class: 100
        max_total_detections: 100
        use_static_shapes: true
      }
      score_converter: SIGMOID
    }
```

**Comment by Iffa-Meah** [comment]
@abroekhof could you provide:
1. Your model framework and topology, eg: Framework: Tensorflow, Topology:Inceptionv1
2. Model files and the relevant config files

**Comment by rkazants** [comment]
@abroekhof, please try not to specify the custom input `0:ExpandDims_5` because you actually cut the graph and for this reason the transformation can't find the original input `image_tensor`. Try to launch the conversion as follows:
```
mo --saved_model_dir models/all_allsites7/saved_model/1660062231 --tensorflow_object_detection_api_pipeline_config models/all_allsites7/pipeline_mod.config --transformations_config models/all_allsites7/ssd_support_custom.json
```

**Comment by abroekhof** [comment]
@rkazants our model is using the [TF Object Detection API](https://github.com/tensorflow/models/tree/master/research/object_detection) which relies on protobuf encoding of examples. This is part of the model, so I had to cut it off, which is why that `image_tensor` node doesn't exist. 

I understand this is somewhat outside the scope of what's supported in OpenVINO, so will close this for the time being
