### ISSUE TITLE
[Bug] Conversion from ONNX model fails

### ISSUE THREAD

**Issue by narang99** [openvinotoolkit/openvino#13207]
Hey
Im getting errors in converting an onnx model to vino

Command ran:
```
mo --input_model model.onyx --input_shape [1,2,1,960,320]
```

And got this log
```
Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	/home/ubuntu/workspace/bench/cxr_product/onnx_models/cavity.onyx
	- Path for generated IR: 	/home/ubuntu/workspace/bench/cxr_product/vino_models/.
	- IR output name: 	cavity
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	[1,2,1,960,320]
	- Source layout: 	Not specified
	- Target layout: 	Not specified
	- Layout: 	Not specified
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP32
	- Enable fusing: 	True
	- User transformations: 	Not specified
	- Reverse input channels: 	False
	- Enable IR generation for fixed input shape: 	False
	- Use the transformations config file: 	None
Advanced parameters:
	- Force the usage of legacy Frontend of Model Optimizer for model conversion into IR: 	False
	- Force the usage of new Frontend of Model Optimizer for model conversion into IR: 	False
OpenVINO runtime found in: 	/home/ubuntu/intel/openvino_2022/python/python3.8/openvino
OpenVINO runtime version: 	2022.1.0-7019-cdb9bec7210-releases/2022/1
Model Optimizer version: 	2022.1.0-7019-cdb9bec7210-releases/2022/1
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Check 'i < input_pshape.rank().get_length()' failed at core/src/op/reshape.cpp:391:
While validating node 'v1::Reshape Reshape_120459 (3098[0]:f32{?,?,?,?}, 3111[0]:i64{5}) -> (f32{?,?,?,?,?})' with friendly_name 'Reshape_120459':
'0' dimension is out of range

[ ERROR ]  Traceback (most recent call last):
  File "/home/ubuntu/workspace/bench/cxr_product/vino_models/vino/lib/python3.9/site-packages/openvino/tools/mo/main.py", line 533, in main
    ret_code = driver(argv)
  File "/home/ubuntu/workspace/bench/cxr_product/vino_models/vino/lib/python3.9/site-packages/openvino/tools/mo/main.py", line 493, in driver
    ret_res = moc_emit_ir(ngraph_function, argv)
  File "/home/ubuntu/workspace/bench/cxr_product/vino_models/vino/lib/python3.9/site-packages/openvino/tools/mo/moc_frontend/serialize.py", line 25, in moc_emit_ir
    apply_moc_transformations(ngraph_function)
  File "/home/ubuntu/workspace/bench/cxr_product/vino_models/vino/lib/python3.9/site-packages/openvino/tools/mo/back/offline_transformations.py", line 39, in apply_moc_transformations
    apply_moc_transformations(func, False)
RuntimeError: Check 'i < input_pshape.rank().get_length()' failed at core/src/op/reshape.cpp:391:
While validating node 'v1::Reshape Reshape_120459 (3098[0]:f32{?,?,?,?}, 3111[0]:i64{5}) -> (f32{?,?,?,?,?})' with friendly_name 'Reshape_120459':
'0' dimension is out of range


[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------
```

Could not find much online about this, can you please help me?

System
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
Stepping:                        4
CPU MHz:                         2500.000
BogoMIPS:                        5000.00
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        4 MiB
L3 cache:                        33 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscal
                                 l nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq sss
                                 e3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lah
                                 f_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx
                                 512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida ar
                                 at pku ospke

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

Linux kernel version
```
5.15.0-1020-aws
```

**NOTE: Was doing this test on an EC2 t3.2xlarge Ubuntu machine**

Thanks!

**Comment by mlukasze** [comment]
Hi @narang99 
Thank you for rising this issue. Please, let us check it, we will back to you with more clear information as soon as possible.

**Comment by mateusztabaka** [comment]
Can you share the cavity.onyx model?

**Comment by tomdol** [comment]
The error looks like some inconsistency in the shapes around a Reshape operation. It's difficult to figure out why without the model. Can you share it?

**Comment by tomdol** [comment]
I've done another pass over the Reshape operator's code and it seems that one of the Reshapes in the model contains a `0` (zero) in the target shape pattern. In this particular model this configuration produces the exception you encountered (because the "special_zero" attribute is set to false). We could still have a look but at the same time you can try to investigate the Reshape operation and see if that zero in the target shape is correct.

**Comment by t-jankowski** [comment]
@tomdol 'special_zero' is OV term. ONNX calls it 'allowzero' and is defaulted to copy the value, so the case you describe. However the exception happens while proceeding with OV model, not sure whether before or after transformations. So either there's hardcoded in the ONNX model 0 value as the 5-th element of that 'shape' tensor or it needs to be debugged.

**Comment by narang99** [comment]
The shapes look like this
```
Input: numpy array shape (1, 2, 1, 960, 320)
Output: A list of numpy arrays with these shapes
[(3, 2), (3, 2, 2, 1), (3, 2, 6, 1), (3, 2, 2, 960, 320)]
```

Sorry, I cant provide the model itself, corporate policy😅    


It would be great if you can guide me into debugging this please (some reference document or steps I need to take).  
Sorry but I didnt understand what you meant here
```
I've done another pass over the Reshape operator's code and it seems that one of the Reshapes in the model contains a 0 (zero) in the target shape pattern. 
```

**Comment by tomdol** [comment]
Overall you need to investigate a Reshape operation in the model. The clues are in this line:
`v1::Reshape Reshape_120459 (3098[0]:f32{?,?,?,?}, 3111[0]:i64{5}) -> (f32{?,?,?,?,?})' with friendly_name 'Reshape_120459'`.
Probably the Reshape operation you're looking for is called "Reshape_120459". It has 2 inputs named "3098" and "3111" - you can use those input names to find this operation too (for example in Netron).
This Reshape operation takes a 4D input with unknown dimensions - `{?, ?, ?, ?}`. The second input with shape `{5}` indicates that the desired output shape after this operation is 5D. One of the values in the second input tensor (the target shape) seems to be equal to zero. Zero has a special meaning and it will be easier to help you if you share the values of this input tensor (`3111` is probably a Constant or an initializer so you should be able to access its values in Netron).

**Comment by t-jankowski** [comment]
Below code triggers the same error. The two commented `new_shape`'s have valid values - note that 0 at first position is ok.
```
from openvino.runtime import Core, Model, Tensor, PartialShape
import numpy as np
import openvino.runtime.opset9 as ov

core = Core()
input = ov.parameter(PartialShape([-1, -1, -1, -1]), dtype=np.float32, name="A")
new_shape = ov.constant(np.array(  [ 0, 10, 2, 5, 0]))        # error
# new_shape = ov.constant(np.array([ 0, 10, 2, 5, -1]))       # ok
# new_shape = ov.constant(np.array([10, 10, 2, 5, 3]))        # ok, actual output's shape
reshape = ov.reshape(input, new_shape, True)
model = Model(reshape, [input])
compiled_model = core.compile_model(model)
req = compiled_model.create_infer_request()
req.infer({"A": Tensor(np.random.random((10, 10, 10, 3)).astype(np.float32))})
```

**Comment by narang99** [comment]
![Screenshot 2022-09-29 at 5 47 39 PM](https://user-images.githubusercontent.com/39337152/193029336-e767f09d-5b7b-44a8-835f-143f0934c8f7.png)

This is what it looks like, doesn't look like its a constant @tomdol

**Comment by tomdol** [comment]
From the screenshot it looks like the second input of Reshape is not a constant, it's a subgraph which gets evaluated by MO during the conversion (constant folding). This evaluation produces a zero in the target shape tensor and thus the error. Unfortunately without the access to the full model I'm not able to suggest anything else. @jane-intel perhaps you have an idea how to overcome the problem?

**Comment by andrei-kochin** [comment]
@jane-intel any brilliant ideas here?

**Comment by avitial** [comment]
@jane-intel gentle ping. 


@narang99 I understand you cannot share the full model due to corporate policy, would it be possible to share a minimal sample model in which the error reproduces?

**Comment by avitial** [comment]
Closing this as nothing further can be suggested without access to the model, I hope previous responses were sufficient to help you proceed or resolve the issue. Feel free to reopen to ask any questions related to this topic, and if issue persists kindly share the requested minimal sample model.
