### ISSUE TITLE
INT8 calibration error using Python tool

### ISSUE THREAD

**Issue by mrsabhar** [openvinotoolkit/openvino#137]
Seeing error during calibration - FP32 model works fine.

00:38:06 openvino.tools.calibration INFO: Starting to reduce number of layers being converted to Int8
00:38:06 openvino.tools.calibration INFO: Returning of '388' to FP32 precision, start validation
IE version: 1.6.23224
Loaded CPU plugin version: 1.6.23224
12 objects processed in 0.370 seconds
IE version: 1.6.23224
Loaded CPU plugin version: 1.6.23224
00:38:10 openvino.tools.benchmark INFO: only one first image is used from dataset annotation to perform benchmark
00:38:10 openvino.tools.calibration INFO: Was not achieved: FP32 accuracy: 91.6667% (latency: 52.8 ms) VS INT8 accuracy: 
50.0000% (latency 16.9650 ms), accuracy drop 41.6667%
00:38:10 openvino.tools.calibration INFO: Returning of '423' to FP32 precision, start validation
IE version: 1.6.23224
Loaded CPU plugin version: 1.6.23224
Traceback (most recent call last):
  File "C:\test\openvino_2019.1.133\python\python3.6\openvino\tools\calibration\base_calibrator.py", line 435, in _infer
    model_evaluator.launcher.exec_network = model_evaluator.launcher.plugin.load(network)
  File "ie_api.pyx", line 395, in openvino.inference_engine.ie_api.IEPlugin.load
  File "ie_api.pyx", line 406, in openvino.inference_engine.ie_api.IEPlugin.load
RuntimeError: Supported primitive descriptors list is empty for node: 431

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibrate.py", line 21, in <module>
    network = calibration.Calibrator(config).run()
  File "C:\test\openvino_2019.1.133\python\python3.6\openvino\tools\calibration\calibrator.py", line 176, in run        
    with calibrator.infer(network=reloaded_network.ie_network) as layer_int8_result:
  File "C:\test\openvino_2019.1.133\python\python3.6\openvino\tools\calibration\base_calibrator.py", line 380, in infer 
    collect_performance_counters=collect_performance_counters)
  File "C:\test\openvino_2019.1.133\python\python3.6\openvino\tools\calibration\base_calibrator.py", line 490, in _infer
    model_evaluator.release()
  File "C:\test\openvino_2019.1.133\python\python3.6\openvino\tools\accuracy_checker\accuracy_checker\model_evaluator.py", line 132, in release
    self.launcher.release()
  File "C:\test\openvino_2019.1.133\python\python3.6\openvino\tools\accuracy_checker\accuracy_checker\launcher\dlsdk_launcher.py", line 429, in release
    del self.exec_network
AttributeError: exec_network

**Comment by shubha-ramani** [comment]
Dear @mrsabhar

Can you give me your entire command_line for calibrate.py ? 

Thanks,

Shubha

**Comment by mrsabhar** [comment]
Command line I'm using --> 
python calibration.py -c model_name.yml -ic 10.

**Comment by shubha-ramani** [comment]
Dear @mrsabhar 

Your command should look more along the lines of this (say, for an inception v4 model) and ImageNet images:

python calibrate.py --config ~/inception_v4.yml --definition ~/definitions.yml -M /home/mickeymouse/intel/openvino/deployment_tools/model_optimizer --tf_custom_op_config_dir ~/tf_custom_op_configs --models ~/models --source /media/user/icv_externalN/omz-validation-datasets --annotations ~/annotations –cfc

Please refer to the following documentation:
[https://docs.openvinotoolkit.org/latest/_inference_engine_tools_calibration_tool_README.html](https://docs.openvinotoolkit.org/latest/_inference_engine_tools_calibration_tool_README.html)

Thanks,

Shubha

**Comment by AnastasiaKazantaeva** [comment]
Seems that suggested command line helped to execute calibration tool. Closing this issue.
