### ISSUE TITLE
importlib.metadata.PackageNotFoundError: omz-tools

### ISSUE THREAD

**Issue by jiapei100** [openvinotoolkit/openvino#13724]
Successfully built and installed **OpenVINO**, both on **Ubuntu 22.04.1** and **Raspbian GNU/Linux 11 (bullseye) armv7l **.

However, when I tried to follow the [Official Downloader](https://docs.openvino.ai/latest/omz_tools_downloader.html) and use `omz_downloader --all` to download the model, I met the **ERROR** as titled:

```console
➜  bin git:(master) ✗ ./omz_downloader --all
Traceback (most recent call last):
  File "....../openvino/build/tools/openvino_dev/build/omz_tools/bin/./omz_downloader", line 33, in <module>
    sys.exit(load_entry_point('omz-tools==1.0.2', 'console_scripts', 'omz_downloader')())
  File "....../openvino/build/tools/openvino_dev/build/omz_tools/bin/./omz_downloader", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: omz-tools
```

Similar to command `omz_data_downloader` to download the test data:

```console
➜  bin git:(master) ✗ ./omz_data_downloader 
Traceback (most recent call last):
  File "....../openvino/build/tools/openvino_dev/build/omz_tools/bin/./omz_data_downloader", line 33, in <module>
    sys.exit(load_entry_point('omz-tools==1.0.2', 'console_scripts', 'omz_data_downloader')())
  File "....../openvino/build/tools/openvino_dev/build/omz_tools/bin/./omz_data_downloader", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: omz-tools
```

I actually can manually download the data in some other way, but how about the models? Thank you ...

**Comment by eaidova** [comment]
@jiapei100 could you please describe how you install openvino? Do you install `openvino-dev` package and use `omz-downloader` (which version) from it or use different approach?  Fot me, path looks strange, here should not be build subdirectories in your path

**Comment by eaidova** [comment]
Also could you please try from another directory and without usage `./` prefix, it is entry points, which should be used as shell commands, not physical files

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and provide additional information or ask any questions related to this topic.
