### ISSUE TITLE
Error occurred when reshaping model in python

### ISSUE THREAD

**Issue by yszhou2019** [openvinotoolkit/openvino#13777]
##### System information (version)
OpenVINO => 2022.2.0
Operating System / Platform => Linux 64 Bit
Problem classification: Model Reshape
Framework: PyTorch
ONNXRuntime: 1.13.1
Python Version: 3.9.7

##### Detailed description
I'm trying to deploy ASR model in python using OpenVINO as runtime.(According to previous experience, inference can be about 20%~50% faster when using OpenVINO compared with ONNXRuntime. Both of them can read models in ONNX format.)
However, something was wrong when I tried to reshape the model. The following codes read the decoder and set specific shapes of several input tensors. But the mocked inputs for decoder have the same shape for ONNXRuntime and OpenVINO. So, I have no idea how to do it.
```python
        decoder_model = core.read_model(decoder_path)
        shapes = [
            [1, 15012, 1024],
            [1, 15012],
            [1, 1],
            [2, 1, 1024],
            [2, 1, 1024],
            [3, 1],
            [3],
            [1, 3, 1024],
            [1, 3, 1024],
        ]
        partial_shapes = { index: ov.PartialShape(shape) for index, shape in enumerate(shapes) }
        # **RuntimeError**
        decoder_model.reshape(partial_shapes)
        self.decoder = core.compile_model(decoder_model, "CPU")
        print("decoder compiled")
```

```python
[root@03815bf6f960 tests]# python3 ov.py 
Traceback (most recent call last):
  File "/app/tests/ov.py", line 52, in <module>
    ov_model = OpenVINOStaticWrapper(encoder_path, decoder_path)
  File "/app/src/app/utils/ov_utils.py", line 69, in __init__
    decoder_model.reshape(partial_shapes)
RuntimeError: Check 'DimType::merge(merged_dimension, arg0_col_dim, arg1_row_dim) || arg0_col_dim.is_dynamic() || arg1_row_dim.is_dynamic()' failed at core/shape_inference/include/matmul_shape_inference.hpp:77:
While validating node 'v0::MatMul MatMul_250 (Softmax_237[0]:f32{1,1,4}, Reshape_249[0]:f32{1,4096}) -> (f32{?,1,1024..})' with friendly_name 'MatMul_250':
Incompatible MatMul matrix dimension. First input dimension=4 at COL_INDEX_DIM=2 doesn't match the second input dimension=1 at ROW_INDEX_DIM=0
```

##### Steps to reproduce

```python
import time
import torch
import numpy as np
import openvino.runtime as ov


class OnnxWrapper:
    def __init__(self, encoder_path: str, decoder_path: str, device: torch.device = torch.device("cpu")) -> None:
        self.device = device
        self.encoder_path = encoder_path
        self.decoder_path = decoder_path

        providers = self.__get_providers(device)
        self.encoder_session = onnxruntime.InferenceSession(
            encoder_path,
            providers=providers,
            sess_options=None
        )
        self.decoder_session = onnxruntime.InferenceSession(
            decoder_path,
            providers=providers,
            sess_options=None
        )

    def encode(self, src_seq, src_mask, hid=None):
        ort_input = {
            self.encoder_session.get_inputs()[0].name: src_seq,
            self.encoder_session.get_inputs()[1].name: src_mask
        }
        return self.encoder_session.run(None, ort_input)

    def decode(self, enc_out, enc_mask, tgt_seq, hid=None, cell=None, padded_bias_phases=None,
               bias_phases_batch=None, bias_hid=None, bias_cell=None):
        ort_input = {
            self.decoder_session.get_inputs()[0].name: enc_out,
            self.decoder_session.get_inputs()[1].name: enc_mask,
            self.decoder_session.get_inputs()[2].name: tgt_seq,
            self.decoder_session.get_inputs()[3].name: hid,
            self.decoder_session.get_inputs()[4].name: cell,
            self.decoder_session.get_inputs()[5].name: padded_bias_phases,
            self.decoder_session.get_inputs()[6].name: bias_phases_batch,
            self.decoder_session.get_inputs()[7].name: bias_hid,
            self.decoder_session.get_inputs()[8].name: bias_cell,
        }
        return self.decoder_session.run(None, ort_input)

    def to(self, device: torch.device):
        if device != self.device:
            self.device = device
            providers = self.__get_providers(device)
            self.encoder_session = onnxruntime.InferenceSession(
                self.encoder_path,
                providers=providers,
                sess_options=None
            )
            self.decoder_session = onnxruntime.InferenceSession(
                self.decoder_path,
                providers=providers,
                sess_options=None
            )
        return self

    def eval(self):
        pass

    def __get_providers(self, device: torch.device):
        if device.type == "cpu":
            providers = ["CPUExecutionProvider"]
        elif device.type == "cuda":
            providers = ["CUDAExecutionProvider"]
        else:
            raise ValueError("Unknown device type")
        return providers


class OpenVINOStaticWrapper:
    
    def __init__(self, encoder_path: str, decoder_path: str, device: torch.device = torch.device("cpu")) -> None:
        self.device = device

        core = ov.Core()

        encoder_model = core.read_model(encoder_path)
        shape1 = ov.PartialShape([1, 60054, 40])
        shape2 = ov.PartialShape([1, 60054])
        encoder_model.reshape({0:shape1, 1:shape2})
        self.encoder = core.compile_model(encoder_model, "CPU")
        print("encoder compiled")

        decoder_model = core.read_model(decoder_path)
        shapes = [
            [1, 15012, 1024],
            [1, 15012],
            [1, 1],
            [2, 1, 1024],
            [2, 1, 1024],
            [3, 1],
            [3],
            [1, 3, 1024],
            [1, 3, 1024],
        ]
        partial_shapes = { index: ov.PartialShape(shape) for index, shape in enumerate(shapes) }
        # **RuntimeError**
        decoder_model.reshape(partial_shapes)
        self.decoder = core.compile_model(decoder_model, "CPU")
        print("decoder compiled")

    def encode(self, src_seq, src_mask, hid=None):
        infer_req = self.encoder.create_infer_request()
        infer_req.set_input_tensor(0, src_seq)
        infer_req.set_input_tensor(1, src_mask)
        s=time.time()
        infer_req.infer()
        print(f"infer {time.time()-s} s")
        return infer_req.get_output_tensor(0), infer_req.get_output_tensor(1)

    def decode(self, enc_out, enc_mask, tgt_seq, hid=None, cell=None, padded_bias_phases=None,
               bias_phases_batch=None, bias_hid=None, bias_cell=None):
        infer_req = self.decoder.create_infer_request()
        infer_req.set_input_tensor(0, enc_out)
        infer_req.set_input_tensor(1, enc_mask)
        infer_req.set_input_tensor(2, tgt_seq)
        infer_req.set_input_tensor(3, hid)
        infer_req.set_input_tensor(4, cell)
        infer_req.set_input_tensor(5, padded_bias_phases)
        infer_req.set_input_tensor(6, bias_phases_batch)
        infer_req.set_input_tensor(7, bias_hid)
        infer_req.set_input_tensor(8, bias_cell)
        infer_req.infer()
        return infer_req.get_output_tensor(0), infer_req.get_output_tensor(1), infer_req.get_output_tensor(2), infer_req.get_output_tensor(3)

# construct input

NUMPY_TYPE_TO_OV_TYPE = {
    np.uint8: ov.Type.u8,
    np.int32: ov.Type.i32,
    np.int64: ov.Type.i64,
    np.float32: ov.Type.f32,
}

def construct_np_encode_input():
    src_seq = np.random.randn(1, 60054, 40).astype(np.float32)
    src_mask = np.random.randn(1, 60054).astype(np.uint8)
    return src_seq, src_mask

def construct_np_decode_input():
    enc_out = np.random.randn(1, 15012, 1024).astype(np.float32)
    enc_mask = np.random.randn(1, 15012).astype(np.uint8)
    tgt_seq = np.random.randn(1, 1).astype(np.int64)
    hid = np.random.randn(2, 1, 1024).astype(np.float32)
    cell = np.random.randn(2, 1, 1024).astype(np.float32)
    padded_bias_phases = np.random.randn(3, 1).astype(np.int32)
    bias_phases_batch = np.random.randn(3).astype(np.float32)
    bias_hid = np.random.randn(1, 3, 1024).astype(np.float32)
    bias_cell = np.random.randn(1, 3, 1024).astype(np.float32)
    return enc_out, enc_mask, tgt_seq, hid, cell, padded_bias_phases, bias_phases_batch, bias_hid, bias_cell

def to_ov_tensor(inputs):
    return tuple([ov.Tensor(input, list(input.shape), NUMPY_TYPE_TO_OV_TYPE[input.dtype.type]) for input in inputs])

encoder_path = "/app/model/asr/epoch-87_encoder.onnx"
decoder_path = "/app/model/asr/epoch-87_decoder.onnx"
ort_model = OnnxWrapper(encoder_path, decoder_path)
ov_model = OpenVINOStaticWrapper(encoder_path, decoder_path)

def ort_encode():
    input = construct_np_encode_input()
    start = time.time()
    for i in range(10):
        begin = time.time()
        res = ort_model.encode(*input)
        print(f"{i+1} iteration takes {time.time() - begin} s")
    print(f"ort encode avg : {(time.time() - start)/10} s")
    print(res)

def ort_decode():
    input = construct_np_decode_input()
    start = time.time()
    for i in range(10):
        begin = time.time()
        res = ort_model.decode(*input)
        print(f"{i+1} iteration takes {time.time() - begin} s")
    print(f"ort encode avg : {(time.time() - start)/10} s")
    print(res)

def ov_encode():
    input = to_ov_tensor(construct_np_encode_input())
    start = time.time()
    for i in range(10):
        begin = time.time()
        res = ov_model.encode(*input)
        print(f"{i+1} iteration takes {time.time() - begin} s")
    print(f"ov encode avg : {(time.time() - start)/10} s")
    print(res)

def ov_decode():
    input = to_ov_tensor(construct_np_decode_input())
    start = time.time()
    for i in range(10):
        begin = time.time()
        res = ov_model.decode(*input)
        print(f"{i+1} iteration takes {time.time() - begin} s")
    print(f"ov decode avg : {(time.time() - start)/10} s")
    print(res)

ort_encode()
ort_decode()
ov_encode()
ov_decode()
```

**Comment by yszhou2019** [comment]
Both `ort_encode()` and `ort_decode()` worked fine. The same with `ov_encode()`. Only `ov_decode()` met with this problem.

**Comment by mlukasze** [comment]
Hey @yszhou2019 
Sorry for inconvenience and thank you for letting us know.
We will check it and will back to you as soon as possible.

**Comment by yszhou2019** [comment]
You can leave your email in this issue and I will send you the randomized encoder/decoder.
