### ISSUE TITLE
RuntimeError: [ NETWORK_NOT_READ ] on CentOS 7.9

### ISSUE THREAD

**Issue by ma7555** [openvinotoolkit/openvino#13883]
I get this error after building on Centos 7.9 and installing the wheels in pip. The build finished successfully

```
[  0%] [cpplint] compile_tool_cpplint
[  0%] [cpplint] inference_engine_snippets_cpplint
[  0%] [cpplint] offline_transformations_cpplint
[  2%] Built target inference_engine_snippets_cpplint
[  2%] Built target compile_tool_cpplint
[  2%] [cpplint] inference_engine_legacy_obj_cpplint
[  3%] Built target offline_transformations_cpplint
[  8%] Built target inference_engine_legacy_obj_cpplint
[  8%] [cpplint] openvino_auto_plugin_cpplint
[  8%] [cpplint] openvino_gapi_preproc_obj_cpplint
[  9%] Built target openvino_auto_plugin_cpplint
[ 10%] Built target openvino_gapi_preproc_obj_cpplint
[ 10%] [cpplint] inference_engine_lp_transformations_cpplint
[ 15%] Built target inference_engine_lp_transformations_cpplint
[ 15%] Built target pugixml-static
[ 16%] Built target util
[ 16%] Built target ov_shape_inference
[ 16%] [cpplint] openvino_intel_cpu_plugin_cpplint
[ 28%] Built target openvino_intel_cpu_plugin_cpplint
[ 28%] Built target nlohmann_json_schema_validator
[ 28%] Built target frontend_common_obj
[ 28%] Built target ngraph_builders
[ 29%] Built target ov_protobuf_shutdown
[ 29%] Built target libprotobuf-lite
[ 29%] Built target openvino_gapi_preproc_obj
[ 29%] Built target ade
[ 29%] Built target format_reader
[ 29%] Built target gflags_nothreads_static
[ 30%] Built target cnpy
[ 34%] Built target libprotobuf
[ 34%] Built target opencv_c_wrapper
[ 35%] Built target ngraph_reference
[ 35%] Built target cpplint_all
[ 35%] Built target itt
[ 37%] Built target fluid
[ 38%] Built target ie_docs_snippets
[ 41%] Built target libprotoc
[ 43%] Built target inference_engine_obj
[ 43%] Built target protoc
[ 51%] Built target dnnl_cpu_x64
[ 52%] Built target dnnl_common
[ 54%] Built target inference_engine_lp_transformations_obj
[ 54%] Built target gen_onnx_proto
[ 58%] Built target dnnl_cpu
[ 58%] Built target gen_onnx_data_proto
[ 58%] Built target gen_onnx_operators_proto
[ 68%] Built target ngraph_obj
[ 68%] Built target dnnl
[ 69%] Built target onnx_proto
[ 70%] Built target onnx
[ 75%] Built target inference_engine_transformations_obj
[ 75%] Built target openvino
[ 75%] Built target onnx_common
[ 75%] Built target openvino_ir_frontend
[ 75%] Built target openvino_gapi_preproc
[ 75%] Built target offline_transformations
[ 75%] Built target openvino_c
[ 75%] Built target inference_engine_snippets
[ 76%] Built target _pyngraph
[ 76%] Built target constants
[ 78%] Built target interpreter_backend
[ 78%] Built target hello_nv12_input_classification_c
[ 78%] Built target ie_samples_utils
[ 78%] Built target hello_classification_c
[ 78%] Built target openvino_template_extension
[ 78%] Built target ov_integration_snippet_c
[ 78%] Built target ov_integration_snippet
[ 80%] Built target pyopenvino
[ 80%] Built target compile_tool
[ 80%] Built target benchmark_app_legacy
[ 83%] Built target openvino_paddle_frontend
[ 83%] Built target ie_api
[ 83%] Built target benchmark_app
[ 83%] Built target classification_sample_async
[ 84%] Built target hello_classification
[ 84%] Built target hello_nv12_input_classification
[ 84%] Built target hello_query_device
[ 84%] Built target hello_reshape_ssd
[ 84%] Built target model_creation_sample
[ 84%] Built target speech_sample
[ 84%] Built target ie_samples
[ 84%] Built target py_paddle_frontend
[ 89%] Built target openvino_tensorflow_frontend
[ 89%] Built target py_tensorflow_frontend
[ 93%] Built target openvino_onnx_frontend
[ 93%] Built target ov_frontends
[ 93%] Built target py_onnx_frontend
[ 93%] Built target openvino_auto_batch_plugin
[ 93%] Built target template_extension
[ 93%] Built target openvino_hetero_plugin
[ 93%] Built target py_ov_frontends
[ 93%] Built target openvino_auto_plugin
[ 94%] Built target openvino_template_plugin
[100%] Built target openvino_intel_cpu_plugin
[100%] Built target ov_plugins
[100%] Run 'fdupes' checks for wheel openvino-2022.3.0-8537-cp39-cp39-manylinux_2_17_x86_64.whl
[100%] Built target ie_wheel
[100%] Built target openvino_dev_wheel
```
CMAKE config:
```
cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_PYTHON=ON -DENABLE_WHEEL=ON \
-DCMAKE_INSTALL_PREFIX=../$installDir -DENABLE_SYSTEM_TBB=OFF -DENABLE_OPENCV=OFF \
-DENABLE_INTEL_GNA=OFF -DENABLE_INTEL_MYRIAD_COMMON=OFF -DTREAT_WARNING_AS_ERROR=OFF \
-DPYTHON_EXECUTABLE=$pathDPYTHON_EXECUTABLE \
-DPYTHON_LIBRARY=$pathDPYTHON_LIBRARY \
-DPYTHON_INCLUDE_DIR=$pathDPYTHON_INCLUDE_DIR  \
-DENABLE_INTEL_GPU=OFF \
-DCMAKE_C_FLAGS="-pthread" -DCMAKE_CXX_FLAGS="-pthread" \
..
```

But upon loading models:
```
RuntimeError: [ NETWORK_NOT_READ ] Unable to read the model: model/saved_model.xml Please check that model format: xml is supported and the model is correct. Available frontends: 
```

The mentioned model is loaded successfully in other systems without any problem and the xml seems fine.

I have installed both wheels openvino and openvino-dev and I can run commands like `mo` and `benchmark_app`.  I have used the same building steps on other systems and they work correctly.
How can I debug this issue?

**Comment by brmarkus** [comment]
Can you provide more information about your environment, please?
Which OpenVINO version have you installed?

Which model do you use and where have you got it from? Do you use a model from OpenVINO/Open-Model-Zoo? Do you use an IR-format or an ONNX-format?

What does the test look like where you get the mentioned error, can you share a command line?

A case where the error message can be seen is, when the model's IR-version is not supported by OpenVINO (like when the installed version supports IR-version v10 but the model is in an older or newer version, like you have OpenVINO 2021 on one machine, downloaded the model from Open-Model-Zoo and then copy the model-files to another machine where OpenVINO v2022 is installed).

**Comment by ilya-lavrenov** [comment]
Hi @ma7555,

Please, check that `openvino-2022.3.0-8537-cp39-cp39-manylinux_2_17_x86_64.whl` actually contains frontend libraries:
```sh
wheel unpack openvino-2022.3.0-8537-cp39-cp39-manylinux_2_17_x86_64.whl
cd openvino-2022.3.0/openvino/libs
```
If they are here, please, try run your application with `strace` and check at which locations `openvino_frontend_**.so.2022.3.0` files are searched by OpenVINO. It can be a key to resolve the issue.

**Comment by ma7555** [comment]
@brmarkus , 
I pulled from master, v2022.3.0, the model is an optimized model from tf "SavedModel" format. I ran the model optimizer `mo` on it using so i think it is IR format. The model optimizer was ran on a Windows 11 maching after installing openvino through PyPI
```
"mo --saved_model_dir {saved_model_path} --output_dir {output_path}"
```
The saved model works well on the windows machine and on other Linux machines but not this one

I use this class as a wrapper for compatibiltiy and drop in replacement with old TF model.

```
class OptimizedModel:
    def __init__(self, path):
        import openvino.runtime as ov

        self.core = ov.Core()
        self.model = self.core.compile_model(
            model=self.core.read_model(model=path),
            device_name="CPU",
        )

    def __call__(self, img) -> tf.Tensor:
        out = self.model([img])[self.model.output(0)]
        out = tf.convert_to_tensor(out, dtype=tf.float32)
        return out
```
The exception is raised with `read_model` function.
```
ov_model = OptimizedModel(path_to_xml)
```

@ilya-lavrenov I am currently rebuilding OpenVINO. Once finished I will try your solution and let you know in the next comment.

**Comment by ma7555** [comment]
@ilya-lavrenov 

files under `libs` after unpacking the wheel:
```
libhwloc.so.5                     libopenvino_intel_cpu_plugin.so      libtbbbind.so            libtbbmalloc.so.2    plugins.xml
libopenvino_auto_batch_plugin.so  libopenvino_ir_frontend.so.2230      libtbbbind.so.2          libtbb_preview.so
libopenvino_auto_plugin.so        libopenvino_onnx_frontend.so.2230    libtbbmalloc_proxy.so    libtbb_preview.so.2
libopenvino_gapi_preproc.so       libopenvino_paddle_frontend.so.2230  libtbbmalloc_proxy.so.2  libtbb.so
libopenvino_hetero_plugin.so      libopenvino.so.2230                  libtbbmalloc.so          libtbb.so.2
```
I will try with strace

**Comment by ma7555** [comment]
strace_output attached
[strace_output.txt](https://github.com/openvinotoolkit/openvino/files/9952904/strace_output.txt)

**Comment by ilya-lavrenov** [comment]
From the strace logs I don't see that frontends are tried to be loaded. Could you please provide a small repro? I will try to load it locally and compare strace logs.

**Comment by ma7555** [comment]
I tried to recompile with GCC 9
As always build is successfull however, loading a model from the zoo for testing I receive the below error:
```
model=resnet-50-pytorch
omz_downloader --name $model -o ~/ov_models/
omz_converter --name $model -o ~/ov_models/ -d ~/ov_models/
```
```
################|| Downloading resnet-50-pytorch ||################

========== Downloading /home/centos/ov_models/public/resnet-50-pytorch/resnet50-19c8e357.pth
... 100%, 100100 KB, 10850 KB/s, 9 seconds passed

========== Converting resnet-50-pytorch to ONNX
Conversion to ONNX command: /home/centos/mambaforge/envs/py39/bin/python3.9 -- /home/centos/mambaforge/envs/py39/lib/python3.9/site-packages/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py --model-name=resnet50 --weights=/home/centos/ov_models/public/resnet-50-pytorch/resnet50-19c8e357.pth --import-module=torchvision.models --input-shape=1,3,224,224 --output-file=/home/centos/ov_models/public/resnet-50-pytorch/resnet-v1-50.onnx --input-names=data --output-names=prob

ONNX check passed successfully.

========== Converting resnet-50-pytorch to IR (FP16)
Conversion command: /home/centos/mambaforge/envs/py39/bin/python3.9 -- /home/centos/mambaforge/envs/py39/bin/mo --framework=onnx --data_type=FP16 --output_dir=/home/centos/ov_models/public/resnet-50-pytorch/FP16 --model_name=resnet-50-pytorch --input=data '--mean_values=data[123.675,116.28,103.53]' '--scale_values=data[58.395,57.12,57.375]' --reverse_input_channels --output=prob --input_model=/home/centos/ov_models/public/resnet-50-pytorch/resnet-v1-50.onnx '--layout=data(NCHW)' '--input_shape=[1, 3, 224, 224]'

[ WARNING ]  Changing Const node '6539_input_port_1/value65418235' data type from int64 to float32 for Add operation
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Check 'false' failed at frontends/common/src/manager.cpp:73:
FrontEnd API failed with InitializationFailure: :
FrontEnd for Framework ir is not found

[ ERROR ]  Traceback (most recent call last):
  File "/home/centos/mambaforge/envs/py39/lib/python3.9/site-packages/openvino/tools/mo/main.py", line 44, in main
    ngraph_function = convert(**argv)
  File "/home/centos/mambaforge/envs/py39/lib/python3.9/site-packages/openvino/tools/mo/convert.py", line 26, in convert
    return _convert(**args)
  File "/home/centos/mambaforge/envs/py39/lib/python3.9/site-packages/openvino/tools/mo/convert_impl.py", line 591, in _convert
    raise e
  File "/home/centos/mambaforge/envs/py39/lib/python3.9/site-packages/openvino/tools/mo/convert_impl.py", line 581, in _convert
    ngraph_function = driver(argv)
  File "/home/centos/mambaforge/envs/py39/lib/python3.9/site-packages/openvino/tools/mo/convert_impl.py", line 496, in driver
    res_ngraph_function = emit_ir(graph, argv)
  File "/home/centos/mambaforge/envs/py39/lib/python3.9/site-packages/openvino/tools/mo/convert_impl.py", line 453, in emit_ir
    func = read_model(orig_model_name + "_tmp.xml")
  File "/home/centos/mambaforge/envs/py39/lib/python3.9/site-packages/openvino/tools/mo/convert_impl.py", line 423, in read_model
    fe = fem.load_by_framework(framework="ir")
openvino._pyopenvino.InitializationFailure: Check 'false' failed at frontends/common/src/manager.cpp:73:
FrontEnd API failed with InitializationFailure: :
FrontEnd for Framework ir is not found


[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------
FAILED:
resnet-50-pytorch
```

**Comment by zulkifli-halim** [comment]
Hi @ma7555, I'm using this [guide ](https://github.com/openvinotoolkit/openvino/wiki/Building-OpenVINO-on-CentOS-7-Guide) to build OpenVINO on CentOs 7.9 and it works for me:
```
[ SUCCESS ] Generated IR version 11 model.
[ SUCCESS ] XML file: /home/pse/Downloads/github/ov_models/public/resnet-50-pytorch/FP32/resnet-50-pytorch.xml
[ SUCCESS ] BIN file: /home/pse/Downloads/github/ov_models/public/resnet-50-pytorch/FP32/resnet-50-pytorch.bin
[ SUCCESS ] Total execution time: 1.48 seconds.
[ SUCCESS ] Memory consumed: 269 MB.
[ INFO ] The model was converted to IR v11, the latest model format that corresponds to the source DL framework input/output format. While IR v11 is backwards compatible with OpenVINO Inference Engine API v1.0, please use API v2.0 (as of 2022.1) to take advantage of the latest improvements in IR v11.
Find more information about API v2.0 and IR v11 at https://docs.openvino.ai
```
I also tested the model with benchmar_app:
```
[Step 3/11] Setting device configuration
[ WARNING ] -nstreams default value is determined automatically for CPU device. Although the automatic selection usually provides a reasonable performance, but it still may be non-optimal for some cases, for more information look at README.
[Step 4/11] Reading network files
[ INFO ] Read model took 58.20 ms
[Step 5/11] Resizing network to match image sizes and given batch
[ INFO ] Network batch size: 1
[Step 6/11] Configuring input of the model
[ INFO ] Model input 'data' precision u8, dimensions ([N,C,H,W]): 1 3 224 224
[ INFO ] Model output 'prob' precision f32, dimensions ([...]): 1 1000
[Step 7/11] Loading the model to the device
[ INFO ] Compile model took 541.38 ms
[Step 8/11] Querying optimal runtime parameters
[ INFO ] DEVICE: CPU
[ INFO ]   AVAILABLE_DEVICES  , ['']
[ INFO ]   RANGE_FOR_ASYNC_INFER_REQUESTS  , (1, 1, 1)
[ INFO ]   RANGE_FOR_STREAMS  , (1, 2)
[ INFO ]   FULL_DEVICE_NAME  , Intel(R) Celeron(R) J4025 CPU @ 2.00GHz
[ INFO ]   OPTIMIZATION_CAPABILITIES  , ['FP32', 'FP16', 'INT8', 'BIN', 'EXPORT_IMPORT']
[ INFO ]   CACHE_DIR  ,
[ INFO ]   NUM_STREAMS  , 1
[ INFO ]   AFFINITY  , Affinity.CORE
[ INFO ]   INFERENCE_NUM_THREADS  , 0
[ INFO ]   PERF_COUNT  , False
[ INFO ]   INFERENCE_PRECISION_HINT  , <Type: 'float32'>
[ INFO ]   PERFORMANCE_HINT  , PerformanceMode.THROUGHPUT
[ INFO ]   PERFORMANCE_HINT_NUM_REQUESTS  , 0
[Step 9/11] Creating infer requests and preparing input data
[ INFO ] Create 1 infer requests took 0.19 ms
[ WARNING ] No input files were given for input 'data'!. This input will be filled with random values!
[ INFO ] Fill input 'data' with random values
[Step 10/11] Measuring performance (Start inference asynchronously, 1 inference requests using 1 streams for CPU, inference only: True, limits: 60000 ms duration)
[ INFO ] Benchmarking in inference only mode (inputs filling are not included in measurement loop).
[ INFO ] First inference took 329.59 ms
[Step 11/11] Dumping statistics report
Count:          188 iterations
Duration:       60624.55 ms
Latency:
    Median:     315.24 ms
    AVG:        322.36 ms
    MIN:        314.32 ms
    MAX:        464.06 ms
Throughput: 3.10 FPS
```

May I know the detail of the system you used? Also, please share with me the command you used to pull the v2022.3.0 branch.

**Comment by ma7555** [comment]
```
CentOS Linux release 7.9.2009 (Core)
```
```
  Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
  CPE OS Name: cpe:/o:centos:centos:7
  Kernel: Linux 3.10.0-1160.76.1.el7.x86_64
  Architecture: x86-64
```
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             4
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 60
Model name:            Intel Core Processor (Haswell, no TSX)
Stepping:              1
CPU MHz:               1999.991
BogoMIPS:              3999.98
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
L3 cache:              16384K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl xtopology eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat
```

OpenVINO is added as a submodule in the project and then cloning is run with

```
  git submodule update --init --recursive
```

Building with this script:
https://gist.github.com/ma7555/c93b9e9d89d1e745f591ccd5b86805dc

As I noted, I installed with the same script successfully on other systems running CentOS 7.9. The problem happens on 1 of 3 machines and I can not find out where is the problem.

Do you mind sharing the wheels you used with the python version used during the compile?

**Comment by zulkifli-halim** [comment]
Hi @ma7555. Here is my [wheel package](https://drive.google.com/file/d/1DQawn3UUR-_JBl1qwe74tUZFJDQnKLoX/view?usp=share_link) and I'm using Python 3.7.

**Comment by ma7555** [comment]
I couldn't install the wheel on my Centos 7.9 system. Any more things to try?

**Comment by ma7555** [comment]
a small reproducible code

```
import numpy as np
import openvino.runtime as ov


class OptimizedModel:
    def __init__(self, path):

        self.core = ov.Core()
        self.model = self.core.compile_model(
            model=self.core.read_model(model=path),
            device_name="CPU",
        )

    def __call__(self, img):
        out = self.model([img])[self.model.output(0)]
        return out


if __name__ == "__main__":
    model = OptimizedModel(path_to_xml)
    ifer = model(np.zeros((1, 224, 224, 3)))
```
[strace.log](https://github.com/openvinotoolkit/openvino/files/9998103/strace.log)

**Comment by zulkifli-halim** [comment]
Hi @ma7555, can you share with us the characteristics of the CPUs of your systems?

**Comment by zulkifli-halim** [comment]
Hi @ma7555, It seems like you are using an old CPU (Haswell), OpenVINO supports CPUs from 6th to 13th generation. You can refer to [system requirements](https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/system-requirements.html) for more info.

**Comment by ma7555** [comment]
> Hi @ma7555, It seems like you are using an old CPU (Haswell), OpenVINO supports CPUs from 6th to 13th generation. You can refer to [system requirements](https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/system-requirements.html) for more info.

[centos@jsc-avl-imp01 face_match]$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             4
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 60
Model name:            Intel Core Processor (Haswell, no TSX)
Stepping:              1
CPU MHz:               1999.991
BogoMIPS:              3999.98
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
L3 cache:              16384K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl xtopology eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat

**Comment by ma7555** [comment]
@ilya-lavrenov 
> > Can those lines be the problem?
> 
> No, someone from our team has faced this issue as well, but when we tries to reproduce it, we could not reproduce the issue with latest master. But the original issue is that OpenVINO cannot load `libopenvino_ir_frontend.so.2230` from some reason. And strace logs show that OpenVINO does not even try to do it in your case..

Was you able to solve it? Could it be that the processor is old (Haswell) as @zulkifli-halim says?

**Comment by ilya-lavrenov** [comment]
> @ilya-lavrenov
> 
> > > Can those lines be the problem?
> > 
> > 
> > No, someone from our team has faced this issue as well, but when we tries to reproduce it, we could not reproduce the issue with latest master. But the original issue is that OpenVINO cannot load `libopenvino_ir_frontend.so.2230` from some reason. And strace logs show that OpenVINO does not even try to do it in your case..
> 
> Was you able to solve it? Could it be that the processor is old (Haswell) as @zulkifli-halim says?

It's not related to processor definitely. It can be OS specific, but it's hard to believe in it. Currently, we have validation on CentOS 7 and all tests passed.

**Comment by hbalasu1** [comment]
Hi @ma7555 

OpenVINO 2022.3 is yet to be an official release, but you can use this pip install command "pip install openvino --pre" on CentOS

Hope this information help

**Comment by ma7555** [comment]
> Hi @ma7555
> 
> OpenVINO 2022.3 is yet to be an official release, but you can use this pip install command "pip install openvino --pre" on CentOS
> 
> Hope this information help

Yeah, it does help. `pip install openvino --pre` works. I suggest adding it to the Docs. Could have saved me a few weeks.

**Comment by ilya-lavrenov** [comment]
> > Hi @ma7555
> > OpenVINO 2022.3 is yet to be an official release, but you can use this pip install command "pip install openvino --pre" on CentOS
> > Hope this information help
> 
> Yeah, it does help. `pip install openvino --pre` works. I suggest adding it to the Docs. Could have saved me a few weeks.

Once 2022.3 is released, CentOS will be supported our of box and users don't have to pass `--pre` option.
In 2022.2 minimal supported OS is Ubuntu 18.04 with glibc version 2.27, in 2022.3 we support all Linux OSes with glibc 2.17 which implies CentOS 7 as well.
