### ISSUE TITLE
Error Running ./demo_squeezenet_download_convert_run.sh

### ISSUE THREAD

**Issue by alfawzaan** [openvinotoolkit/openvino#1388]
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  cannot import name '_message' from 'google.protobuf.pyext' (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/google/protobuf/pyext/__init__.py)
[ ERROR ]  Traceback (most recent call last):
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/main.py", line 312, in main
    ret_code = driver(argv)
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/main.py", line 273, in driver
    ret_res = emit_ir(prepare_ir(argv), argv)
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/main.py", line 228, in prepare_ir
    import_extensions.load_dirs(argv.framework, extensions, get_front_classes)
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/utils/import_extensions.py", line 104, in load_dirs
    load_dir(framework, path, get_front_classes)
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/utils/import_extensions.py", line 89, in load_dir
    import_by_path(os.path.join(path, *p), [ext, *p])
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/utils/import_extensions.py", line 33, in import_by_path
    importlib.import_module('{}.{}'.format('.'.join(middle_names), name))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/front/caffe/loader.py", line 24, in <module>
    from google.protobuf import text_format
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/google/protobuf/text_format.py", line 54, in <module>
    from google.protobuf.internal import type_checkers
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/google/protobuf/internal/type_checkers.py", line 55, in <module>
    from google.protobuf.internal import decoder
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/google/protobuf/internal/decoder.py", line 90, in <module>
    from google.protobuf.internal import encoder
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/google/protobuf/internal/encoder.py", line 73, in <module>
    from google.protobuf.internal import wire_format
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/google/protobuf/internal/wire_format.py", line 36, in <module>
    from google.protobuf import descriptor
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: cannot import name '_message' from 'google.protobuf.pyext' (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/google/protobuf/pyext/__init__.py)

[ ERROR ]  ---------------- END OF BUG REPORT --------------

**Comment by ilya-lavrenov** [comment]
@alfawzaan have you installed requirements.txt of Model Optimizer?

**Comment by alfawzaan** [comment]
Yes, I have installed it. The demo sample is working. But this error still persists.

**Comment by maxlytkin** [comment]
@alfawzaan 
Please try workaround methods from the following thread https://github.com/tensorflow/tensorboard/issues/1566

**Comment by alfawzaan** [comment]
Okay thanks.
