### ISSUE TITLE
RuntimeError: Failed to allocate graph: MYRIAD device is not opened.

### ISSUE THREAD

**Issue by mzwtjp** [openvinotoolkit/openvino#14128]
I am trying to use NCS2(MYRIAD) device with benchmark_app on Jetson Nano.
I have built OpenVINO libraries and benchmark app using the 2022/2 branch, however I am seeing the following error.

For -d CPU (contrib's arm_plugun), I do not see error and benchmark_app finishes successfully.
So I expected with -d MYRIAD it also suceeeds, but it looks like I am seeing devvice open related error.

I am new to OpenVINO / MYRIAD, so still not figured out what is wrong with my build or operation.
If you have any suggestion or hint (e.g. what might be causing this error, etc.) I really appreciate.

I am running this within docker container where I have built OpenVINO.

command line:

> benchmark_app -d MYRIAD -m ./intel/vehicle-detection-0200/FP16/vehicle-detection-0200.xml

log:

> [Step 1/11] Parsing and validating input arguments
> [ WARNING ]  -nstreams default value is determined automatically for a device. Although the automatic selection usually provides a reasonable performance, but it still may be non-optimal for some cases, for more information look at README.
> [Step 2/11] Loading OpenVINO
> [ WARNING ] PerformanceMode was not explicitly specified in command line. Device MYRIAD performance hint will be set to THROUGHPUT.
> [ INFO ] OpenVINO:
>          API version............. 2022.2.0-000-4da2c945d6c-releases/2022/2
> [ INFO ] Device info
>          MYRIAD
>          openvino_intel_myriad_plugin version 2022.2
>          Build................... 2022.2.0-000-4da2c945d6c-releases/2022/2
> 
> [Step 3/11] Setting device configuration
> [ WARNING ] -nstreams default value is determined automatically for MYRIAD device. Although the automatic selection usually provides a reasonable performance, but it still may be non-optimal for some cases, for more information look at README.
> [Step 4/11] Reading network files
> [ INFO ] Read model took 101.10 ms
> [Step 5/11] Resizing network to match image sizes and given batch
> [ INFO ] Network batch size: 1
> [Step 6/11] Configuring input of the model
> [ INFO ] Model input 'image' precision u8, dimensions ([N,C,H,W]): 1 3 256 256
> [ INFO ] Model output 'detection_out' precision f32, dimensions ([...]): 1 1 200 7
> [Step 7/11] Loading the model to the device
> I: [ncAPI] [    353313] [benchmark_app] ncDeviceOpen:926 ncDeviceOpen() XLinkBootRemote is running for 1.2.4.2-ma2480...
> 
> W: [ncTool] [    353331] [benchmark_app] patchSetMemTypeCommand:205 Fail to find call command
> W: [ncTool] [    353331] [benchmark_app] bootDevice:233 Fail to patch "Set memory type" command for firmware sc = -2
> I: [ncAPI] [    353513] [benchmark_app] ncDeviceOpen:945 ncDeviceOpen() XLinkBootRemote returned success X_LINK_SUCCESS for 1.2.4.2-ma2480
> E: [ncAPI] [    368513] [benchmark_app] ncDeviceOpen:1013 Failed to find booted device after boot
> W: [ncAPI] [    368513] [benchmark_app] ncDeviceOpen:1016 Device (1.2.4.2-ma2480) doesn't disappear after firmware loading
> I: [ncAPI] [    368513] [benchmark_app] destroyDeviceHandle:1651 Destroying device handler
> I: [ncAPI] [    368513] [benchmark_app] ncDeviceClose:1685 Handle already destroyed
> [ ERROR ] Failed to allocate graph: MYRIAD device is not opened.
> Traceback (most recent call last):
>   File "/home/user1/.local/lib/python3.6/site-packages/openvino/tools/benchmark/main.py", line 297, in run
>     compiled_model = benchmark.core.compile_model(model, benchmark.device)
>   File "/home/user1/.local/lib/python3.6/site-packages/openvino/runtime/ie_api.py", line 387, in compile_model
>     super().compile_model(model, device_name, {} if config is None else config),
> RuntimeError: Failed to allocate graph: MYRIAD device is not opened.
> I: [watchdog] [    368522] [benchmark_app] ~WatchdogImpl:125 watchdog terminated
>

**Comment by mzwtjp** [comment]
following seems to worked:

> docker run -v /dev:/dev
(then within docker container)
> sudo LD_LIBRARY_PATH=${LD_LIBRARY_PATH} benchmark_app

Perhaps related to /dev usb device permission issue?
