### ISSUE TITLE
[Bug] Split node Dimension of data input shape along 'axis': 1172 must be evenly divisible by 'num_splits' attribute value: 60

### ISSUE THREAD

**Issue by zhaohb** [openvinotoolkit/openvino#14718]
##### System information (version)

- OpenVINO => 2022.1
- Operating System / Platform =>linux
- Problem classification: Model convert
- Framework: onnx 2 OpenVINO
- Model name: Recommendation model

##### Detailed description

this is my onnx model, and that split op is not divide equally，but when doing model conversions it is treated as an even split and should be converted to a variadicsplit op，how to fix it？thank you very much！
<img width="880" alt="image" src="https://user-images.githubusercontent.com/5791375/208334239-1908a274-45e4-4719-a0af-77e324ab72ee.png">

that is mo output log：
```shell
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  While validating ONNX node '<Node(Split): StatefulPartitionedCall/model_wrapper/model/tf.split/split>':
Check 'dimension_at_axis % num_splits == 0' failed at src/core/shape_inference/include/split_shape_inference.hpp:60:
While validating node 'v1::Split Split_1953 (StatefulPartitionedCall/model_wrapper/model/UnifiedDynamicEmbedding/Reshape[0]:f32[256,1172,49], Constant_1952[0]:i64[]) -> (dynamic[...])' with friendly_name 'Split_1953':
Dimension of data input shape along 'axis': 1172 must be evenly divisible by 'num_splits' attribute value: 60

[ ERROR ]  Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/openvino/tools/mo/main.py", line 50, in main
    ngraph_function = convert_model(**argv)
  File "/usr/local/lib/python3.8/dist-packages/openvino/tools/mo/convert.py", line 47, in convert_model
    return _convert(**args)
  File "/usr/local/lib/python3.8/dist-packages/openvino/tools/mo/convert_impl.py", line 937, in _convert
    raise e.with_traceback(None)
RuntimeError: While validating ONNX node '<Node(Split): StatefulPartitionedCall/model_wrapper/model/tf.split/split>':
Check 'dimension_at_axis % num_splits == 0' failed at src/core/shape_inference/include/split_shape_inference.hpp:60:
While validating node 'v1::Split Split_1953 (StatefulPartitionedCall/model_wrapper/model/UnifiedDynamicEmbedding/Reshape[0]:f32[256,1172,49], Constant_1952[0]:i64[]) -> (dynamic[...])' with friendly_name 'Split_1953':
Dimension of data input shape along 'axis': 1172 must be evenly divisible by 'num_splits' attribute value: 60


[ ERROR ]  ---------------- END OF BUG REPORT --------------
```

I also test 2022.2 202.3, but had same error!

**Comment by andrei-kochin** [comment]
@zhaohb do you have a link to your or reference model so we can try it locally?

**Comment by zhaohb** [comment]
@andrei-kochin Thank you very much for your reply. The following code can generate an onnx model called signal_split.onnx, and then use the following mo command to reproduce it: mo --input_model signal_split.onnx --model_name signal_split

**Comment by zhaohb** [comment]
@andrei-kochin  Thank you very much for your reply.
The following code can generate an onnx model called signal_split.onnx:
```python
import numpy as np
import onnx
from onnx import helper
from onnx import AttributeProto, TensorProto, GraphProto

node_input = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0]).astype(np.float32)
split = np.array([3, 4]).astype(np.int32)

input_1 = helper.make_tensor_value_info('input_1', TensorProto.FLOAT, [7])
#split = helper.make_tensor_value_info('split', TensorProto.INT32, [2])

output_1 = helper.make_tensor_value_info('output_1', TensorProto.FLOAT, [3])
output_2 = helper.make_tensor_value_info('output_2', TensorProto.FLOAT, [4])
node_def = onnx.helper.make_node(
    "Split",
    inputs=["input_1"],
    outputs=["output_1", "output_2"],
    axis=0,
    split=[3,4],
)
graph_def = helper.make_graph(
    [node_def],
    'test-model',
    [input_1],
    [output_1, output_2],
)

# Create the model (ModelProto)
model_def = helper.make_model(graph_def, producer_name='onnx-example')

print('The model is:\n{}'.format(model_def))
#onnx.checker.check_model(model_def)
print('The model is checked!')
onnx.save(model_def, "signal_split.onnx")
```
then use the following mo command to reproduce it: mo --input_model signal_split.onnx --model_name signal_split

**Comment by andrei-kochin** [comment]
@mlukasze could you please ask someone to check?

**Comment by zhaohb** [comment]
@andrei-kochin @mlukasze can you repeat the question? how to fix it?

**Comment by tomdol** [comment]
Can you please try changing your code so that the model is created like this?

`model_def = helper.make_model(graph_def, producer_name='onnx-example', opset_imports=[helper.make_opsetid("", 11)])`

You've passed the splits as an attribute and this is only valid in older versions of this operator. Without this modification your script creates a model using the largest opset available and it's probably 13 (or higher).

**Comment by zhaohb** [comment]
@tomdol I passed the splits as an attribute because splits is an attribute  in openvino ops/split.py, and there's no way to convert if I don't set it as an attribute.
Yes, now I'm using opset 13, and I think this is an openvino bug, It is not the opset version that is causing the problem.

**Comment by tomdol** [comment]
I've tested it myself and I have different results. If you change your code according to my suggestion you will get a correct model which fulfills the requirements of the opset-11 version of the Split operator https://github.com/onnx/onnx/blob/main/docs/Changelog.md#Split-11 - this version expects the splits to be passed in as an attribute and this is what you do in your code snippet. This way you end up with a model where the Split operation takes a single input:
![image](https://user-images.githubusercontent.com/22572387/209119511-d4a408c2-64cf-4e96-a6a1-ece836585375.png)
When you save a model without the suggested changes you still get a similarly looking graph but this time it's incorrect from the standard perspective - since ONNX opset 13 the Split operation expects the splits to be passed in as an input https://github.com/onnx/onnx/blob/main/docs/Changelog.md#Split-13. OV can correctly handle both versions depending on the opset number detected in the model https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/op/split.cpp. I was able to create and import both versions locally so I don't see a bug here.

**Comment by tomdol** [comment]
There's one more thing you can do to verify your ONNX model. You can run the model checker with an extra argument to perform a full check:
![image](https://user-images.githubusercontent.com/22572387/209122026-e3a2b7a7-7ffb-427a-8215-b91fd4cf3407.png)

**Comment by zhaohb** [comment]
@tomdol thank you very much, I understood,  the split version that openvino supports is too low,  I'll try again with opset 11

**Comment by zhaohb** [comment]
@tomdol From https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/op/split.cpp should also can support opset13, So I get the signal_split_13.onnx model with the following code, opset version 13, and then I use two different model transformations but get different results:
```python
import numpy as np
import onnx
from onnx import helper
from onnx import AttributeProto, TensorProto, GraphProto

node_input = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0]).astype(np.float32)
split = np.array([3, 4]).astype(np.int32)

initializers= []

input_1 = helper.make_tensor_value_info('input_1', TensorProto.FLOAT, [7])
#split = helper.make_tensor_value_info('split', TensorProto.INT32, [2])
initializers  = [onnx.helper.make_tensor(
        name='split',
        data_type=TensorProto.INT32,
        dims=[2],
        vals=split.flatten().tolist())]

output_1 = helper.make_tensor_value_info('output_1', TensorProto.FLOAT, [3])
output_2 = helper.make_tensor_value_info('output_2', TensorProto.FLOAT, [4])

attr = helper.make_attribute("", 1.)

node_def = onnx.helper.make_node(
    "Split",
    inputs=["input_1", 'split'],
    outputs=["output_1", "output_2"],
    axis=np.int32(0),
#    split=np.array([3,4], dtype=np.int32),
)
graph_def = helper.make_graph(
    [node_def],
    'test-model',
    [input_1],
    [output_1, output_2],
    initializer=initializers,
)

# Create the model (ModelProto)
model_def = helper.make_model(graph_def, producer_name='onnx-example',opset_imports=[helper.make_opsetid("", 13)])
import pdb
#pdb.set_trace()
#model_def = helper.make_model(graph_def, producer_name='onnx-example')

print('The model is:\n{}'.format(model_def))
onnx.checker.check_model(model_def)
print('The model is checked!')
onnx.save(model_def, "signal_split_13.onnx")
```
first command：
```shell
#mo --input_model signal_split_13.onnx --model_name signal_split_13  --extension /usr/local/lib/python3.8/dist-packages/openvino/tools/mo/

Model Optimizer arguments:
Common parameters:
	- Path to the Input Model:   signal_split_13.onnx
	- Path for generated IR: 	.
	- IR output name: 	signal_split_13
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	Not specified, inherited from the model
	- Source layout: 	Not specified
	- Target layout: 	Not specified
	- Layout: 	Not specified
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP32
	- Enable fusing: 	True
	- User transformations: 	Not specified
	- Reverse input channels: 	False
	- Enable IR generation for fixed input shape: 	False
	- Use the transformations config file: 	None
Advanced parameters:
	- Force the usage of legacy Frontend of Model Optimizer for model conversion into IR: 	False
	- Force the usage of new Frontend of Model Optimizer for model conversion into IR: 	False
OpenVINO runtime found in: 	/opt/intel/openvino/python/python3.8/openvino
OpenVINO runtime version: 	2022.1.0-7019-cdb9bec7210-releases/2022/1
Model Optimizer version: 	2022.1.0-7019-cdb9bec7210-releases/2022/1
> /usr/local/lib/python3.8/dist-packages/openvino/tools/mo/front/onnx/split_ext.py(23)extract()
-> if size_splits is None:
(Pdb) c
[ ERROR ]  Cannot infer shapes or values for node "output_15/Split".
[ ERROR ]  Input shape is not evenly divided by `num_splits` of Split node output_15/Split. `input_shape`=[7], `axis`=0, `num_splits`=2
[ ERROR ]
[ ERROR ]  It can happen due to bug in custom shape infer function <function SplitBase.infer at 0x7f76f020d1f0>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ ERROR ]  Run Model Optimizer with --log_level=DEBUG for more information.
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'openvino.tools.mo.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "output_15/Split" node.
 For more information please refer to Model Optimizer FAQ, question #38. (https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=38#question-38)
```

second command:
```shell
#mo --input_model signal_split_13.onnx --model_name signal_split_13

Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	signal_split_13.onnx
	- Path for generated IR: .
	- IR output name: 	signal_split_13
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	Not specified, inherited from the model
	- Source layout: 	Not specified
	- Target layout: 	Not specified
	- Layout: 	Not specified
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP32
	- Enable fusing: 	True
	- User transformations: 	Not specified
	- Reverse input channels: 	False
	- Enable IR generation for fixed input shape: 	False
	- Use the transformations config file: 	None
Advanced parameters:
	- Force the usage of legacy Frontend of Model Optimizer for model conversion into IR: 	False
	- Force the usage of new Frontend of Model Optimizer for model conversion into IR: 	False
OpenVINO runtime found in: 	/opt/intel/openvino/python/python3.8/openvino
OpenVINO runtime version: 	2022.1.0-7019-cdb9bec7210-releases/2022/1
Model Optimizer version: 	2022.1.0-7019-cdb9bec7210-releases/2022/1
[ SUCCESS ] Generated IR version 11 model.
[ SUCCESS ] XML file: /data/zhaohb/subgraph/tfra/tfra_xiongxiong/models/get_split_model/signal_split_13.xml
[ SUCCESS ] BIN file: /data/zhaohb/subgraph/tfra/tfra_xiongxiong/models/get_split_model/signal_split_13.bin
[ SUCCESS ] Total execution time: 0.47 seconds.
[ SUCCESS ] Memory consumed: 138 MB.
It's been a while, check for a new version of Intel(R) Distribution of OpenVINO(TM) toolkit here https://software.intel.com/content/www/us/en/develop/tools/openvino-toolkit/download.html?cid=other&source=prod&campid=ww_2022_bu_IOTG_OpenVINO-2022-1&content=upg_all&medium=organic or on the GitHub*
[ INFO ] The model was converted to IR v11, the latest model format that corresponds to the source DL framework input/output format. While IR v11 is backwards compatible with OpenVINO Inference Engine API v1.0, please use API v2.0 (as of 2022.1) to take advantage of the latest improvements in IR v11.
Find more information about API v2.0 and IR v11 at https://docs.openvino.ai
```

I have custom op and front logic in my business model, so I have to add --extension.
What will be the impact of '--extension' ? I know --extension can use a custom operator library directly

**Comment by mbencer** [comment]
@zhaohb Passing path to the folder is old method of defining extensions (like `--extension /usr/local/lib/python3.8/dist-packages/openvino/tools/mo/` is your case). Since `22.1` release we've introduced new path (C++ ONNX Frontend) of ModelOptimizer conversion. If you are using extensions in such a way, conversion fallbacks to the old path (which is not widely developing now) – the exception is thrown there.
I recommend using the new format of MO extensions - passing path to *.dll/*.so library.
The instruction how to implement it can be found in https://docs.openvino.ai/latest/openvino_docs_Extensibility_UG_Intro.html#create-a-library-with-extensions

**Comment by mbencer** [comment]
@zhaohb Could you confirm if it works for you?

**Comment by zhaohb** [comment]
@mbencer Sorry it's late. yeah, it'll fix my problem, thank you very much.
