### ISSUE TITLE
[Bug] Benchmark_app crashes with IndexError: Accessing out-of-range dimension in Dimension[]

### ISSUE THREAD

**Issue by ilya-naumov** [openvinotoolkit/openvino#14852]
##### System information (version)
- OpenVINO=> 2022.3.0
- Operating System / Platform => Ubuntu 20.04
- Model name: vitstr-small-patch16-224
##### Detailed description
benchmark_app since OpenVINO 2022.3.0 crashes on model `vitstr-small-patch16-224` with the following exception:
```
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading OpenVINO Runtime
[ INFO ] OpenVINO:
[ INFO ] Build ................................. 2022.3.0-9052-9752fafe8eb-releases/2022/3
[ INFO ] 
[ INFO ] Device info:
[ INFO ] CPU
[ INFO ] Build ................................. 2022.3.0-9052-9752fafe8eb-releases/2022/3
[ INFO ] 
[ INFO ] 
[Step 3/11] Setting device configuration
[ WARNING ] Performance hint was not explicitly specified in command line. Device(CPU) performance hint will be set to THROUGHPUT.
[Step 4/11] Reading model files
[ INFO ] Loading model files
[ INFO ] Read model took 739.86 ms
[ INFO ] Original model I/O parameters:
[ INFO ] Model inputs:
[ INFO ]     image (node: image) : f32 / [N,C,H,W] / [1,1,224,224]
[ INFO ]     onnx::Unsqueeze_1 (node: onnx::Unsqueeze_1) : i64 / [...] / []
[ INFO ] Model outputs:
[ INFO ]     logits (node: logits) : f32 / [...] / [..1,..197,96]
[Step 5/11] Resizing model to match image sizes and given batch
[ ERROR ] Accessing out-of-range dimension in Dimension[]
Traceback (most recent call last):
  File "/mnt/c/repo/venv_2022.3/lib/python3.8/site-packages/openvino/tools/benchmark/main.py", line 384, in main
    app_inputs_info, reshape = get_inputs_info(args.shape, args.data_shape, args.layout, args.batch_size, args.input_scale, args.input_mean, model.inputs)
  File "/mnt/c/repo/venv_2022.3/lib/python3.8/site-packages/openvino/tools/benchmark/utils/utils.py", line 658, in get_inputs_info
    supposed_batch = info.partial_shape[0]
IndexError: Accessing out-of-range dimension in Dimension[]
```

Debugging showed that the crash is related to the input **onnx::Unsqueeze_1**. This input is missing in the model converted by the previous 2022.2 release.

##### Steps to reproduce
1. Install OpenVINO 2022.3.0
2. `omz_downloader --name vitstr-small-patch16-224`
3. `omz_converter --name vitstr-small-patch16-224 --precisions FP32`
4. `benchmark_app -m public/vitstr-small-patch16-224/FP32/vitstr-small-patch16-224.xml -i /mnt/share/datasets/ICDAR13 -b 1`

**Comment by zulkifli-halim** [comment]
HI @ilya-naumov, I'm able to run the benchmark_app with vitstr-small-patch16-224 model without any issue by removing the batch_size (-b) option:
`benchmark_app -m /home/vitstr-small-patch16-224/FP32/vitstr-small-patch16-224.xml`

```
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading OpenVINO Runtime
[ INFO ] OpenVINO:
[ INFO ] Build ................................. 2022.3.0-9052-9752fafe8eb-releases/2022/3
[ INFO ]
[ INFO ] Device info:
[ INFO ] CPU
[ INFO ] Build ................................. 2022.3.0-9052-9752fafe8eb-releases/2022/3
[ INFO ]
[ INFO ]
[Step 3/11] Setting device configuration
[ WARNING ] Performance hint was not explicitly specified in command line. Device(CPU) performance hint will be set to THROUGHPUT.
[Step 4/11] Reading model files
[ INFO ] Loading model files
[ INFO ] Read model took 185.36 ms
[ INFO ] Original model I/O parameters:
[ INFO ] Model inputs:
[ INFO ]     image (node: image) : f32 / [N,C,H,W] / [1,1,224,224]
[ INFO ]     onnx::Unsqueeze_1 (node: onnx::Unsqueeze_1) : i64 / [...] / []
[ INFO ] Model outputs:
[ INFO ]     logits (node: logits) : f32 / [...] / [..1,..197,96]
[Step 5/11] Resizing model to match image sizes and given batch
[ INFO ] Model batch size: 1
[Step 6/11] Configuring input of the model
[ INFO ] Model inputs:
[ INFO ]     image (node: image) : f32 / [N,C,H,W] / [1,1,224,224]
[ INFO ]     onnx::Unsqueeze_1 (node: onnx::Unsqueeze_1) : i64 / [...] / []
[ INFO ] Model outputs:
[ INFO ]     logits (node: logits) : f32 / [...] / [..1,..197,96]
[Step 7/11] Loading the model to the device
[ INFO ] Compile model took 771.60 ms
[Step 8/11] Querying optimal runtime parameters
[ INFO ] Model:
[ INFO ]   NETWORK_NAME: torch_jit
[ INFO ]   OPTIMAL_NUMBER_OF_INFER_REQUESTS: 4
[ INFO ]   NUM_STREAMS: 4
[ INFO ]   AFFINITY: Affinity.CORE
[ INFO ]   INFERENCE_NUM_THREADS: 4
[ INFO ]   PERF_COUNT: False
[ INFO ]   INFERENCE_PRECISION_HINT: <Type: 'float32'>
[ INFO ]   PERFORMANCE_HINT: PerformanceMode.THROUGHPUT
[ INFO ]   PERFORMANCE_HINT_NUM_REQUESTS: 0
[Step 9/11] Creating infer requests and preparing input tensors
[ WARNING ] No input files were given for input 'image'!. This input will be filled with random values!
[ WARNING ] No input files were given for input 'onnx::Unsqueeze_1'!. This input will be filled with random values!
[ INFO ] Fill input 'image' with random values
[ INFO ] Fill input 'onnx::Unsqueeze_1' with random values
[Step 10/11] Measuring performance (Start inference asynchronously, 4 inference requests, limits: 60000 ms duration)
[ INFO ] Benchmarking in inference only mode (inputs filling are not included in measurement loop).
[ INFO ] First inference took 1152.67 ms
[Step 11/11] Dumping statistics report
[ INFO ] Count:            212 iterations
[ INFO ] Duration:         61945.89 ms
[ INFO ] Latency:
[ INFO ]    Median:        1154.87 ms
[ INFO ]    Average:       1160.65 ms
[ INFO ]    Min:           1132.43 ms
[ INFO ]    Max:           1224.72 ms
[ INFO ] Throughput:   3.42 FPS
```

**Comment by ilya-naumov** [comment]
Hi @zulkifli-halim,
Thank you for the provided workaround. 
I use benchmark_app to measure models with different values of batch size. The benchmark_app from the previous 2022.2 release works fine for this model with the option `-b 1`, but version 2022.3 produces the exception with same command line. 
It looks like a bug. Can this problem be fixed in the next OpenVINO release?

**Comment by zulkifli-halim** [comment]
Hi @ilya-naumov, can you share with me the result from OpenVINO 2022.2? I faced the same error even after when I switched to OV 2022.2:
```
[Step 1/11] Parsing and validating input arguments
[ WARNING ]  -nstreams default value is determined automatically for a device. Although the automatic selection usually provides a reasonable performance, but it still may be non-optimal for some cases, for more information look at README.
[Step 2/11] Loading OpenVINO
[ WARNING ] PerformanceMode was not explicitly specified in command line. Device CPU performance hint will be set to THROUGHPUT.
[ INFO ] OpenVINO:
         API version............. 2022.2.0-7713-af16ea1d79a-releases/2022/2
[ INFO ] Device info
         CPU
         openvino_intel_cpu_plugin version 2022.2
         Build................... 2022.2.0-7713-af16ea1d79a-releases/2022/2

[Step 3/11] Setting device configuration
[ WARNING ] -nstreams default value is determined automatically for CPU device. Although the automatic selection usually provides a reasonable performance, but it still may be non-optimal for some cases, for more information look at README.
[Step 4/11] Reading network files
[ INFO ] Read model took 191.42 ms
[Step 5/11] Resizing network to match image sizes and given batch
[ ERROR ] Accessing out-of-range dimension in Dimension[]
Traceback (most recent call last):
  File "/home/2022_2/openvino_env/lib/python3.8/site-packages/openvino/tools/benchmark/main.py", line 268, in run
    app_inputs_info, reshape = get_inputs_info(args.shape, args.data_shape, args.layout, args.batch_size, args.input_scale, args.input_mean, model.inputs)
  File "/home/2022_2/openvino_env/lib/python3.8/site-packages/openvino/tools/benchmark/utils/utils.py", line 563, in get_inputs_info
    supposed_batch = info.partial_shape[0]
IndexError: Accessing out-of-range dimension in Dimension[]
```

Which method did you use to install OpenVINO ([pip](https://pypi.org/project/openvino-dev/), [GitHub](https://github.com/openvinotoolkit/openvino), [Archives](https://storage.openvinotoolkit.org/repositories/openvino/packages/2022.3/linux))?

**Comment by zulkifli-halim** [comment]
Hi @ilya-naumov, this could be a bug in the latest OpenVINO release. Thank you for reporting and we will rectify this issue.

**Comment by hbalasu1** [comment]
The issue has been escalated for further investigation. 

Ref 100581

**Comment by hbalasu1** [comment]
Hi @ilya-naumov 

For your information, torch changed the behavior for the export model to onnx with default args represented as scalar values. Issue not observable in 2022.2 because it has a limit on torch version in 1.8, where old behavior is preserved. As workaround, you can install this torch version and use it with Openvino 2022.3 and issue is gone, 

For more robust  and predicted behavior, our developer have created pull request for [#3662](https://github.com/openvinotoolkit/open_model_zoo/pull/3662)

**Comment by hbalasu1** [comment]
Hi @ilya-naumov 

Pull request #3662 has been merged, could you try and close the case? 

Thank you

**Comment by ilya-naumov** [comment]
Hi @hbalasu1, this solution works for me, thank you! 
The issue can be closed.
