### ISSUE TITLE
[Bug] libopenvino_intel_myriad_plugin.so: libopenvino_intel_myriad_plugin.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Veereshdammur** [openvinotoolkit/openvino#14918]
##### System information (version)
 
-   OpenVINO => `openvino_2022.3.0.9038`, built using docker image `openvino/ubuntu20_dev image`
-   Operating System / Platform => `Ubuntu 20.04 LTS`,
-   Problem classification: Openvino installation error 
-   Framework: Caffe
-   Model name: `GoogleNet`
 
##### Detailed description
 
I tried running the sample image classification [example](https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_docker_linux.html#running-the-image-on-intel-neural-compute-stick-2) but couldn't succeed. 

```
veeresh@veeresh:~$ sudo docker run -it --device-cgroup-rule='c 189:* rmw' -v /dev/bus/usb:/dev/bus/usb -v /home/veeresh/Downloads/test_dir/:/tmp/test_dir/  --rm openvino/ubuntu20_dev:latest 
openvino@5e57586cb892:/opt/intel/openvino_2022.3.0.9038$ /bin/bash -c "omz_downloader --name googlenet-v1 --precisions FP16 && omz_converter --name googlenet-v1 --precision FP16 && curl -O https://storage.openvinotoolkit.org/data/test_data/images/car_1.bmp && python3 samples/python/hello_classification/hello_classification.py public/googlenet-v1/FP16/googlenet-v1.xml car_1.bmp MYRIAD"
################|| Downloading googlenet-v1 ||################

========== Downloading /opt/intel/openvino_2022.3.0.9038/public/googlenet-v1/googlenet-v1.prototxt
... 100%, 35 KB, 42254 KB/s, 0 seconds passed

========== Downloading /opt/intel/openvino_2022.3.0.9038/public/googlenet-v1/googlenet-v1.caffemodel
... 100%, 52279 KB, 52915 KB/s, 0 seconds passed

========== Replacing text in /opt/intel/openvino_2022.3.0.9038/public/googlenet-v1/googlenet-v1.prototxt

========== Converting googlenet-v1 to IR (FP16)
Conversion command: /usr/bin/python3.8 -- /usr/local/bin/mo --framework=caffe --data_type=FP16 --output_dir=/opt/intel/openvino_2022.3.0.9038/public/googlenet-v1/FP16 --model_name=googlenet-v1 --input=data '--mean_values=data[104.0,117.0,123.0]' --output=prob --input_model=/opt/intel/openvino_2022.3.0.9038/public/googlenet-v1/googlenet-v1.caffemodel --input_proto=/opt/intel/openvino_2022.3.0.9038/public/googlenet-v1/googlenet-v1.prototxt '--layout=data(NCHW)' '--input_shape=[1, 3, 224, 224]'

[ WARNING ]  Use of deprecated cli option --data_type detected. Option use in the following releases will be fatal. 
[ INFO ] The model was converted to IR v11, the latest model format that corresponds to the source DL framework input/output format. While IR v11 is backwards compatible with OpenVINO Inference Engine API v1.0, please use API v2.0 (as of 2022.1) to take advantage of the latest improvements in IR v11.
Find more information about API v2.0 and IR v11 at https://docs.openvino.ai/latest/openvino_2_0_transition_guide.html
[ SUCCESS ] Generated IR version 11 model.
[ SUCCESS ] XML file: /opt/intel/openvino_2022.3.0.9038/public/googlenet-v1/FP16/googlenet-v1.xml
[ SUCCESS ] BIN file: /opt/intel/openvino_2022.3.0.9038/public/googlenet-v1/FP16/googlenet-v1.bin

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1398k  100 1398k    0     0  3361k      0 --:--:-- --:--:-- --:--:-- 3361k
[ INFO ] Creating OpenVINO Runtime Core
[ INFO ] Reading the model: public/googlenet-v1/FP16/googlenet-v1.xml
[ INFO ] Loading the model to the plugin
Traceback (most recent call last):
  File "samples/python/hello_classification/hello_classification.py", line 114, in <module>
    sys.exit(main())
  File "samples/python/hello_classification/hello_classification.py", line 80, in main
    compiled_model = core.compile_model(model, device_name)
  File "/opt/intel/openvino_2022.3.0.9038/python/python3.8/openvino/runtime/ie_api.py", line 399, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: Cannot load library 'libopenvino_intel_myriad_plugin.so: libopenvino_intel_myriad_plugin.so: cannot open shared object file: No such file or directory
openvino@5e57586cb892:/opt/intel/openvino_2022.3.0.9038$ 
```

 
 

I have updated my udev rules as follow, 

```
cat <<EOF > 97-myriad-usbboot.rules
SUBSYSTEM=="usb", ATTRS{idProduct}=="2150", ATTRS{idVendor}=="03e7", GROUP="users", MODE="0666", ENV{ID_MM_DEVICE_IGNORE}="1"
SUBSYSTEM=="usb", ATTRS{idProduct}=="2485", ATTRS{idVendor}=="03e7", GROUP="users", MODE="0666", ENV{ID_MM_DEVICE_IGNORE}="1"
SUBSYSTEM=="usb", ATTRS{idProduct}=="f63b", ATTRS{idVendor}=="03e7", GROUP="users", MODE="0666", ENV{ID_MM_DEVICE_IGNORE}="1"
EOF

sudo cp 97-myriad-usbboot.rules /etc/udev/rules.d/
sudo udevadm control --reload-rules
sudo udevadm trigger
sudo ldconfig
```

The device is being recognized on the system, 
```
veeresh@veeresh:~$ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 001 Device 004: ID 0c45:632e Microdia USB 2.0 Camera
Bus 001 Device 003: ID 0bda:b812 Realtek Semiconductor Corp. 802.11ac NIC
Bus 001 Device 007: ID 1b1c:0c08 Corsair H80i v2
Bus 001 Device 006: ID 03e7:2485 Intel Movidius MyriadX
Bus 001 Device 002: ID 0bda:8771 Realtek Semiconductor Corp. Bluetooth Radio
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
veeresh@veeresh:~$ 

```

**Comment by ilya-lavrenov** [comment]
Hi @Veereshdammur,

As you can read in [releasee notes](https://github.com/openvinotoolkit/openvino/releases/tag/2022.3.0), MYRIAD plugin is not a part of 2022.3 release and you need to use 2022.1 to leverage MYRIAD stick.

Thanks.

**Comment by Veereshdammur** [comment]
> Hi @Veereshdammur,
> 
> As you can read in [releasee notes](https://github.com/openvinotoolkit/openvino/releases/tag/2022.3.0), MYRIAD plugin is not a part of 2022.3 release and you need to use 2022.1 to leverage MYRIAD stick.
> 
> Thanks.

Thanks Roman for the quick reply. It worked well after switching to the 2022.2 version.

**Comment by zulkifli-halim** [comment]
Closing issue.
