### ISSUE TITLE
MO conversion error: Check 'i < input_pshape.rank().get_length()'

### ISSUE THREAD

**Issue by Simardeep27** [openvinotoolkit/openvino#15084]
Hi,

I am trying to convert DINO (https://github.com/IDEA-Research/DINO) to OpenVino IR and was able to convert it to ONNX (https://drive.google.com/file/d/150dUWR3xS2A7aqobjuSQj8GqDLV-tplJ/view?usp=sharing) but got the following error while converting using model optimizer.

[ ERROR ]  Check 'i < input_pshape.rank().get_length()' failed at C:\j\workspace\private-ci\ie\build-windows-vs2019@3\b\repos\openvino\src\core\src\op\reshape.cpp:391:
While validating node 'v1::Reshape Reshape_428470 (onnx::Shape_14522[0]:f32{?,256}, onnx::Reshape_14532[0]:i64{3}) -> (f32{?,?,?})' with friendly_name 'Reshape_428470':
'0' dimension is out of range

ONNX opset version:13(checked with all other opset versions>13)
OpenVino Version: 2022.1

What could be the reason behind this error?

Thanks

**Comment by rkazants** [comment]
Hi @Simardeep27,

I tried your model to convert with the latest source build and this is converted. If it is not critical for you, can you try please our latest release 2022.3?
My cmd-line to convert:
```
mo --input_model DINO_op13.onnx
```

Best regards,
Roman

**Comment by Simardeep27** [comment]
Hi @rkazants, thanks for the reply.

I did test the conversion using version 2022.3. Although the conversion from ONNX to IR is successful, while loading the model to CPU or a VPU, it shows the following error:

RuntimeError: There should be only one instance of RegistersPool per thread

**Comment by Simardeep27** [comment]
Update: I was able to run the basic pipeline for model loading the above mentioned IR file. The issue I faced earlier was encountered when the onnx file was generated through opset versions 14 and 15.

**Comment by rkazants** [comment]
Hi @Simardeep27,

I see that the maximum opset for operation is `opset8` (introduces in 2022.1) in the generated IR. Can you try to infer this IR by 2022.1 on VPU?

Best regards,
Roman

**Comment by Simardeep27** [comment]
Hey @rkazants,

For version 2022.1, the model does compile on CPU, but fails to compile on a MYRIAD device.
The error displayed is:
Failed to compile layer "CumSum_1751": unsupported layer type "CumSum"

**Comment by rkazants** [comment]
@Simardeep27, that seems to me that even IR generated with 2022.1 will lead to the same error. This is limitation of the VPU plugin:(
@Maxim-Doronin, @DariaMityagina, can you please comment if you support `CumSum` on VPU or you have decomposing transformation for this operation?

Best regards,
Roman

**Comment by DariaMityagina** [comment]
> CumSum

Hi @rkazants , @Simardeep27 !
No, unfortunately the `CumSum` operation is not supported for MYRIAD devices.

Best regards,
Daria

**Comment by rkazants** [comment]
@Simardeep27, can you please share what kind of `CumSum` you have in your model and how many of them? I would like to know if we can decompose it or not.

Regards,
Roman

**Comment by Simardeep27** [comment]
So, there were 4-5 cumsum operations that were being implemented for positional embedding. I replaced those with a custom function built through basic pytorch functions. Now, the cumsum operation is removed, but when I compile the new model with v2022.1 I face another error for a different layer:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Intel\openvino_2022\python\python3.9\openvino\runtime\ie_api.py", line 266, in compile_model
    super().compile_model(model, device_name, {} if config is None else config)
RuntimeError: [ GENERAL_ERROR ]
C:\j\workspace\private-ci\ie\build-windows-vs2019@3\b\repos\openvino\src\plugins\intel_myriad\graph_transformer\src\frontend\frontend.cpp:592 Failed to compile layer "Cos_29787": unsupported layer type "Cos"

**Comment by Simardeep27** [comment]
Hey @rkazants, the model architecture which I am currently working on applies dynamic positional encoding, so it might not be possible to convert it to a constant. Is there any method by which IR files generation can be done using v2022.1 only, because I feel using IR files generated through v2022.3 might have a lot of mismatched operations while compilation in v2022.3.

**Comment by rkazants** [comment]
@Simardeep27, I think VPU is not targeted to support such complex operations like `Cos`.
@DariaMityagina, @Maxim-Doronin, can you comment please why `Cos` support is missed in VPU?

Best regards,
Roman

**Comment by Simardeep27** [comment]
Is there any alternative to creating custom function for Cos and Sin in this case, since they will be highly inefficient?

**Comment by avitial** [comment]
@Simardeep27 according to [Supported Devices](https://docs.openvino.ai/2022.1/openvino_docs_OV_UG_supported_plugins_Supported_Devices.html#doxid-openvino-docs-o-v-u-g-supported-plugins-supported-devices) in documentation `Cos` and `Sin` ops are not supported by VPU plugins. Not sure there are any alternatives to this.
