### ISSUE TITLE
OpenVINO does not support the following ONNX operations: ConcatFromSequence, SequenceEmpty, SplitToSequence

### ISSUE THREAD

**Issue by shu0o0** [openvinotoolkit/openvino#15094]
Is it a problem of my model? What should I do to solve it?
Plateform is Windows 10, It is my openvino version:
openvino                2022.3.0
openvino-dev            2022.3.0
openvino-telemetry      2022.3.0

It's error:
[ ERROR ]  Traceback (most recent call last):
  File "F:\Anaconda3\envs\pytorch\Lib\site-packages\openvino\tools\mo\main.py", line 50, in main
    ngraph_function = convert_model(**argv)
  File "F:\Anaconda3\envs\pytorch\lib\site-packages\openvino\tools\mo\convert.py", line 47, in convert_model
    return _convert(**args)
  File "F:\Anaconda3\envs\pytorch\lib\site-packages\openvino\tools\mo\convert_impl.py", line 937, in _convert
    raise e.with_traceback(None)
RuntimeError: Check 'unknown_operators.empty()' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\frontends\onnx\frontend\src\core\graph.cpp:215:
OpenVINO does not support the following ONNX operations: ConcatFromSequence, SequenceEmpty, SplitToSequence

**Comment by mbencer** [comment]
Hi @shu0o0yX, ONNX Sequence-based operations are currently not supported by OpenVINO. Some initial research work is in progress, but I am not able to say any specific date.

**Comment by shu0o0yX** [comment]
> 

OK! Thanks for your reply.

**Comment by shu0o0yX** [comment]
> Hi @shu0o0yX, ONNX Sequence-based operations are currently not supported by OpenVINO. Some initial research work is in progress, but I am not able to say any specific date.

OK! Thanks for your reply.

**Comment by mlukasze** [comment]
hey @shu0o0yX, could you share a name/source of the model, if it is not a problem?

**Comment by shu0o0yX** [comment]
> hey @shu0o0yX, could you share a name/source of the model, if it is not a problem?

OK! The link is https://github.com/OFA-Sys/DAFlow. Hope that helps.

**Comment by mlukasze** [comment]
it will, thank you!

**Comment by rkazants** [comment]
Internal ticket to track enabling this model: 101224

**Comment by shu0o0yX** [comment]
> Internal ticket to track enabling this model: 101224

What does that mean?

**Comment by brmarkus** [comment]
> 

This is an internal reference to an internal issue-tracking system.

**Comment by gjn2659338105** [comment]
> Is it a problem of my model? What should I do to solve it? Plateform is Windows 10, It is my openvino version: openvino 2022.3.0 openvino-dev 2022.3.0 openvino-telemetry 2022.3.0
> 
> It's error: [ ERROR ] Traceback (most recent call last): File "F:\Anaconda3\envs\pytorch\Lib\site-packages\openvino\tools\mo\main.py", line 50, in main ngraph_function = convert_model(**argv) File "F:\Anaconda3\envs\pytorch\lib\site-packages\openvino\tools\mo\convert.py", line 47, in convert_model return _convert(**args) File "F:\Anaconda3\envs\pytorch\lib\site-packages\openvino\tools\mo\convert_impl.py", line 937, in _convert raise e.with_traceback(None) RuntimeError: Check 'unknown_operators.empty()' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\frontends\onnx\frontend\src\core\graph.cpp:215: OpenVINO does not support the following ONNX operations: ConcatFromSequence, SequenceEmpty, SplitToSequence

Are you also working on virtual try-on recently? I converted several models to OpenVINO IR Format but all failed.

**Comment by shu0o0yX** [comment]
> > Is it a problem of my model? What should I do to solve it? Plateform is Windows 10, It is my openvino version: openvino 2022.3.0 openvino-dev 2022.3.0 openvino-telemetry 2022.3.0
> > It's error: [ ERROR ] Traceback (most recent call last): File "F:\Anaconda3\envs\pytorch\Lib\site-packages\openvino\tools\mo\main.py", line 50, in main ngraph_function = convert_model(**argv) File "F:\Anaconda3\envs\pytorch\lib\site-packages\openvino\tools\mo\convert.py", line 47, in convert_model return _convert(**args) File "F:\Anaconda3\envs\pytorch\lib\site-packages\openvino\tools\mo\convert_impl.py", line 937, in _convert raise e.with_traceback(None) RuntimeError: Check 'unknown_operators.empty()' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\frontends\onnx\frontend\src\core\graph.cpp:215: OpenVINO does not support the following ONNX operations: ConcatFromSequence, SequenceEmpty, SplitToSequence
> 
> Are you also working on virtual try-on recently? I converted several models to OpenVINO IR Format but all failed.

Maybe virtual try-on models are not fit for OpenVINO.

**Comment by akladiev** [comment]
This issue will be closed in 2 weeks in case of no activity.
