### ISSUE TITLE
Unexpected exception happened when Transform YOLO-v3-tf.pb to IR.

### ISSUE THREAD

**Issue by Ludwig-Zh** [openvinotoolkit/openvino#1525]
Hi,
  When I tried to transform yolo-v3-tf.pb(download from https://download.01.org/opencv/) to IR file, by command:
 "python3 mo_tf.py --input_model ~/openvino_models/downloader/public/yolo-v3-tf/yolo-v3.pb -b 1 --tensorflow_custom_operations_config ~/openvino_models/downloader/public/yolo-v3-tf/yolo-v3.json"
  then got these ERROR message:
  Model Optimizer version: 	
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID (<class 'extensions.front.tf.tensorflow_custom_operations_config_update.TensorflowCustomOperationsConfigUpdate'>)": The function 'update_custom_layer_attributes' must be implemented in the sub-class.
[ ERROR ]  Traceback (most recent call last):
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 288, in apply_transform
    for_graph_and_each_sub_graph_recursively(graph, replacer.find_and_replace_pattern)
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/middle/pattern_match.py", line 58, in for_graph_and_each_sub_graph_recursively
    func(graph)
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/extensions/front/tf/tensorflow_custom_operations_config_update.py", line 59, in find_and_replace_pattern
    replacement_desc.update_custom_replacement_attributes(graph)
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/utils/custom_replacement_config.py", line 136, in update_custom_replacement_attributes
    raise Exception("The function 'update_custom_layer_attributes' must be implemented in the sub-class.")
Exception: The function 'update_custom_layer_attributes' must be implemented in the sub-class.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/main.py", line 312, in main
    ret_code = driver(argv)
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/main.py", line 273, in driver
    ret_res = emit_ir(prepare_ir(argv), argv)
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/main.py", line 238, in prepare_ir
    graph = unified_pipeline(argv)
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/pipeline/unified.py", line 29, in unified_pipeline
    class_registration.ClassType.BACK_REPLACER
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 334, in apply_replacements
    apply_replacements_list(graph, replacers_order)
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 324, in apply_replacements_list
    num_transforms=len(replacers_order))
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/utils/logger.py", line 124, in wrapper
    function(*args, **kwargs)
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 312, in apply_transform
    )) from err
Exception: Exception occurred during running replacer "REPLACEMENT_ID (<class 'extensions.front.tf.tensorflow_custom_operations_config_update.TensorflowCustomOperationsConfigUpdate'>)": The function 'update_custom_layer_attributes' must be implemented in the sub-class.

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------

 Environments:
 OPENVINO 2020.3
 Ubuntu 18.04
 Python3.7.5
 Tensorflow 1.14
 
 I have seen similar issue before but didn't find the answer. Any tips here?

**Comment by Ludwig-Zh** [comment]
Sorry, i mad a mistake in command:
should use "--tensorflow_use_custom_operations_config" instead of "--tensorflow_custom_operations_config". closed.
