### ISSUE TITLE
[Bug] Model quantization failed

### ISSUE THREAD

**Issue by fmo-mt** [openvinotoolkit/openvino#15557]
##### System information (version)
- OpenVINO=> :grey_question: https://github.com/mvafin/openvino/tree/mvafin/fix/broadcast_legacy
- Operating System / Platform => :grey_question: Ubuntu20.04
- Compiler => :grey_question: gcc
- Problem classification => :grey_question: Model quantization

##### Detailed description
Following the issue #15427 , I can load model with fixed commits, but going on quantization it fails still.

##### Steps to reproduce
Model just almost same as: https://github.com/ming024/FastSpeech2
converted to openvino IR by `mo --input_model ../fastspeech2.onnx --input speaker_id,input_id,seq_len --input_shape [1,1],[1,-1],[1,1]` (more info see #15427 )

I quantize openvino IR model using:
```python
from openvino.runtime import Core
from openvino.tools.pot import load_model, IEEngine, compress_model_weights, create_pipeline

model_config = xxx
model = load_model(model_config=model_config) # fixed by mvafin
engine_config = {"device": "CPU"}
algorithms = [
    {
    "name": "DefaultQuantization",
    "params": {
        "target_device": "ANY",
        "preset": "performance",
        "stat_subset_size": 100,
        "activations": {"range_estimator": {
            "min": {"aggregator": "min", "type": "min"},
            "max": {"aggregator": "mean", "type": "quantile", "outlier_prob": 0.001}
         }},
         "ignored": {"scope": ["214"]}
        }}]
engine = IEEngine(config=engine_config, data_loader=dataloader, metric=None) # I don't need a metric
pipeline = create_pipeline(algo_config=algorithms, engine=engine)
compressed_model = pipeline.run(model=model) # Got ERROR!
```
error log:
```txt
Traceback (most recent call last):
  File "tools/openvino_fastspeech2_compare.py", line 189, in <module>
    quant_vino_model()
  File "tools/openvino_fastspeech2_compare.py", line 174, in quant_vino_model
    compressed_model = pipeline.run(model=model)
  File "/root/pyenv/fmo/lib/python3.8/site-packages/openvino/tools/pot/pipeline/pipeline.py", line 52, in run
    result = self.collect_statistics_and_run(model, current_algo_seq)
  File "/root/pyenv/fmo/lib/python3.8/site-packages/openvino/tools/pot/pipeline/pipeline.py", line 58, in collect_statistics_and_run
    collect_statistics(self._engine, model, algo_seq)
  File "/root/pyenv/fmo/lib/python3.8/site-packages/openvino/tools/pot/statistics/collector.py", line 140, in collect_statistics
    algo.register_statistics(model, stats_collector)
  File "/root/pyenv/fmo/lib/python3.8/site-packages/openvino/tools/pot/algorithms/quantization/default/algorithm.py", line 132, in register_statistics
    algo.register_statistics(model, minmax_bc_collector)
  File "/root/pyenv/fmo/lib/python3.8/site-packages/openvino/tools/pot/algorithms/quantization/minmax/algorithm.py", line 64, in register_statistics
    fqut.insert_fake_quantize_nodes(self._config, model)
  File "/root/pyenv/fmo/lib/python3.8/site-packages/openvino/tools/pot/algorithms/quantization/fake_quantize.py", line 188, in insert_fake_quantize_nodes
    GraphTransformer(hardware_config).insert_fake_quantize(model, ignored_params)
  File "/root/pyenv/fmo/lib/python3.8/site-packages/openvino/tools/pot/graph/transformer.py", line 87, in insert_fake_quantize
    for_graph_and_each_sub_graph_recursively(model_dict['model'], self._insert_fake_quantize)
  File "/root/pyenv/fmo/lib/python3.8/site-packages/openvino/tools/mo/middle/pattern_match.py", line 46, in for_graph_and_each_sub_graph_recursively
    func(graph)
  File "/root/pyenv/fmo/lib/python3.8/site-packages/openvino/tools/pot/graph/transformer.py", line 65, in _insert_fake_quantize
    self.fq_propagation.find_and_replace_pattern(graph)
  File "/root/pyenv/fmo/lib/python3.8/site-packages/openvino/tools/pot/graph/passes.py", line 319, in find_and_replace_pattern
    m_op = find_operation_matches(self.quantize_agnostic_operations, input_node)
  File "/root/pyenv/fmo/lib/python3.8/site-packages/openvino/tools/pot/graph/utils.py", line 110, in find_operation_matches
    if operations_matched(src_op, dst_op):
  File "/root/pyenv/fmo/lib/python3.8/site-packages/openvino/tools/pot/graph/utils.py", line 97, in operations_matched
    ie_dst_op = convert_mo_to_ie_operation(dst_op) if ie_in_dst_op else dst_op
  File "/root/pyenv/fmo/lib/python3.8/site-packages/openvino/tools/pot/graph/utils.py", line 75, in convert_mo_to_ie_operation
    return process_list(op, op['IE'])
  File "/root/pyenv/fmo/lib/python3.8/site-packages/openvino/tools/pot/graph/utils.py", line 66, in process_list
    ie_mo_naming_loc.update(process_list(op, item))
  File "/root/pyenv/fmo/lib/python3.8/site-packages/openvino/tools/pot/graph/utils.py", line 57, in process_list
    ie_mo_naming_loc.update(process_list(op, item))
  File "/root/pyenv/fmo/lib/python3.8/site-packages/openvino/tools/pot/graph/utils.py", line 61, in process_list
    if callable(item[1]) and item[1](op) is not None:
  File "/root/pyenv/fmo/lib/python3.8/site-packages/openvino/tools/mo/ops/If.py", line 298, in <lambda>
    [('id', lambda node: self.re_numerate_internal_id_and_get_if_id(node)), 'name', 'type', 'version'],
  File "/root/pyenv/fmo/lib/python3.8/site-packages/openvino/tools/mo/ops/If.py", line 282, in re_numerate_internal_id_and_get_if_id
    then_graph_nodes[idx]['internal_layer_id'] = idx
  File "/root/pyenv/fmo/lib/python3.8/site-packages/networkx/classes/reportviews.py", line 194, in __getitem__
    return self._nodes[n]
KeyError: 0
```

**Comment by AlexKoff88** [comment]
@MaximProshin, can anybody from the team look at this? It seems like there is a problem with the subgraph processing I am not sure if everything is right on the POT side even so it is failed in the MO part.

**Comment by mvafin** [comment]
@fmo-mt I was thinking initially that problem might be in desterilizing `If` operation in MO, but it seems the issue is in POT tool. I will ask someone from POT to look into issue

**Comment by fmo-mt** [comment]
@mvafin Thanks, if you need anything I can provide just at me in the comment.

**Comment by andrei-kochin** [comment]
@MaximProshin just to follow-up

**Comment by avitial** [comment]
@fmo-mt this issue is still currently being looked at, we will share some updates as soon as they are available. 

@MaximProshin FYI

**Comment by fmo-mt** [comment]
Thanks @mvafin , I'll check that one in a day or two, and would comment later.

**Comment by fmo-mt** [comment]
@mvafin Sorry for late reply, but that commit did fix the problem, thanks again
