### ISSUE TITLE
[Bug] run onnx file out incorrect result

### ISSUE THREAD

**Issue by anhtu812** [openvinotoolkit/openvino#16261]
run [onnx file](https://1drv.ms/u/s!AhFk3ICqlZI2ir1_1tdqlddi_7JnTA?e=eFZkpg) with openvino c++ out incorrect result (num_detections:0 = [0])
run with onnxruntime.InferenceSession python out correct result (num_detections:0 = [100])

**Comment by mbencer** [comment]
I'm confirming that I was able to reproduce the problem using code:
```
from openvino.runtime import Core
import numpy as np

core = Core()
path = "Google_Mobile_Object_Localizer.onnx"
model = core.read_model(path)
shape = [1,192,192,3]
compiled_model = core.compile_model(model, "CPU")
in_name = "Cast:0"
image = np.ones(shape).astype(np.float32)
input_map = {in_name : image}
ov_results = compiled_model.infer_new_request(input_map)

import onnxruntime as rt

sess = rt.InferenceSession(path)

output_names = [out.name for out in sess.get_outputs()]
ort_results = sess.run(output_names, {in_name: image})

for idx, name in enumerate(ov_results.keys()):
    print("output: ", name.get_any_name())
    np.testing.assert_allclose(ov_results[name], ort_results[idx], rtol=1e-5, atol=1e-7)
```
with result
```
output:  detection_boxes:0
Traceback (most recent call last):
  File "maskrcnn.py", line 23, in <module>
    np.testing.assert_allclose(ov_results[name], ort_results[idx], rtol=1e-5, atol=1e-7)
  File "/home/mbencer/.virtualenvs/ov/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1530, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/home/mbencer/.virtualenvs/ov/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-05, atol=1e-07

Mismatched elements: 336 / 400 (84%)
Max absolute difference: 0.8951865
Max relative difference: 1336.1726
 x: array([[[2.944410e-02, 5.193412e-03, 9.757534e-01, 1.000000e+00],
        [5.420375e-02, 6.636504e-01, 9.643924e-01, 9.955779e-01],
        [5.168050e-01, 1.181063e-01, 9.939371e-01, 9.994758e-01],...
 y: array([[[2.814469e-02, 5.193383e-03, 9.744540e-01, 1.000000e+00],
        [5.420375e-02, 6.627206e-01, 9.643924e-01, 9.946481e-01],
        [5.189917e-01, 1.181063e-01, 9.938987e-01, 9.994758e-01],...
```
using OpenVINO from the current master and ORT in version 1.13.1. The work is in progress.

**Comment by hbalasu1** [comment]
Hi @anhtu812 
Is your issue been resolved with the advice given by @mbencer?

**Comment by mbencer** [comment]
@anhtu812 Sorry for a long time responding. The problem occurs also in the current master. Number to internal tracking: 110407

**Comment by gkrivor** [comment]
Still reproducing on a fresh master
