### ISSUE TITLE
[Bug] Tips to resolve issues in conversion of onnx model to OpenVINO IR

### ISSUE THREAD

**Issue by RyanMetcalfeInt8** [openvinotoolkit/openvino#16468]
Hi, was wondering if someone could give some advice for how to potentially resolve issues that I am having converting an my onnx model?

I'm using 2022.3.0 version of openvino devtools:
```
openvino           2022.3.0
openvino-dev       2022.3.0
openvino-telemetry 2022.3.0
```

I receive this error when attempting to use mo to convert the onnx model to IR:
```
>mo --input_model model.onnx
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Check '!axes_val.empty()' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\core\shape_inference\include\unsqueeze_shape_inference.hpp:35:
While validating node 'v0::Unsqueeze Unsqueeze_74548 (Range_74436[0]:i64[336], Constant_74547[0]:i64[0]) -> (dynamic[...])' with friendly_name 'Unsqueeze_74548':
'axes' input is mandatory

[ ERROR ]  Traceback (most recent call last):
  File "D:\OpenVINO\openvino_env\Lib\site-packages\openvino\tools\mo\main.py", line 50, in main
    ngraph_function = convert_model(**argv)
  File "D:\OpenVINO\openvino_env\lib\site-packages\openvino\tools\mo\convert.py", line 47, in convert_model
    return _convert(**args)
  File "D:\OpenVINO\openvino_env\lib\site-packages\openvino\tools\mo\convert_impl.py", line 937, in _convert
    raise e.with_traceback(None)
RuntimeError: Check '!axes_val.empty()' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\core\shape_inference\include\unsqueeze_shape_inference.hpp:35:
While validating node 'v0::Unsqueeze Unsqueeze_74548 (Range_74436[0]:i64[336], Constant_74547[0]:i64[0]) -> (dynamic[...])' with friendly_name 'Unsqueeze_74548':
'axes' input is mandatory
```

I'm pretty new to the details of this conversion process -- Is there a recommended approach to resolve such an issue?

Thanks in advance!

**Comment by rkazants** [comment]
Hi @RyanMetcalfeInt8,

Thanks for your query. The model has `Unsqueeze` with empty `axes` vector that is a sort of corner case uncovered by ONNX specification.

Can you please tell if ONNX Runtime can infer your model? Also, I would ask @mlukasze, @tomdol to look at `Unsqueeze` translator in our ONNX FE and consider expanding it on empty `axes` case.

Best regards,
Roman

**Comment by RyanMetcalfeInt8** [comment]
Hi @rkazants,

Thanks! Yes, the onnx runtime can infer the model. I've also incorporated it into the larger software stack and have confirmed that it produces the correct results.

If it helps, here is a link to a zip containing the onnx model and simple python script that runs inference on random input tensors:
[onnx_model_and_python_script.zip](https://drive.google.com/file/d/1BVMNI_ysIPXVjdRwgyPmkaVUocf8PRXJ/view?usp=sharing)

Thanks for the support!

Ryan

**Comment by RyanMetcalfeInt8** [comment]
@tomdol thanks! I just tried benchmark_app (from 2022.3 sampels), passing the onnx model directly and it worked!

So I think inferring directly is fine for now. Would I expect MO to perform any additional performance optimizations if/when it works? I guess that would be the only reason I'd want to use MO to convert to IR ahead of time.

**Comment by andrei-kochin** [comment]
@RyanMetcalfeInt8 please try latest master as #16851 seems fixing the issue

**Comment by akladiev** [comment]
This issue will be closed in 2 weeks in case of no activity.

**Comment by avitial** [comment]
Ref. 106636

Closing this as issue has been addressed. Feel free to reopen to ask any questions related to this topic.
