### ISSUE TITLE
[Bug] An OpenCL error occurred: -6

### ISSUE THREAD

**Issue by violet17** [openvinotoolkit/openvino#16675]
Run "`benchmark_app -d GPU -m model.xml -hint latency`"
get 
```
[Step 7/11] Loading the model to the device
[ ERROR ] An OpenCL error occurred: -6
Traceback (most recent call last):
  File "/home/test/miniconda3/lib/python3.8/site-packages/openvino/tools/benchmark/main.py", line 414, in main
    compiled_model = benchmark.core.compile_model(model, benchmark.device)
  File "/home/test/miniconda3/lib/python3.8/site-packages/openvino/runtime/ie_api.py", line 399, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: An OpenCL error occurred: -6
```

##### System information (version)

- OpenVINO => 2022.3
- Operating System / Platform => Ubuntu 22.04 5.17.0-1020-oem
- Problem classification: Inference
- Model name: yolov5m or other models
- Driver verion  22.49.25018.23

I have met this error before and there libs conflicts in `/usr/local/lib/`.
But now I can not find `libig*` in `/usr/local/lib/`, so it is not the problem of lib conflicts by `libig*`.

And the GPU is Arc A770. I have install and reinstall the driver.
`benchmark_app -h` and `clinfo` get right results and no error.

"`err：-6`" means `CL_OUT_OF_HOST_MEMORY`  in OpenCL, however, I have two 8GB memory in my test NUC.
Before I upgrade the system from ubuntu 20.04 to ubuntu 22.04, I can run inference on GPU. This error happens after upgrade system.
What's more, I have followed this link[https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-jammy-arc.html] to set up my environment.
The C++ version of benchmark_app also gets the same error as python version.

Thanks.

**Comment by violet17** [comment]
This issue has been fixed.
It is still the problem of libig*.

Use this command dpkg -l | grep libig
```
ii  libigc-dev                                       1.0.12504.6+i537~20.04                  amd64        Intel graphics compiler for OpenCL -- core development files
ii  libigc1                                          1.0.12504.6+i537~20.04                  amd64        Intel graphics compiler for OpenCL -- core libs
ii  libigdfcl-dev                                    1.0.12504.6+i537~20.04                  amd64        Intel graphics compiler for OpenCL -- OpenCL development files
ii  libigdfcl1                                       1.0.12504.6+i537~20.04                  amd64        Intel graphics compiler for OpenCL -- OpenCL library
ii  libigdgmm11:amd64                                21.3.3+i643~u20.04                      amd64        Intel Graphics Memory Management Library -- shared library
ii  libigdgmm12:amd64                                22.3.3+i550~22.04                       amd64        Intel Graphics Memory Management Library -- shared library
```
There are still some libs related to ubuntu 20.04.
So I remove the libs according to https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-focal-arc.html
```
sudo apt-get autoremove \
  intel-opencl-icd \
  intel-level-zero-gpu level-zero \
  intel-media-va-driver-non-free libmfx1 libmfxgen1 libvpl2 \
  libegl-mesa0 libegl1-mesa libegl1-mesa-dev libgbm1 libgl1-mesa-dev libgl1-mesa-dri \
  libglapi-mesa libgles2-mesa-dev libglx-mesa0 libigdgmm11 libxatracker2 mesa-va-drivers \
  mesa-vdpau-drivers mesa-vulkan-drivers va-driver-all vainfo
```

```
sudo apt-get autoremove -y \
  libigc-dev \
  intel-igc-cm \
  libigdfcl-dev \
  libigfxcmrt-dev \
  level-zero-dev
```

 Then, reinstall libs about ubuntu 22.04

```
sudo apt-get install -y \
  intel-opencl-icd intel-level-zero-gpu level-zero \
  intel-media-va-driver-non-free libmfx1 libmfxgen1 libvpl2 \
  libegl-mesa0 libegl1-mesa libegl1-mesa-dev libgbm1 libgl1-mesa-dev libgl1-mesa-dri \
  libglapi-mesa libgles2-mesa-dev libglx-mesa0 libigdgmm12 libxatracker2 mesa-va-drivers \
  mesa-vdpau-drivers mesa-vulkan-drivers va-driver-all vainfo
```
