### ISSUE TITLE
[Bug] Failed to convert pre-trained public model in OpenVINO model zoo

### ISSUE THREAD

**Issue by Semmer2** [openvinotoolkit/openvino#16983]
##### System information (version)
- OpenVINO => 2022.3.0
- OpenVINO_dev => 2022.3.0
- Operating System / Platform => Ubuntu 20.04
- Problem classification: Model Conversion
- Framework: 
- Model name: Some of the omz_downloader downloaded model, name list in 'Detailed description'.

##### Detailed description

I have managed to download all public pre-trained model by omz_downloader tool, but when I tried to convert them to OpenVINO format with command `omz_converter --all`, it just failed with some public models.
And here is the model name list:
`aclnet
aclnet-int8
bert-base-ner
brain-tumor-segmentation-0001
cocosnet
colorization-siggraph
colorization-v2
convnext-tiny
ctdet_coco_dlav0_512
ctpn
deblurgan-v2
detr-resnet50
dla-34
drn-d-38
efficientdet-d0-tf
efficientdet-d1-tf
efficientnet-b0-pytorch
efficientnet-v2-b0
efficientnet-v2-s
f3net
faceboxes-pytorch
fastseg-large
fastseg-small
fbcnn
googlenet-v3-pytorch
gpt-2
hbonet-0.25
hbonet-1.0
higher-hrnet-w32-human-pose-estimation
hrnet-v2-c1-segmentation
human-pose-estimation-3d-0001
hybrid-cs-model-mri
levit-128s
midasnet
mobilefacedet-v1-mxnet
mobilenet-v2-pytorch
mobilenet-v3-large-1.0-224-paddle
mobilenet-v3-small-1.0-224-paddle
modnet-photographic-portrait-matting
modnet-webcam-portrait-matting
nanodet-m-1.5x-416
nanodet-plus-m-1.5x-416
nfnet-f0
ocrnet-hrnet-w48-paddle
octave-resnet-26-0.25
pspnet-pytorch
quartznet-15x5-en
regnetx-3.2gf
repvgg-a0
repvgg-b1
repvgg-b3
resnest-50-pytorch
resnet-18-pytorch
resnet-34-pytorch
resnet-50-pytorch
retinaface-resnet50-pytorch
rexnet-v1-x1.0
shufflenet-v2-x1.0
single-human-pose-estimation-0001
swin-tiny-patch4-window7-224
t2t-vit-14
text-recognition-resnet-fc
vitstr-small-patch16-224
wav2vec2-base
yolact-resnet50-fpn-pytorch
yolof
yolox-tiny`

And the error message for each model can be different, for example the errors in converting `aclnet` is
`WARNING:root:Failed to send event with the following error: HTTPSConnectionPool(host='www.google-analytics.com', port=443): Max retries exceeded with url: /collect (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5c6ff6ac70>, 'Connection to www.google-analytics.com timed out. (connect timeout=1.0)'))
WARNING:root:Failed to send event with the following error: HTTPSConnectionPool(host='www.google-analytics.com', port=443): Max retries exceeded with url: /collect (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5c6ef02880>, 'Connection to www.google-analytics.com timed out. (connect timeout=1.0)'))
WARNING:root:Failed to send event with the following error: HTTPSConnectionPool(host='www.google-analytics.com', port=443): Max retries exceeded with url: /collect (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5c6ef029d0>, 'Connection to www.google-analytics.com timed out. (connect timeout=1.0)'))
========== Converting aclnet to IR (FP16)
Conversion command: /home/semmer/openvino_local/openvino_env/bin/python3 -- /home/semmer/openvino_local/openvino_env/bin/mo --framework=onnx --data_type=FP16 --output_dir=/home/semmer/Projects/OpenVINO_ModelZoo/public/aclnet/FP16 --model_name=aclnet --input=input --output=output --input_model=/home/semmer/Projects/OpenVINO_ModelZoo/public/aclnet/aclnet_des_53.onnx '--layout=input(NCWL)' '--input_shape=[1, 1, 1, 16000]'

WARNING:root:Failed to send event with the following error: HTTPSConnectionPool(host='www.google-analytics.com', port=443): Max retries exceeded with url: /collect (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5c6e559a30>, 'Connection to www.google-analytics.com timed out. (connect timeout=1.0)'))
ERROR:root:Use of deprecated cli option --data_type detected. Option use in the following releases will be fatal.
ERROR:root:Use of deprecated cli option --data_type detected. Option use in the following releases will be fatal.
[ WARNING ]  Use of deprecated cli option --data_type detected. Option use in the following releases will be fatal.
ERROR:root:-------------------------------------------------
[ ERROR ]  -------------------------------------------------
ERROR:root:----------------- INTERNAL ERROR ----------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
ERROR:root:Unexpected exception happened.
[ ERROR ]  Unexpected exception happened.
ERROR:root:Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
ERROR:root:Error during import of ONNX model provided as input stream  with binary protobuf message.
[ ERROR ]  Error during import of ONNX model provided as input stream  with binary protobuf message.
ERROR:root:Traceback (most recent call last):
  File "/home/semmer/openvino_local/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/main.py", line 43, in main
    ngraph_function = convert_model(**argv)
  File "/home/semmer/openvino_local/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/convert.py", line 47, in convert_model
    return _convert(**args)
  File "/home/semmer/openvino_local/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/convert_impl.py", line 935, in _convert
    raise e.with_traceback(None)
RuntimeError: Error during import of ONNX model provided as input stream  with binary protobuf message.

[ ERROR ]  Traceback (most recent call last):
  File "/home/semmer/openvino_local/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/main.py", line 43, in main
    ngraph_function = convert_model(**argv)
  File "/home/semmer/openvino_local/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/convert.py", line 47, in convert_model
    return _convert(**args)
  File "/home/semmer/openvino_local/openvino_env/lib/python3.8/site-packages/openvino/tools/mo/convert_impl.py", line 935, in _convert
    raise e.with_traceback(None)
RuntimeError: Error during import of ONNX model provided as input stream  with binary protobuf message.

ERROR:root:---------------- END OF BUG REPORT --------------
[ ERROR ]  ---------------- END OF BUG REPORT --------------
ERROR:root:-------------------------------------------------
[ ERROR ]  -------------------------------------------------
FAILED:
aclnet
WARNING:root:Failed to send event with the following error: HTTPSConnectionPool(host='www.google-analytics.com', port=443): Max retries exceeded with url: /collect (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5c6e56e550>, 'Connection to www.google-analytics.com timed out. (connect timeout=1.0)'))
WARNING:root:Failed to send event with the following error: HTTPSConnectionPool(host='www.google-analytics.com', port=443): Max retries exceeded with url: /collect (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5c6e4f9f70>, 'Connection to www.google-analytics.com timed out. (connect timeout=1.0)'))
WARNING:root:Failed to send event with the following error: HTTPSConnectionPool(host='www.google-analytics.com', port=443): Max retries exceeded with url: /collect (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5c6e514790>, 'Connection to www.google-analytics.com timed out. (connect timeout=1.0)'))`

I think the WARNING for network connection is irrelevant to this issue.

**Comment by mbencer** [comment]
@Semmer2 Could you check which version of `onnx` and `protobuf` python packages have you installed? (you can call just `pip list`)

**Comment by Semmer2** [comment]
Hi @mbencer 
I think maybe I have missed some requirements, so I installed the module you mentioned, and they are `protobuf 3.19.6` and  `onnx 1.12.0`. Hope I installed the correct version. But I still failed to convert the models above.
For `aclnet`, here is new error info:
 ========== Converting aclnet to IR (FP16)
Conversion command: /usr/bin/python -- /home/semmer/.local/bin/mo --framework=onnx --data_type=FP16 --output_dir=/home/semmer/Projects/OpenVINO_ModelZoo/public/aclnet/FP16 --model_name=aclnet --input=input --output=output --input_model=/home/semmer/Projects/OpenVINO_ModelZoo/public/aclnet/aclnet_des_53.onnx '--layout=input(NCWL)' '--input_shape=[1, 1, 1, 16000]'

ERROR:root:Use of deprecated cli option --data_type detected. Option use in the following releases will be fatal.
ERROR:root:Use of deprecated cli option --data_type detected. Option use in the following releases will be fatal.
[ WARNING ]  Use of deprecated cli option --data_type detected. Option use in the following releases will be fatal.
ERROR:root:-------------------------------------------------
[ ERROR ]  -------------------------------------------------
ERROR:root:----------------- INTERNAL ERROR ----------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
ERROR:root:Unexpected exception happened.
[ ERROR ]  Unexpected exception happened.
ERROR:root:Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
ERROR:root:Error during import of ONNX model provided as input stream  with binary protobuf message.
[ ERROR ]  Error during import of ONNX model provided as input stream  with binary protobuf message.
ERROR:root:Traceback (most recent call last):
  File "/home/semmer/.local/lib/python3.8/site-packages/openvino/tools/mo/main.py", line 43, in main
    ngraph_function = convert_model(**argv)
  File "/home/semmer/.local/lib/python3.8/site-packages/openvino/tools/mo/convert.py", line 47, in convert_model
    return _convert(**args)
  File "/home/semmer/.local/lib/python3.8/site-packages/openvino/tools/mo/convert_impl.py", line 935, in _convert
    raise e.with_traceback(None)
RuntimeError: Error during import of ONNX model provided as input stream  with binary protobuf message.

[ ERROR ]  Traceback (most recent call last):
  File "/home/semmer/.local/lib/python3.8/site-packages/openvino/tools/mo/main.py", line 43, in main
    ngraph_function = convert_model(**argv)
  File "/home/semmer/.local/lib/python3.8/site-packages/openvino/tools/mo/convert.py", line 47, in convert_model
    return _convert(**args)
  File "/home/semmer/.local/lib/python3.8/site-packages/openvino/tools/mo/convert_impl.py", line 935, in _convert
    raise e.with_traceback(None)
RuntimeError: Error during import of ONNX model provided as input stream  with binary protobuf message.

ERROR:root:---------------- END OF BUG REPORT --------------
[ ERROR ]  ---------------- END OF BUG REPORT --------------
ERROR:root:-------------------------------------------------
[ ERROR ]  -------------------------------------------------
FAILED:
aclnet

**Comment by Semmer2** [comment]
Updates:
After installation of several python modules, most of the failed models can be converted to OpenVINO format successfully. But still 9 of them failed.
List
`aclnet
aclnet-int8
ctpn/16
deblurgan-v2
drn-d-38
efficientdet-d0-tf
efficientdet-d1-tf
hybrid-cs-model-mri
rexnet-v1-x1.0`
The two efficientdet model are casued by `No module named 'keras.api' `, but I cannot fix it by correctly installed `keras`.
Others got different error infos like what I mentioned above. Hope these infos make sense.

**Comment by avitial** [comment]
@Semmer2 try installing openvino-dev dependencies via _pip_, this resolved for me most of the conversion errors for the 9 listed models you had issues with.
`pip install openvino-dev[caffe,kaldi,mxnet,onnx,pytorch,tensorflow2]==2022.3.0`

Note I still wasn't able to convert the _efficientdet-d0-tf_ and _efficientdet-d1-tf_ models with the above suggestion, it might be a bug in 2022.3.0 in OMZ tools or an issue with TF 2.9.3 (these two models convert fine with openvino-dev 2022.1.0 which installs TF 2.5.3).

As a workaround you can try downgrading your TensorFlow version to 2.5.3 (with `pip install tensorflow==2.5.3`) and see if that fixes the issue for the efficientdet-d models (it worked for me).

**Comment by akladiev** [comment]
This issue will be closed in 2 weeks in case of no activity.

**Comment by avitial** [comment]
The following PR https://github.com/openvinotoolkit/openvino/pull/17570 addresses the model conversion issue for efficientdet-d0/d1-tf with OMZ tools. 

Fix will be available as part of openvino-dev 2023.0 package or can be applied by installing Open Model Zoo from source code from https://github.com/openvinotoolkit/open_model_zoo/tree/releases/2022/3.

Closing this issue as PR has been merged and issue has been addressed.
