### ISSUE TITLE
[Bug] Internal MO error when converting rexnet-v1-x1.0 

### ISSUE THREAD

**Issue by eltimen** [openvinotoolkit/openvino#17369]
##### System information (version)
- OpenVINO Source=> pip
- OpenVINO Version=> 2022.3.0
- Operating System / Platform => Ubuntu 20.04
- Compiler => N/A
- Problem classification => Model Conversion, Model Optimizer
- Device use: => CPU
- Framework => onnx
- Model name => rexnet-v1-x1.0

##### Detailed description
MO crashes with the error below when I trying to convert `rexnet-v1-x1.0` to IR using `omz_converter`:
```
$ omz_converter --name rexnet-v1-x1.0
========== Converting rexnet-v1-x1.0 to ONNX
Conversion to ONNX command: /tmp/test_venv/venv/bin/python3 -- /tmp/test_venv/venv/lib/python3.8/site-packages/openvino/model_zoo/internal_scripts/pytorch_to_onnx.py --model-path=/tmp/test_venv/public/rexnet-v1-x1.0 --model-name=ReXNetV1 --weights=/tmp/test_venv/public/rexnet-v1-x1.0/rexnetv1_1.0x.pth --import-module=rexnetv1 --model-param=width_mult=1.0 --input-shape=1,3,224,224 --output-file=/tmp/test_venv/public/rexnet-v1-x1.0/rexnet-v1-x1.0.onnx --input-names=input.1 --output-names=prob

ONNX check passed successfully.

========== Converting rexnet-v1-x1.0 to IR (FP16)
Conversion command: /tmp/test_venv/venv/bin/python3 -- /tmp/test_venv/venv/bin/mo --framework=onnx --data_type=FP16 --output_dir=/tmp/test_venv/public/rexnet-v1-x1.0/FP16 --model_name=rexnet-v1-x1.0 --input=input.1 --input_model=/tmp/test_venv/public/rexnet-v1-x1.0/rexnet-v1-x1.0.onnx '--mean_values=input.1[123.675,116.28,103.53]' '--scale_values=input.1[58.395,57.12,57.375]' --reverse_input_channels --output=prob '--layout=input.1(NCHW)' '--input_shape=[1, 3, 224, 224]'

[ WARNING ]  Use of deprecated cli option --data_type detected. Option use in the following releases will be fatal. 
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Check '!axes_val.empty()' failed at src/core/shape_inference/include/unsqueeze_shape_inference.hpp:35:
While validating node 'v0::Unsqueeze Unsqueeze_9753 (Range_9641[0]:i64[27], Constant_9752[0]:i64[0]) -> (dynamic[...])' with friendly_name 'Unsqueeze_9753':
'axes' input is mandatory

[ ERROR ]  Traceback (most recent call last):
  File "/tmp/test_venv/venv/lib/python3.8/site-packages/openvino/tools/mo/main.py", line 50, in main
    ngraph_function = convert_model(**argv)
  File "/tmp/test_venv/venv/lib/python3.8/site-packages/openvino/tools/mo/convert.py", line 47, in convert_model
    return _convert(**args)
  File "/tmp/test_venv/venv/lib/python3.8/site-packages/openvino/tools/mo/convert_impl.py", line 937, in _convert
    raise e.with_traceback(None)
RuntimeError: Check '!axes_val.empty()' failed at src/core/shape_inference/include/unsqueeze_shape_inference.hpp:35:
While validating node 'v0::Unsqueeze Unsqueeze_9753 (Range_9641[0]:i64[27], Constant_9752[0]:i64[0]) -> (dynamic[...])' with friendly_name 'Unsqueeze_9753':
'axes' input is mandatory


[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------
FAILED:
rexnet-v1-x1.0
```

##### Steps to reproduce

1. `pip install openvino_dev[pytorch]==2022.3.0`
2. `omz_downloader --name rexnet-v1-x1.0`
3. `omz_converter --name rexnet-v1-x1.0`

**Comment by YuChern-Intel** [comment]
Thanks for highlighting this matter! I also encountered the same issue. 

When installing openvino_dev[pytorch]==2022.3.0, the following packages will be installed and the latest version will be selected.
_torch<=1.13.0,>=1.8.1
torchvision<=0.14.0,>=0.9.1
onnx<=1.12,>=1.8.1_

The current workaround to make the model conversion works is to downgrade the PyTorch version.
_pip install torch==1.8.1
pip install torchvision==0.9.1
pip install onnx==1.8.1_

**Comment by eltimen** [comment]
Hi @YuChern-Intel.
Thank you for the provided workaround. 
Can you please tell me if this problem will be fixed in the next OpenVINO release?

**Comment by YuChern-Intel** [comment]
@eltimen I just tried with the latest pre-released OpenVINO and the conversion is success using the latest versions of PyTorch.

```
pip install openvino-dev[pytorch]==2023.0.0.dev20230427 --no-cache-dir
omz_downloader --name rexnet-v1-x1.0
omz_converter --name rexnet-v1-x1.0
```

**Comment by eltimen** [comment]
@YuChern-Intel Thank you for your assistance!
