### ISSUE TITLE
[Bug] Weights/ifm mismatch

### ISSUE THREAD

**Issue by catid** [openvinotoolkit/openvino#17530]
##### System information (version)
- OpenVINO Source => Runtime /pip install
- OpenVINO Version => Version 2022.3
- Operating System / Platform => Ubuntu 20.10
- Compiler => Python
- Problem classification: Model Conversion
- Device use: GPU
- Framework: PyTorch => ONNX => OpenVINO
- Model name: Custom super-resolution model

##### Detailed description

I'm stumped trying to get OpenVINO to work.  It seems to have some trouble compiling the super-resolution model that I trained for for Intel GPU.

The input is supposed to be NCHW uint8, and output is NCHW uint8, and it does normalization inside the model.  N=1, C=3 RGB, H=234, W=123 (also tried 256x256 with same result).

```bash
(openvino) catid@devnuc:~/sources/upsampling/openvino$ python test_openvino.py
Detected OpenVINO device: CPU (12th Gen Intel(R) Core(TM) i7-1260P)
Detected OpenVINO device: GPU (Intel(R) Graphics [0x46a6] (iGPU))
Loading model...
Model input names: {'input'}, shape: [1,3,234,123]
Model output names: {'output'}, shape: [1,3,468,246]
Traceback (most recent call last):
  File "/home/catid/sources/upsampling/openvino/test_openvino.py", line 119, in <module>
    main()
  File "/home/catid/sources/upsampling/openvino/test_openvino.py", line 102, in main
    compiled_model = core.compile_model(model, args.device, {"PERFORMANCE_HINT": "THROUGHPUT"})
  File "/home/catid/.local/lib/python3.10/site-packages/openvino/runtime/ie_api.py", line 399, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: Error has occured for: convolution:/conv_first/Conv/WithoutBiases
Weights feature maps number(=3) is not equal to: input feature maps number(=123)
Weights/ifm mismatch
```

Can't figure out what this error means!

##### Steps to reproduce

The network is defined like this.  It trains (over about 8 hours) and evaluates fine in PyTorch:

```
class FromInputRGB8(nn.Module):
    def __init__(self):
        super(FromInputRGB8, self).__init__()

    def forward(self, x):
        # Convert data type to FP16 and normalize from [0, 255] to [-1, 1]
        x = x.half()
        x = (x / 127.5) - 1.0

        return x


class SimpleModel(nn.Module):
    def __init__(self, num_in_ch=3, num_feat=64):
        super(SimpleModel, self).__init__()

        self.input_convert = FromInputRGB8()
        self.conv_first = nn.Conv2d(num_in_ch, num_feat, 3, 1, 1)
        # Unrelated stuff removed...

    def forward(self, feat):
        feat = self.input_convert(feat)
        feat = self.conv_first(feat)
        # Unrelated stuff removed...

```

Training produces a .pth file that I convert to ONNX:

```
import torch
import argparse
import onnx
from onnxconverter_common import float16

from upsampling_net import create_vapsr2x

import logging
from tools.logging_tools import setup_colored_logging
setup_colored_logging()

def load_model(model_path):
    model = create_vapsr2x(rgb8output=True)
    model.load_state_dict(torch.load(model_path))
    model.half().eval().cuda()
    return model

def main(args):
    logging.info("Loading model...")

    dummy_input = torch.randn(1, 3, 224, 224).byte().cuda()

    model = load_model(args.input)

    logging.info("Converting model to ONNX...")

    torch.onnx.export(
        model,
        dummy_input,
        args.temp,
        verbose=True,
        opset_version=11,
        input_names=['input'],
        output_names=['output'],
        dynamic_axes={'input' : {0 : 'batch_size', 2 : 'height', 3 : 'width'},    # variable length axes
                    'output' : {0 : 'batch_size', 2 : 'height', 3 : 'width'}})

    logging.info("Converting model to FP16 ONNX...")

    model_fp16 = float16.convert_float_to_float16_model_path(args.temp)

    onnx.save(model_fp16, args.output)

    logging.info("Success!")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Training")
    parser.add_argument("--input", type=str, default="upsampling.pth", help="Input model")
    parser.add_argument("--temp", type=str, default="temp.onnx", help="Temp intermediate model file")
    parser.add_argument("--output", type=str, default="upsampling.onnx", help="Output model")

    args = parser.parse_args()

    main(args)
```

Then I converted to OpenVINO IR format:

```
mo --input_model upsampling.onnx --input "input[1,3,1..,1..]{u8}" --output_dir openvino_model --compress_to_fp16 --use_new_frontend
```

And then trying to actually run the OpenVINO model on GPU with this script:

```
import argparse
import os
import time

from pathlib import Path
import numpy as np
from PIL import Image

from openvino.preprocess import PrePostProcessor, ColorFormat
import openvino.runtime as ov

def process_image(compiled_model, input_path, output_path, w, h):
    # Load an image with PIL
    input_image = Image.open(input_path)
    # Convert to numpy array
    input_image_np = np.array(input_image)

    input_image_np = input_image_np[:h, :w]

    # Reshape input
    input_image_np = input_image_np.transpose((2, 0, 1))
    input_image_np.expand_dims(input_image_np, axis=0)

    # The output would be your upscaled image
    print("Inference input shape:", input_image_np.shape)

    infer_request = compiled_model.create_infer_request()
    infer_request.infer([input_image_np])
    output = infer_request.get_output_tensor().buffer

    # Remove batch dimension
    output.squeeze(output, axis=0)
    output = output.transpose((1, 2, 0))

    # The output would be your upscaled image
    print("Inference output shape:", output.shape)

    # Save output to image
    output_img_pil = Image.fromarray(output)
    output_img_pil.save(output_path)

def main():
    parser = argparse.ArgumentParser(description='2x Image Upsampling with OpenVINO')
    parser.add_argument('--model-dir', type=str, default="openvino_model", help='Path to OpenVino model directory')
    parser.add_argument('--input-dir', type=str, default="urban100", help='Path to input image directory')
    parser.add_argument('--output-dir', type=str, default="urban200", help='Path to output image directory')
    parser.add_argument('--device', type=str, default="GPU", help='OpenVINO device to use')
    args = parser.parse_args()

    # Run inference
    model_xml = os.path.join(args.model_dir, "upsampling.xml")
    model_bin = os.path.join(args.model_dir, "upsampling.bin")

    # Create output directory if not exists
    os.makedirs(args.output_dir, exist_ok=True)

    # Create cache folder
    cache_folder = Path("model_cache")
    cache_folder.mkdir(exist_ok=True)

    # Initialize OpenVINO runtime
    core = ov.Core()
    core.set_property({'CACHE_DIR': cache_folder})

    # print available devices
    for device in core.available_devices:
        device_name = core.get_property(device, "FULL_DEVICE_NAME")
        print(f"Detected OpenVINO device: {device} ({device_name})")

    print("Loading model...")

    # Read the model
    model = core.read_model(model_xml, model_bin)

    # Note: Intel GPU only supports fixed-size input
    # https://docs.openvino.ai/latest/openvino_docs_OV_UG_supported_plugins_GPU.html#dynamic-shapes
    w = 123
    h = 234

    model.reshape([1, 3, h, w])

    print(f"Model input names: {model.input().names}, shape: {model.input().partial_shape}")
    print(f"Model output names: {model.output().names}, shape: {model.output().partial_shape}")

    ppp = PrePostProcessor(model)

    # FIXME: Can we change layout here?

    ppp.input("input").tensor() \
            .set_element_type(ov.Type.u8) \
            .set_layout(ov.Layout('NCHW')) \
            .set_color_format(ColorFormat.RGB) \
            .set_memory_type("GPU_SURFACE")

    ppp.input("input").model().set_layout(ov.Layout('NCHW'))

    ppp.output('output').tensor() \
        .set_layout(ov.Layout("NCHW"))

    model = ppp.build()

    compiled_model = core.compile_model(model, args.device, {"PERFORMANCE_HINT": "THROUGHPUT"})
    #compiled_model = core.compile_model(model, args.device, {"PERFORMANCE_HINT": "LATENCY"})

    print("Running model...")

    # Process each image in the input directory
    start_time = time.time()
    for filename in os.listdir(args.input_dir):
        if filename.endswith('.png') or filename.endswith('.jpg') or filename.endswith('.jpeg'):
            input_path = os.path.join(args.input_dir, filename)
            output_path = os.path.join(args.output_dir, filename)
            process_image(compiled_model, input_path, output_path, w, h)
    end_time = time.time()

    print(f"Processed all images in {end_time - start_time} seconds")

if __name__ == "__main__":
    main()
```

It fails with the error:

```
RuntimeError: Error has occured for: convolution:/conv_first/Conv/WithoutBiases
Weights feature maps number(=3) is not equal to: input feature maps number(=123)
Weights/ifm mismatch
```

Looks like it's using the width of the image in the channel dimension?  I don't see the bug in my code.

**Comment by catid** [comment]
Ah seems to be due to set_memory_type("GPU_SURFACE").  Removing that fixes it.

**Comment by rkazants** [comment]
@vladimir-paramuzov, @p-durandin, please take a look.

Best regards,
Roman

**Comment by catid** [comment]
There are some bugs in the OpenVINO code after the model compilation step that you can ignore since it is failing before it gets to that part.  The final working scripts are here: https://github.com/catid/upsampling/tree/master/openvino

**Comment by avitial** [comment]
Closing this as it seems issue has been resolved. Feel free to reopen to ask any questions related to this topic.
