### ISSUE TITLE
[Bug][ ERROR ] Incorrect number of input edges for layer detection_out

### ISSUE THREAD

**Issue by whatisor** [openvinotoolkit/openvino#1755]
This api(from sample code with my comverted model):
ExecutableNetwork executable_network = ie.LoadNetwork(network, FLAGS_d, configure(FLAGS_config));

Where can I get **specification** of layer shape which is supported by openvino?
I think it is not a bug, but we need a specification to avoid this error from this code:
https://github.com/openvinotoolkit/openvino/blob/8c118ef8b2517aff2fed1506a0c112d09a037dcf/inference-engine/src/mkldnn_plugin/nodes/mkldnn_input_node.cpp

**Comment by whatisor** [comment]
CPU plugin:
if (layer->insData.size() != 3)

Myriad plugin:
IE_ASSERT(numInputs() == 3 || numInputs() == 5);
        IE_ASSERT(numOutputs() == 1);

can you explain why you only support 5-input for Myriad?

**Comment by jgespino** [comment]
Hi @whatisor Please provide additional information.

- OpenVINO toolkit version
- Which sample/demo code are you using?
- Model Details (Framework, Topology)
- Custom Trained model? Which base model was used?

Regards,
Jesus

**Comment by whatisor** [comment]
I checked more your website and found this
https://docs.openvinotoolkit.org/latest/openvino_docs_ops_detection_DetectionOutput_1.html
So this is just an enhancement request.

**Comment by jgespino** [comment]
Hi @whatisor 

Correct, the two additional input for DetectionOutput is only supported on the Myriad Plugin. Could you please provide additional information about your use case (framework, model, CPU/GPU?, etc)? I will pass this information along with the feature request to the development team for concideration.

Regards,
Jesus

**Comment by whatisor** [comment]
@jgespino  it is not related to specific model I am working on,which I cannot share here.
The feature we need is implementing 5-input version for CPU to remove this limitation:

> It can have 2 additional inputs with additional confidence predictions and box coordinates described in the article. The 5-input version of the layer is supported with Myriad plugin only

**Comment by lazarevevgeny** [comment]
The support for DetectionOutput operation with 5 inputs has been added to the CPU plugin. Take a look: https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/src/mkldnn_plugin/nodes/detectionoutput.cpp! It will be available in the official 2021.1 package of OpenVINO, but you can clone the repository and compile it from sources! Enjoy!

**Comment by whatisor** [comment]
@lazarevevgeny , can I use old version ( latest official release version) of tools (https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_Tools_Overview.html) to work on the model which has "DetectionOutput operation with 5 inputs" for cpu optimization?

**Comment by lazarevevgeny** [comment]
@whatisor , I am not 100% sure but I think that tools should work.

**Comment by whatisor** [comment]
@lazarevevgeny , do you have any suggestion for these error?
I got this error while try using above way:
`INFO:app.run:Output log dir: ./results/mobilenet-ssd_MinMaxQuantization/2020-09-01_07-37-35
INFO:app.run:Creating pipeline:
 Algorithm: MinMaxQuantization
 Parameters:
        preset                     : mixed
        range_estimator            : {'preset': 'quantile'}
        stat_subset_size           : 1000
        target_device              : CPU
        exec_log_dir               : ./results/mobilenet-ssd_MinMaxQuantization/2020-09-01_07-37-35
 ===========================================================================
Traceback (most recent call last):
  File "/usr/local/bin/pot", line 11, in <module>
    load_entry_point('pot==1.0', 'console_scripts', 'pot')()
  File "/usr/local/lib/python3.6/dist-packages/pot-1.0-py3.6.egg/app/run.py", line 37, in main
    app(sys.argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/pot-1.0-py3.6.egg/app/run.py", line 56, in app
    metrics = optimize(config)
  File "/usr/local/lib/python3.6/dist-packages/pot-1.0-py3.6.egg/app/run.py", line 106, in optimize
    model = load_model(config.model)
  File "/usr/local/lib/python3.6/dist-packages/pot-1.0-py3.6.egg/compression/graph/model_utils.py", line 25, in load_model
    return NXModelWrapper(config=model_config)
  File "/usr/local/lib/python3.6/dist-packages/pot-1.0-py3.6.egg/compression/graph/nx_wrapper.py", line 50, in __init__
    self._from_config(kwargs['config'])
  File "/usr/local/lib/python3.6/dist-packages/pot-1.0-py3.6.egg/compression/graph/nx_wrapper.py", line 65, in _from_config
    self._models.append({'model': load_graph(model_config)})
  File "/usr/local/lib/python3.6/dist-packages/pot-1.0-py3.6.egg/compression/graph/graph_utils.py", line 41, in load_graph
    graph_from_ir, meta_data = stdout_redirect(restore_graph_from_ir, xml_path, bin_path)
  File "/usr/local/lib/python3.6/dist-packages/pot-1.0-py3.6.egg/compression/utils/logger.py", line 114, in stdout_redirect
    res = fn(*args, **kwargs)
  File "/openvinomaster/openvinotool/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/utils/ir_reader/restore_graph.py", line 51, in restore_graph_from_ir
    new_graph = copy_graph_with_ops(ir.graph)
  File "/openvinomaster/openvinotool/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/utils/ir_reader/layer_to_class.py", line 333, in copy_graph_with_ops
    new_graph.clean_up()
  File "/openvinomaster/openvinotool/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/graph/graph.py", line 985, in clean_up
    shape_inference(self)
  File "/openvinomaster/openvinotool/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/middle/passes/eliminate.py", line 169, in shape_inference
    node.infer(node)
  File "/openvinomaster/openvinotool/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/ops/strided_slice.py", line 95, in infer
    tf_strided_slice_infer(node)
  File "/openvinomaster/openvinotool/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/front/common/partial_infer/slice.py", line 112, in tf_strided_slice_infer
    data_type_str = 'int64' if node.graph.graph['cmd_params'].generate_experimental_IR_V10 else 'int32'
**AttributeError: 'Namespace' object has no attribute 'generate_experimental_IR_V10'`**

**Comment by lazarevevgeny** [comment]
@whatisor , we have removed the command line parameter 'generate_experimental_IR_V10' after the 2020.4 release. But I see that you use 2020.4 release of OpenVINO MO and I am confused. Did you modify some MO files manually?

**Comment by whatisor** [comment]
@lazarevevgeny  I am using openvino-master source and compile it to support 5 input for CPU ( successfully).
However I do not find /deployment_tools/tools/post_training_optimization_toolkit from this compilation. So I try to reuse tools from openvino_2020.4.287 then gettting above issue.
Where do you store post_training_optimization_toolkit  in master branch?

**Comment by lazarevevgeny** [comment]
@AlexKoff88 , is POT available on github?

**Comment by AlexKoff88** [comment]
No. It is not open-sourced and distributed under Intel proprietary license.

**Comment by whatisor** [comment]
in that case, I cannot use your latest source with old POT?
