### ISSUE TITLE
[TensorFlow Frontend] Internal error

### ISSUE THREAD

**Issue by vidithirve** [openvinotoolkit/openvino#18249]
Hello,

I am trying to convert a TensorFlow model using

`C:\Handwritten_OCR\SimpleHTR-master\SimpleHTR-master\model>mo --input_meta_graph snapshot-13.meta`

but I am getting the following error as an output:

```
[libprotobuf ERROR C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\thirdparty\protobuf\protobuf\src\google\protobuf\wire_format_lite.cc:618] String field 'tensorflow.NodeDef.op' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Check 'is_conversion_successful' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\frontends\tensorflow\src\frontend.cpp:263:
FrontEnd API failed with OpConversionFailure: :
[TensorFlow Frontend] Internal error, conversion is failed for CTCLoss operation with a message:
Check 'shape_rank.compatible(1)' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\core\shape_inference\include\slice_shape_inference.hpp:70:
While validating node 'opset8::Slice Slice_60676 (ShapeOf_60672[0]:i64[3], Constant_60675[0]:i64[], Constant_60674[0]:i64[], Constant_60673[0]:i64[]) -> (dynamic[...])' with friendly_name 'Slice_60676':
Slice `start` input must be a 1D tensor. Got rank: 0

[TensorFlow Frontend] Internal error, conversion is failed for Conv2DBackpropInput operation with a message:
Accessing out-of-range dimension in Dimension[]
[TensorFlow Frontend] Internal error, no translator found for operation(s): AssignSubVariableOp, BiasAddGrad, BroadcastGradientArgs, ConcatOffset, Conv2DBackpropFilter, FusedBatchNormGradV3, InvertPermutation, MaxPoolGrad, OptionalFromValue, OptionalGetValue, ReluGrad, ResourceApplyAdam, ShapeN, SigmoidGrad, TanhGrad, TensorListPopBack

[ ERROR ]  Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\openvino\tools\mo\convert_impl.py", line 915, in _convert
    ov_model, legacy_path = driver(argv, {"conversion_parameters": non_default_params})
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\openvino\tools\mo\convert_impl.py", line 591, in driver
    graph, ngraph_function = prepare_ir(argv)
                             ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\openvino\tools\mo\convert_impl.py", line 404, in prepare_ir
    ngraph_function = moc_pipeline(argv, moc_front_end)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\openvino\tools\mo\moc_frontend\pipeline.py", line 266, in moc_pipeline
    ov_model = moc_front_end.convert(input_model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openvino._pyopenvino.OpConversionFailure: Check 'is_conversion_successful' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\frontends\tensorflow\src\frontend.cpp:263:
FrontEnd API failed with OpConversionFailure: :
[TensorFlow Frontend] Internal error, conversion is failed for CTCLoss operation with a message:
Check 'shape_rank.compatible(1)' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\core\shape_inference\include\slice_shape_inference.hpp:70:
While validating node 'opset8::Slice Slice_60676 (ShapeOf_60672[0]:i64[3], Constant_60675[0]:i64[], Constant_60674[0]:i64[], Constant_60673[0]:i64[]) -> (dynamic[...])' with friendly_name 'Slice_60676':
Slice `start` input must be a 1D tensor. Got rank: 0

[TensorFlow Frontend] Internal error, conversion is failed for Conv2DBackpropInput operation with a message:
Accessing out-of-range dimension in Dimension[]
[TensorFlow Frontend] Internal error, no translator found for operation(s): AssignSubVariableOp, BiasAddGrad, BroadcastGradientArgs, ConcatOffset, Conv2DBackpropFilter, FusedBatchNormGradV3, InvertPermutation, MaxPoolGrad, OptionalFromValue, OptionalGetValue, ReluGrad, ResourceApplyAdam, ShapeN, SigmoidGrad, TanhGrad, TensorListPopBack


[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------
[ INFO ] You can also try to use legacy TensorFlow Frontend by using argument --use_legacy_frontend.
```

I am unable to find a solution for this. I would really appreciate some help on this.

**Comment by rkazants** [comment]
Hi @vidithirve,

You have two types of the problem:
1. problem in translator of CTCLoss operation
2. no translators for AssignSubVariableOp, BiasAddGrad, BroadcastGradientArgs, ConcatOffset, Conv2DBackpropFilter, FusedBatchNormGradV3, ...

You can solve the first problem by using 2023.0 official release where it includes the fix on March: https://github.com/openvinotoolkit/openvino/pull/16380
As for the second type of the problem, you need to explicitly to specify outputs of your models by cutting training parts of the model. That is because I see not translated operations like `BiasAddGrad, BroadcastGradientArgs`. Please open-up your model in Netron or TensorFlow and identity outputs you needed for inference.

Best regards,
Roman

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.
