### ISSUE TITLE
cv2 module is required when import openvino.tools.pot

### ISSUE THREAD

**Issue by nai-kon** [openvinotoolkit/openvino#18519]
`import openvino.tools.pot` requires unnecessary cv2 module.
I wanna quantize a transformer model, which does not need opencv, using OpenVINO POT.
I found `tools/accuracy_checker/representation/segmentation_representation.py`  refers cv2 at the top level of the source, but a transformer model does not need it.

This time I installed opencv for it, but I didn't wanna install unnecessary modules in reality. 
So please don't do "import cv2" at the top level of source, but import it inside a function to minimize scope.
I hope this will be fixed in next version.

# Version
* openvino-dev 2023.0.1

# The Error
```python
>>> import openvino.tools.pot

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.local/lib/python3.10/site-packages/openvino/tools/pot/__init__.py", line 4, in <module>
    from .algorithms.quantization.accuracy_aware.algorithm import AccuracyAwareQuantization
  File "/home/.local/lib/python3.10/site-packages/openvino/tools/pot/algorithms/quantization/accuracy_aware/algorithm.py", line 4, in <module>
    from ...algorithm import Algorithm
  File "/home/.local/lib/python3.10/site-packages/openvino/tools/pot/algorithms/algorithm.py", line 8, in <module>
    from ..api.engine import Engine
  File "/home/.local/lib/python3.10/site-packages/openvino/tools/pot/api/__init__.py", line 5, in <module>
    from .engine import Engine
  File "/home/.local/lib/python3.10/site-packages/openvino/tools/pot/api/engine.py", line 7, in <module>
    from ..statistics.statistic_graph_builder import StatisticGraphBuilder
  File "/home/.local/lib/python3.10/site-packages/openvino/tools/pot/statistics/statistic_graph_builder.py", line 18, in <module>
    from ..graph.model_utils import get_node_by_name
  File "/home/.local/lib/python3.10/site-packages/openvino/tools/pot/graph/__init__.py", line 4, in <module>
    from openvino.tools.pot.graph.model_utils import load_model, save_model
  File "/home/.local/lib/python3.10/site-packages/openvino/tools/pot/graph/model_utils.py", line 10, in <module>
    from .nx_model import CompressedModel
  File "/home/.local/lib/python3.10/site-packages/openvino/tools/pot/graph/nx_model.py", line 10, in <module>
    from openvino.tools.pot.graph.graph_utils import load_graph, save_graph
  File "/home/.local/lib/python3.10/site-packages/openvino/tools/pot/graph/graph_utils.py", line 17, in <module>
    from ..configs.config import GNA_DEVICES
  File "/home/.local/lib/python3.10/site-packages/openvino/tools/pot/configs/config.py", line 11, in <module>
    from ..utils.ac_imports import ConfigReader
  File "/home/.local/lib/python3.10/site-packages/openvino/tools/pot/utils/ac_imports.py", line 15, in <module>
    from openvino.tools.accuracy_checker.evaluators.quantization_model_evaluator import create_model_evaluator
  File "/home/.local/lib/python3.10/site-packages/openvino/tools/accuracy_checker/evaluators/__init__.py", line 17, in <module>
    from .model_evaluator import ModelEvaluator
  File "/home/.local/lib/python3.10/site-packages/openvino/tools/accuracy_checker/evaluators/model_evaluator.py", line 24, in <module>
    from ..dataset import Dataset
  File "/home/.local/lib/python3.10/site-packages/openvino/tools/accuracy_checker/dataset.py", line 25, in <module>
    from .annotation_converters import (
  File "/home/.local/lib/python3.10/site-packages/openvino/tools/accuracy_checker/annotation_converters/__init__.py", line 18, in <module>
    from .convert import make_subset, save_annotation, analyze_dataset, DatasetConversionInfo
  File "/home/.local/lib/python3.10/site-packages/openvino/tools/accuracy_checker/annotation_converters/convert.py", line 31, in <module>
    from ..representation import (
  File "/home/.local/lib/python3.10/site-packages/openvino/tools/accuracy_checker/representation/__init__.py", line 41, in <module>
    from .segmentation_representation import (
  File "/home/.local/lib/python3.10/site-packages/openvino/tools/accuracy_checker/representation/segmentation_representation.py", line 22, in <module>
    import cv2 as cv
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

**Comment by alexsu52** [comment]
@KodiaqQ, please, take a look.

**Comment by KodiaqQ** [comment]
Hi, @nai-kon.
The `opencv-python` module is required for `POT` at least for the pipeline with the custom engine (non-accuracy checker).
As you found, the other `opencv-python` requirement states in `tools/accuracy_checker/representation/segmentation_representation.py`. This is not the `POT` part, but the `Accuracy Checker` (the tool of `OMZ` - https://github.com/openvinotoolkit/open_model_zoo/) that is also required for `POT` as a submodule.
So, it's not really possible to remove the `opencv-python` module from POT, based on model type.
cc @AlexKoff88

**Comment by nai-kon** [comment]
Now I understand it. Thank you for the answer.  Close the issue.
