### ISSUE TITLE
[Download a Trained Model problem][connection error]

### ISSUE THREAD

**Issue by Fly-Key** [openvinotoolkit/openvino#1884]
#### System information (version)

- OpenVINO=> :  2020.4
- Operating System / Platform => : CentOS Linux release 7.8.2003 (Core)
- Compiler => : g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
- Problem classification => : Download a Trained Model problem

#### Detailed description && Steps to reproduce

When I prepareing a Model for Sample Inference, I Installed the [prerequisites](https://github.com/opencv/open_model_zoo/tree/master/tools/downloader#prerequisites). After that, I run:

`./downloader.py --name squeezenet1.1 --output_dir /home/qdl/qdl/public_models`  

and got the following error:

```
[root@asc01 downloader]# ./downloader.py --name squeezenet1.1 --output_dir /home/qdl/qdl/public_models

################|| Downloading models ||################

========== Downloading /home/qdl/qdl/public_models/public/squeezenet1.1/squeezenet1.1.prototxt
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/root/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/root/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/root/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/root/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/root/.local/lib/python3.6/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/root/.local/lib/python3.6/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f546cd58940>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/root/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/root/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /forresti/SqueezeNet/a47b6f13d30985279789d08053d37013d67d131b/SqueezeNet_v1.1/deploy.prototxt (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f546cd58940>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred: 

Traceback (most recent call last):
  File "./downloader.py", line 83, in try_download
    chunk_iterable, continue_offset = start_download(offset=progress.size)
  File "/home/qdl/qdl/open_model_zoo/tools/downloader/common.py", line 298, in start_download
    response = session.get(self.url, stream=True, timeout=DOWNLOAD_TIMEOUT, headers=headers)
  File "/root/.local/lib/python3.6/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.local/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /forresti/SqueezeNet/a47b6f13d30985279789d08053d37013d67d131b/SqueezeNet_v1.1/deploy.prototxt (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f546cd58940>: Failed to establish a new connection: [Errno 111] Connection refused',))
########## Error: Download failed
```

This seems to be the reason for the network connection ? Am I being treated as a robot?.  I would like to know how to solve this problem, or how to download the Trained Model manually.

Thank you in advance !

**Comment by Fly-Key** [comment]
Hi @jgespino,
As you said, my network was blocked. I added some configurations to the /etc/hosts file and successfully solved the problem. Thank you again.

**Comment by shijialee** [comment]
works by adding  `151.101.76.133    raw.githubusercontent.com` to `/etc/hosts`
