### ISSUE TITLE
[Good First Issue]: Expose Model.get_output_size() method to Node.js API

### ISSUE THREAD

**Issue by almilosz** [openvinotoolkit/openvino#23567]
### Context

Node.js API is the newest binding of OpenVINO.
The task is to expose Model.get_output_size() method.
[C++ API](https://docs.openvino.ai/2022.3/classov_1_1Model.html#doxid-classov-1-1-model-1a495378df3029c9b36522bbb16f9287cc) and [Python API](https://docs.openvino.ai/2022.3/api/ie_python_api/_autosummary/openvino.runtime.Model.html#openvino.runtime.Model.get_output_size) documentation of this method

### What needs to be done?

 - add `get_output_size()` method on C++ side (src/bindings/js/node/src/model.cpp)
 - update TypeScript definition (src/bindings/js/node/lib/addon.ts)
 - create unit test for added functionality using Node.js Test Runner
 
 Note: Remember about parameter validation

### Example Pull Requests

Here is the link to a PR with a very similar task that covers the steps listed above:
- https://github.com/openvinotoolkit/openvino/pull/22100

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Node.js API Reference](https://docs.openvino.ai/2024/api/nodejs_api/addon.html)
- [Node.js bindings examples of usage](https://github.com/nodejs/node-addon-examples)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

@almilosz @vishniakov-nikolai

**Comment by almilosz** [comment]
@Huanli-Gong you can take this task as the [Prerequisite task](https://github.com/openvinotoolkit/openvino/wiki/Google-Summer-Of-Code#prerequisite-task) or select one of the tasks listed under "good first issues" on [this page](https://github.com/orgs/openvinotoolkit/projects/3).

**Comment by Huanli-Gong** [comment]
.take

**Comment by DaBaoDIY** [comment]
#WLB#+ .take

**Comment by Huanli-Gong** [comment]
I want to ask some questions about this task, who should I talk to? (I tried to join Discord but found the invite expired)

**Comment by mlukasze** [comment]
> I want to ask some questions about this task, who should I talk to? (I tried to join Discord but found the invite expired)

@almilosz is your best contact point  :)

**Comment by almilosz** [comment]
Here's the link to [Discord](https://discord.gg/gTNQWUwt) but you can always ask questions here

**Comment by Huanli-Gong** [comment]
Thanks! But it still shows the Discord invite expired :(  My questions are: 
1. I didn't find src/bindings/js/node/src/model.cpp, does it mean src/bindings/js/node/src/model_wrap.cpp? 
2. How do I run unit tests for it to check if my code is valid?

**Comment by almilosz** [comment]
1. Yes
1.  `npm run test`. To test the functionality you just added you have to create new unit tests

**Comment by Huanli-Gong** [comment]
I ran npm run test in src/bindings/js/node/, and found not all existing tests are passed. Is there any build step that needs to be run first? Or is it ok to not pass all the tests?

**Comment by vishniakov-nikolai** [comment]
> I ran npm run test in src/bindings/js/node/, and found not all existing tests are passed. Is there any build step that needs to be run first? Or is it ok to not pass all the tests?

Hi @Huanli-Gong! If you faced failed tests in the master code, please, provide more info (which tests are failed, your system configuration, commands how you built bindings, etc)

**Comment by Huanli-Gong** [comment]
@vishniakov-nikolai @almilosz I ran 2 commands (in src/bindings/js/node/): 
```
npm install
npm run test
```
I found that some newly added functions were not declared successfully causing the test to fail. For example, if I ran ```
npx jest tests/model.test.js
``` I will get:
```
▶ Node.js Model.isDynamic()
  ✖ should return a boolean value indicating if the model is dynamic (0.5368ms)
    TypeError: model.isDynamic is not a function
        at TestContext.<anonymous> (F:\IDS 721 Data Analysis at Scale in Cloud\openvino\src\bindings\js\node\tests\model.test.js:21:26)
        at Test.runInAsyncScope (node:async_hooks:203:9)
        at Test.run (node:internal/test_runner/test:631:25)
        at Test.start (node:internal/test_runner/test:542:17)
        at node:internal/test_runner/test:946:71
        at node:internal/per_context/primordials:487:82
        at new Promise (<anonymous>)
        at new SafePromise (node:internal/per_context/primordials:455:29)
        at node:internal/per_context/primordials:487:9
        at Array.map (<anonymous>)
        at arrayToSafePromiseIterable (node:internal/per_context/primordials:484:5)
        at node:internal/per_context/primordials:501:21
        at new Promise (<anonymous>)
        at primordials.SafePromiseAll (node:internal/per_context/primordials:500:3)
        at Suite.run (node:internal/test_runner/test:946:23)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at startSubtest (node:internal/test_runner/harness:214:3)

  ✖ should not accept any arguments (1.5006ms)
    AssertionError [ERR_ASSERTION]: Expected isDynamic to throw an error when called with arguments
        at TestContext.throws (F:\IDS 721 Data Analysis at Scale in Cloud\openvino\src\bindings\js\node\tests\model.test.js:21:12)
        at Test.runInAsyncScope (node:async_hooks:203:9)
        at Test.run (node:internal/test_runner/test:631:25)
        at Suite.processPendingSubtests (node:internal/test_runner/test:374:18)
        at Test.postRun (node:internal/test_runner/test:715:19)
        at Test.run (node:internal/test_runner/test:673:12)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 0)
        at Suite.run (node:internal/test_runner/test:948:7)
        at startSubtest (node:internal/test_runner/harness:214:3) {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: TypeError: model.isDynamic is not a function
          at F:\IDS 721 Data Analysis at Scale in Cloud\openvino\src\bindings\js\node\tests\model.test.js:26:13
          at getActual (node:assert:756:5)
          at Function.throws (node:assert:902:24)
          at TestContext.<anonymous> (F:\IDS 721 Data Analysis at Scale in Cloud\openvino\src\bindings\js\node\tests\model.test.js:25:12)
          at Test.runInAsyncScope (node:async_hooks:203:9)
          at Test.run (node:internal/test_runner/test:631:25)
          at Suite.processPendingSubtests (node:internal/test_runner/test:374:18)
          at Test.postRun (node:internal/test_runner/test:715:19)
          at Test.run (node:internal/test_runner/test:673:12)
          at processTicksAndRejections (node:internal/process/task_queues:95:5)
          at async Promise.all (index 0)
          at Suite.run (node:internal/test_runner/test:948:7)
          at startSubtest (node:internal/test_runner/harness:214:3),
      expected: /^Error: isDynamic\(\) does not accept any arguments\.$/,
      operator: 'throws'
    }

  ✖ returns false for a static model (0.1236ms)
    TypeError: model.isDynamic is not a function
        at TestContext.<anonymous> (F:\IDS 721 Data Analysis at Scale in Cloud\openvino\src\bindings\js\node\tests\model.test.js:31:30)
        at Test.runInAsyncScope (node:async_hooks:203:9)
        at Test.run (node:internal/test_runner/test:631:25)
        at Suite.processPendingSubtests (node:internal/test_runner/test:374:18)
        at Test.postRun (node:internal/test_runner/test:715:19)
        at Test.run (node:internal/test_runner/test:673:12)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at Suite.processPendingSubtests (node:internal/test_runner/test:374:7)
``` 
but if I change ``` isDynamic``` to ``` getName``` in tests/model.test.js, it will not say model.getName is not a function. Is there any step needs to be run first to build model?

**Comment by vishniakov-nikolai** [comment]
@Huanli-Gong, looks like you didn't run rebuild after pulling latest changes. You have to rebuild and install binaries again, following this guide: https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/js/docs/README.md#openvino-node-package-developer-documentation
