### ISSUE TITLE
[Good First Issue][Python API]: Create constant for string tensor and fix segfault

### ISSUE THREAD

**Issue by rkazants** [openvinotoolkit/openvino#23611]
### Context

Currently, we receive segfault during creation of string type constant:

```
import openvino.runtime.opset14 as ov
import numpy as np
str_const = ov.constant(np.array(['openvino'], dtype=str))
```

For reproducing, you can install latest nightly build:

```
pip install openvino-nightly
```

### What needs to be done?

Implement this feature

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers
- [How to link your Pull Request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar)

### Contact points

- @jiwaszki
- @p-wysocki 
- @mlukasze
- @akuporos  
- @rkazants

**Comment by dante-hl** [comment]
Was wondering if I could take this towards the GSoC prerequisite.

**Comment by rkazants** [comment]
> Was wondering if I could take this towards the GSoC prerequisite.

Hi @dante-hl, ask this question in discussions in a thread dedicated project idea. What project idea are you going to apply to?

Best regards,
Roman

**Comment by dante-hl** [comment]
Oh, sorry about that - I was thinking of applying to one of the two:
Project 10: Accelerating PyTorch Lightning and ComfyUI with torch.compile OpenVINO
Project 11: PyTorch Model Optimizations with torch.compile OpenVINO Backend

Regardless, I'll make a discussion post specifically for this right away - sorry about the inconvenience!

**Comment by awayzjj** [comment]
.take

**Comment by awayzjj** [comment]
@rkazants Hi, I have several questions.
1. Which branch corresponds to the openvino-nightly build? When I tested using the test script you provided on the latest master branch, I encountered a MemoryError: std::bad_alloc error. Should I make modifications directly on the master branch? I have already attempted some modifications based on the master branch.

2.The error traceback is as follows:
https://github.com/openvinotoolkit/openvino/blob/c3c409ee133ffb26bf8fd5570ef50a7c004839a4/src/bindings/python/src/pyopenvino/pyopenvino.cpp#L234
https://github.com/openvinotoolkit/openvino/blob/c3c409ee133ffb26bf8fd5570ef50a7c004839a4/src/bindings/python/src/pyopenvino/graph/ops/constant.cpp#L104-L114
https://github.com/openvinotoolkit/openvino/blob/c3c409ee133ffb26bf8fd5570ef50a7c004839a4/src/bindings/python/src/pyopenvino/core/common.hpp#L100-L105
https://github.com/openvinotoolkit/openvino/blob/c3c409ee133ffb26bf8fd5570ef50a7c004839a4/src/bindings/python/src/pyopenvino/core/common.cpp#L286-L301
https://github.com/openvinotoolkit/openvino/blob/c3c409ee133ffb26bf8fd5570ef50a7c004839a4/src/core/src/op/constant.cpp#L131-L140
The line `std::uninitialized_copy_n(src_strings, num_elements, dst_strings);` ultimately caused the error.

3.As shown in the code snippet below, I have added some print statements and attempted different approaches:

```
Constant::Constant(const element::Type& type, const Shape& shape, const void* data) : Constant(false, type, shape) {
    if (m_element_type == ov::element::string) {
        auto num_elements = shape_size(m_shape); // 1
        const std::string* src_strings = static_cast<const std::string*>(data);
        const char* src_ptr = reinterpret_cast<const char*>(src_strings);
        printf("src_string: %c|%c|%c|%c|%c\n", *src_ptr, *(src_ptr+1), *(src_ptr+2), *(src_ptr+3), *(src_ptr+4));

        std::string* dst_strings = static_cast<std::string*>(get_data_ptr_nc());
        char* dst_ptr = reinterpret_cast<char*>(dst_strings);
        printf("dst_string: %c|%c|%c|%c|%c\n", *dst_ptr, *(dst_ptr+1), *(dst_ptr+2), *(dst_ptr+3), *(dst_ptr+4));

        std::uninitialized_copy_n(src_strings, num_elements, dst_strings); // case 0: MemoryError: std::bad_alloc
        //std::uninitialized_fill_n(dst_strings, num_elements, std::string()); // case 1: no core, reached copy ctor
        //std::memcpy(get_data_ptr_nc(), data, mem_size()); // case 2: copied src_string to dst_string, reached copy ctor
        *dst_ptr = 'x'; // case 3: 
        printf("modified dst_string: %c|%c|%c|%c|%c\n", *dst_ptr, *(dst_ptr+1), *(dst_ptr+2), *(dst_ptr+3), *(dst_ptr+4));
    } else {
        std::memcpy(get_data_ptr_nc(), data, mem_size());
    }
}

Constant::Constant(const Constant& other)
    : m_element_type{other.m_element_type},
      m_shape{other.m_shape},
      m_data{other.m_data},
      m_all_elements_bitwise_identical{other.m_all_elements_bitwise_identical.load()},
      m_all_elements_bitwise_identical_checked{other.m_all_elements_bitwise_identical_checked.load()} {
    std::cout << "in copy ctor" << std::endl;
    constructor_validate_and_infer_types();
}
```
case 0: No modification, error occurs  
```
src_string: o||||p
dst_string: ;||Z||
Traceback (most recent call last):
  File "/home/ubuntu/dev/openvino/build/bug.py", line 8, in <module>
    str_const = ov.constant(np.array(['openvion'], dtype=str))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/openvino/runtime/utils/decorators.py", line 24, in wrapper
    node = node_factory_function(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/openvino/runtime/opset13/ops.py", line 337, in constant
    return Constant(_value, shared_memory=_shared_memory)
MemoryError: std::bad_alloc
```
case 1: Initialization is done, exit normally.  
```
src_string: o||||p
dst_string: ]||||
modified dst_string: ||D||
in copy ctor
```
case 2: Similar to the else branch, src_string copy is successful, but segfault occurs later  
```
src_string: o||||p
dst_string: U|S|||*
modified dst_string: o||||p
in copy ctor
Segmentation fault (core dumped)
```
case 3: Direct modification first character of dst_string, segfault occurs
```
src_string: o||||p
dst_string: |||
modified dst_string: x|||
in copy ctor
Segmentation fault (core dumped)
```

Could you please provide me with some debugging tips or any other suggestions? Thank you.

**Comment by p-wysocki** [comment]
cc @rkazants

**Comment by awayzjj** [comment]
@rkazants Hi, could you please provide me with some debugging tips or any other suggestions? :)

**Comment by amkarn258** [comment]
.take

**Comment by mlukasze** [comment]
hey @amkarn258 any help needed?

**Comment by torabshaikh** [comment]
Hey @amkarn258 , I am interested in solving this issue. Can you please assign this to me and tell me about how I can set up environment for this?

**Comment by torabshaikh** [comment]
.take

**Comment by p-wysocki** [comment]
Since @torabshaikh hasn't been active since December 6th, I think it's safe to assume they're not working on the task anymore. You've been assigned @darksapien23151, please let us know if you have any questions. :)

**Comment by torabshaikh** [comment]
Hi @darksapien23151 , I was able to reproduce the issue and I was looking at the codebase to understand it. But then I got busy with some medical related issues. I just got free and I had started working on it again. But if you want to work on it, go ahead.
@p-wysocki I can get work on some other issue. Please let me know if you have any other issue for me.

**Comment by p-wysocki** [comment]
Hello @torabshaikh, thanks for letting us know, I hope you're okay now. You can just choose any open issue from the board, we'll answer any questions you may have.

**Comment by aman-singhsm01** [comment]
.take (can i work on this issue)

**Comment by RaghavYadav04** [comment]
@mlukasze just a quick one, how am i supposed to set the environment for this issue? lil confused on that

**Comment by mlukasze** [comment]
@almilosz will guide you :)

**Comment by RaghavYadav04** [comment]
@almilosz could you help me get started with this issue, I had some questions...

**Comment by RaghavYad04** [comment]
@p-wysocki, would appreciate it if you could reassign this issue to me, my old account got suspended.
Thanks

**Comment by Raghavyadav17** [comment]
hi @p-wysocki, pls assign this issue to me, due to my old account being suspended
Thanks :)

**Comment by vijaykr338** [comment]
@p-wysocki please assign this to me

**Comment by vijaykr338** [comment]
.take

**Comment by Raghavyadav17** [comment]
> [@p-wysocki](https://github.com/p-wysocki) please assign this to me

buddy i am already working on this issue !!!

**Comment by Raghavyadav17** [comment]
@rkazants Hi Roman, hope you're doing well, if possible could you please assign this issue to this account of mine, due to my old account being suspended. Would really appreciate it, thanks!!

**Comment by Raghavyadav17** [comment]
@mlukasze could you please assign this issue to me on this account ? my old account got deactivated 
Thanks!!

**Comment by Raghavyadav17** [comment]
@rkazants Would really appreciate it if you could assign this issue to me.

**Comment by p-wysocki** [comment]
The issue has been assigned to you @Raghavyadav17

**Comment by Raghavyadav17** [comment]
@p-wysocki rlly appreciate it, will create a PR for this issue v.soon

**Comment by p-wysocki** [comment]
Reopening the issue due to inactivity.

**Comment by gamidirohan** [comment]
Was wondering if I could take this towards the GSoC prerequisite? I plan on applying for the "OpenVINO Messenger AI-Assistant for an AI PC" project. I've started wokring on the project already (https://github.com/gamidirohan/OpenVINO-Messenger-AI-Assistant-for-an-AI-PC.git).

**Comment by Raghavyadav17** [comment]
.take

**Comment by p-wysocki** [comment]
Hello @Raghavyadav17, you've just been unassigned from this issue due to inactivity. Please finish your other commitments before picking up this issue. I'm assigning @gamidirohan.

**Comment by gamidirohan** [comment]
@p-wysocki Thank you so much for assigning this to me, is there anything else I'm supposed to know or any references I could refer to before I get into this?

**Comment by mahimairaja** [comment]
Hey @mlukasze is this issue stale?

**Comment by tarunmehrda** [comment]
.take

**Comment by Barospooky** [comment]
.take

**Comment by Mrunalpatil100** [comment]
.take

**Comment by vishalharkal15** [comment]
.Take

**Comment by dibyajyoti-mandal** [comment]
.take

**Comment by om4rrr** [comment]
.take

**Comment by amishijain123** [comment]
.take

**Comment by KarSri7694** [comment]
.take

**Comment by vishalharkal15** [comment]
.take

**Comment by muhammad-wei** [comment]
.take

**Comment by muhammad-wei** [comment]
.take

**Comment by tani125** [comment]
.take

**Comment by SaumyaTiwari108** [comment]
.take
wish to work on it if it's available

**Comment by Abh-igyan** [comment]
.take

**Comment by Abh-igyan** [comment]
@rkazants
