### ISSUE TITLE
IndexError: index -1 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by larrydemons** [openvinotoolkit/openvino#283]
The model i used is trained by Pixel_Link, and the command i used to optimizer model is
`python3 mo_tf.py --input_model /Users/myang/oss_model/detectforinvoice.pb --output_dir /Users/myang/oss_model --log_level=DEBUG --reverse_input_channels --input_shape '[1280,1280,3]'`

and it will raise an error ` 2019-10-11 18:49:23,559 ] [ DEBUG ] [ class_registration:267 ]  Run replacer <class 'extensions.middle.EltwiseInputReshape.Eltwise1DInputReshape'>
[ 2019-10-11 18:49:23,569 ] [ DEBUG ] [ class_registration:267 ]  Run replacer <class 'extensions.middle.EltwiseChecker.EltwiseChecker'>
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID (<class 'extensions.middle.EltwiseChecker.EltwiseChecker'>)": index -1 is out of bounds for axis 0 with size 0
[ ERROR ]  Traceback (most recent call last):
  File "/opt/intel/openvino_2019.2.275/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 273, in apply_replacements
    for_graph_and_each_sub_graph_recursively(graph, replacer.find_and_replace_pattern)
  File "/opt/intel/openvino_2019.2.275/deployment_tools/model_optimizer/mo/middle/pattern_match.py", line 58, in for_graph_and_each_sub_graph_recursively
    func(graph)
  File "/opt/intel/openvino_2019.2.275/deployment_tools/model_optimizer/extensions/middle/EltwiseChecker.py", line 72, in find_and_replace_pattern
    np.put(possible_shape, feature_dim, tensor_shape.item(feature_dim))
IndexError: index -1 is out of bounds for axis 0 with size 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/intel/openvino_2019.2.275/deployment_tools/model_optimizer/mo/main.py", line 302, in main
    return driver(argv)
  File "/opt/intel/openvino_2019.2.275/deployment_tools/model_optimizer/mo/main.py", line 251, in driver
    is_binary=not argv.input_model_is_text)
  File "/opt/intel/openvino_2019.2.275/deployment_tools/model_optimizer/mo/pipeline/tf.py", line 134, in tf2nx
    class_registration.apply_replacements(graph, class_registration.ClassType.MIDDLE_REPLACER)
  File "/opt/intel/openvino_2019.2.275/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 299, in apply_replacements
    )) from err
Exception: Exception occurred during running replacer "REPLACEMENT_ID (<class 'extensions.middle.EltwiseChecker.EltwiseChecker'>)": index -1 is out of bounds for axis 0 with size 0

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------`

and if i use `python3 mo_tf.py --input_model /Users/myang/oss_model/detectforinvoice.pb --output_dir /Users/myang/oss_model --log_level=DEBUG --reverse_input_channels --input_shape '[1280,1280,3]' --tensorflow_operation_patterns All,Assert`

the error will be `[ INFO ]  Running nodes with operation using pattern 'Assert'
[ 2019-10-11 19:00:25,981 ] [ DEBUG ] [ custom_subgraph_call:70 ]  Node 'evaluation_1280x1280/ssd_preprocessing_train/per_image_standardization/assert_positive/assert_less/Assert/Assert' operation matches pattern 'Assert'
[ INFO ]  Create new node with name 'TFSubgraphCall_286' for nodes 'evaluation_1280x1280/ssd_preprocessing_train/per_image_standardization/assert_positive/assert_less/Assert/Assert'
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID (<class 'extensions.front.tf.tensorflow_patterns.TensorflowOperationPatterns'>)": Attempt to connect evaluation_1280x1280/ssd_preprocessing_train/per_image_standardization/assert_positive/assert_less/Assert/Assert/data_0 to TFSubgraphCall_286. Missing in port (0) in TFSubgraphCall_286 node
[ ERROR ]  Traceback (most recent call last):
  File "/opt/intel/openvino_2019.2.275/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 273, in apply_replacements
    for_graph_and_each_sub_graph_recursively(graph, replacer.find_and_replace_pattern)
  File "/opt/intel/openvino_2019.2.275/deployment_tools/model_optimizer/mo/middle/pattern_match.py", line 58, in for_graph_and_each_sub_graph_recursively
    func(graph)
  File "/opt/intel/openvino_2019.2.275/deployment_tools/model_optimizer/extensions/front/tf/tensorflow_patterns.py", line 51, in find_and_replace_pattern
    csc.offload_operations_to_tf(graph, argv.tensorflow_operation_patterns)
  File "/opt/intel/openvino_2019.2.275/deployment_tools/model_optimizer/mo/front/tf/custom_subgraph_call.py", line 71, in offload_operations_to_tf
    merge_nodes(graph, [node_name])
  File "/opt/intel/openvino_2019.2.275/deployment_tools/model_optimizer/mo/front/tf/custom_subgraph_call.py", line 165, in merge_nodes
    edge_attrs)
  File "/opt/intel/openvino_2019.2.275/deployment_tools/model_optimizer/mo/graph/graph.py", line 518, in add_edge
    assert vnode.has_port('in', in_port, control_flow=is_control_flow), "{} Missing in port ({}) in {} node".format(message, in_port, vnode.name)
AssertionError: Attempt to connect evaluation_1280x1280/ssd_preprocessing_train/per_image_standardization/assert_positive/assert_less/Assert/Assert/data_0 to TFSubgraphCall_286. Missing in port (0) in TFSubgraphCall_286 node

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/intel/openvino_2019.2.275/deployment_tools/model_optimizer/mo/main.py", line 302, in main
    return driver(argv)
  File "/opt/intel/openvino_2019.2.275/deployment_tools/model_optimizer/mo/main.py", line 251, in driver
    is_binary=not argv.input_model_is_text)
  File "/opt/intel/openvino_2019.2.275/deployment_tools/model_optimizer/mo/pipeline/tf.py", line 133, in tf2nx
    class_registration.apply_replacements(graph, class_registration.ClassType.FRONT_REPLACER)
  File "/opt/intel/openvino_2019.2.275/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 299, in apply_replacements
    )) from err
Exception: Exception occurred during running replacer "REPLACEMENT_ID (<class 'extensions.front.tf.tensorflow_patterns.TensorflowOperationPatterns'>)": Attempt to connect evaluation_1280x1280/ssd_preprocessing_train/per_image_standardization/assert_positive/assert_less/Assert/Assert/data_0 to TFSubgraphCall_286. Missing in port (0) in TFSubgraphCall_286 node

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------`

thx

**Comment by larrydemons** [comment]
and if i use 2019_R1.0.1 it gives
`[ 2019-10-12 12:26:16,225 ] [ DEBUG ] [ op:217 ]  Finished running infer function, data nodes attributes: {'kind': 'data', 'precision': 'FP32', 'name': 'bias_data1708', 'value': '[ 0.04467966 -0.04467963]', 'shape': array([2]), 'data_type': None, 'dim_attrs': ['channel_dims', 'spatial_dims', 'axis', 'batch_dims'], 'shape_attrs': ['shape', 'window', 'pad', 'output_shape', 'stride'], '_in_ports': set(), '_out_ports': set(), 'is_output_reachable': True, 'is_undead': False, 'is_const_producer': False}
[ ERROR ]  Can't permute attrs for node EltwiseReshapeNormalization. Error message: only integer scalar arrays can be converted to a scalar index
[ 2019-10-12 12:26:16,317 ] [ DEBUG ] [ main:318 ]  Traceback (most recent call last):
  File "/Users/myang/mygo/src/dldt/model-optimizer/mo/middle/passes/shape.py", line 251, in permute_op_nodes_attrs
    node.permute_attrs.permute_attrs(node)
  File "/Users/myang/mygo/src/dldt/model-optimizer/mo/ops/op.py", line 404, in permute_attrs
    node[name] = func(node, permutation, name)
  File "/Users/myang/mygo/src/dldt/model-optimizer/mo/ops/op.py", line 336, in <lambda>
    common_permutation = lambda node, permutation, attr: node[attr][permutation.perm]
TypeError: only integer scalar arrays can be converted to a scalar index

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/myang/mygo/src/dldt/model-optimizer/mo/main.py", line 312, in main
    return driver(argv)
  File "/Users/myang/mygo/src/dldt/model-optimizer/mo/main.py", line 263, in driver
    is_binary=not argv.input_model_is_text)
  File "/Users/myang/mygo/src/dldt/model-optimizer/mo/pipeline/tf.py", line 213, in tf2nx
    for_graph_and_each_sub_graph_recursively(graph, permute_op_nodes_attrs)
  File "/Users/myang/mygo/src/dldt/model-optimizer/mo/middle/pattern_match.py", line 58, in for_graph_and_each_sub_graph_recursively
    func(graph)
  File "/Users/myang/mygo/src/dldt/model-optimizer/mo/middle/passes/shape.py", line 253, in permute_op_nodes_attrs
    raise Error('Can\'t permute attrs for node {}. Error message: {}'.format(node.id, e))
mo.utils.error.Error: Can't permute attrs for node EltwiseReshapeNormalization. Error message: only integer scalar arrays can be converted to a scalar index`

**Comment by larrydemons** [comment]
this is the output of tensorflow summarize_graph
`Found 1 possible inputs: (name=evaluation_1280x1280/Placeholder, type=int32(3), shape=[?,?,3])
No variables spotted.
Found 2 possible outputs: (name=evaluation_1280x1280/strided_slice_3, op=StridedSlice) (name=evaluation_1280x1280/strided_slice_4, op=StridedSlice)
Found 20525565 (20.52M) const parameters, 0 (0) variable parameters, and 1 control_edges
Op types used: 106 Const, 47 Identity, 23 Conv2D, 23 BiasAdd, 16 Relu, 9 StridedSlice, 6 Reshape, 6 Add, 5 MaxPool, 5 ResizeBilinear, 4 Sub, 4 Shape, 3 Pack, 2 Square, 2 Mean, 2 ExpandDims, 2 Softmax, 2 Slice, 2 ConcatV2, 2 Cast, 1 BatchToSpaceND, 1 Less, 1 Rsqrt, 1 RealDiv, 1 Prod, 1 Placeholder, 1 SpaceToBatchND, 1 Sqrt, 1 Maximum, 1 All, 1 Assert
To use with tensorflow/tools/benchmark:benchmark_model try these arguments:
bazel run tensorflow/tools/benchmark:benchmark_model -- --graph=/Users/myang/Desktop/dl/model/aliyun_model/detectforinvoice.pb --show_flops --input_layer=evaluation_1280x1280/Placeholder --input_layer_type=int32 --input_layer_shape=-1,-1,3 --output_layer=evaluation_1280x1280/strided_slice_3,evaluation_1280x1280/strided_slice_4`

**Comment by shubha-ramani** [comment]
Dear @larrydemons 

When you get such an error from Model Optimizer like 

> np.put(possible_shape, feature_dim, tensor_shape.item(feature_dim))
IndexError: index -1 is out of bounds for axis 0 with size 0

This error is coming from numpy, not even Model Optimizer. My recommendation is to dump your tensorflow frozen pb into a text file and carefully scan the dimensions in your model to see if anything looks strange, particularly -1 values. numpy can deal with -1 in one dimension but Model Optimizer cannot. Model Optimizer requires that every index in dim (N,W,H,C in Tensorflow's case) is a positive value. 

Also both the versions of OpenVino you are testing on are old. We have recently released 2019R3. Please kindly stick with the latest OpenVino versions as newer versions contain bug fixes as well as new features and performance enhancements.

Hope it helps,

Thanks,

Shubha

**Comment by AnastasiaKazantaeva** [comment]
It seems this issue is not actual, closing it. Feel free to create a new one in case of some questions/problems
