### ISSUE TITLE
'Graph' object has no attribute 'node'

### ISSUE THREAD

**Issue by TheLostIn** [openvinotoolkit/openvino#294]
I was transfering caffemodel into .xml,.bin.
`python mo.py --input_model F:/openvino_download/2019_download/object_detection/common/mtcnn/o/caffe/mtcnn-o.caffemodel --input_proto F:/openvino_download/2019_download/object_detection/common/mtcnn/o/caffe/mtcnn-o.prototxt --data_type FP16`
I downloaded the `mtcnn-o.caffemodel` and `mtcnn-o.prototxt` by the command line `python downloader.py --name 'mtcnn-o'`
```
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  'Graph' object has no attribute 'node'
[ ERROR ]  Traceback (most recent call last):
  File "C:\Program Files (x86)\IntelSWTools\openvino_2019.1.148\deployment_tools\model_optimizer\mo\main.py", line 312, in main
    return driver(argv)
  File "C:\Program Files (x86)\IntelSWTools\openvino_2019.1.148\deployment_tools\model_optimizer\mo\main.py", line 272, in driver
    custom_layers_mapping_path=custom_layers_mapping_path)
  File "C:\Program Files (x86)\IntelSWTools\openvino_2019.1.148\deployment_tools\model_optimizer\mo\pipeline\caffe.py", line 59, in driver
    graph, original_shapes = loader.caffe_pb_to_nx(proto, model)
  File "C:\Program Files (x86)\IntelSWTools\openvino_2019.1.148\deployment_tools\model_optimizer\mo\front\caffe\loader.py", line 242, in caffe_pb_to_nx
    kind='op')
  File "C:\Program Files (x86)\IntelSWTools\openvino_2019.1.148\deployment_tools\model_optimizer\mo\graph\graph.py", line 494, in add_node
    node.update_node()
  File "C:\Program Files (x86)\IntelSWTools\openvino_2019.1.148\deployment_tools\model_optimizer\mo\graph\graph.py", line 459, in update_node
    in_ports_count = self.in_ports_count if self.has_valid('in_ports_count') else None
  File "C:\Program Files (x86)\IntelSWTools\openvino_2019.1.148\deployment_tools\model_optimizer\mo\graph\graph.py", line 162, in has_valid
    print('self.graph.node:',self.graph.node)
AttributeError: 'Graph' object has no attribute 'node'
```
I dont't know how to solve this, would somebody help me?

**Comment by benhoff** [comment]
https://github.com/opencv/dldt/issues/289

Looks like `$ pip install networkx==2.3` will resolve.

**Comment by TheLostIn** [comment]
Thanks god,it helped!!!
Thank you very much!

**Comment by r0l1** [comment]
Great thank you! This dependency should be included into the install requirements...

**Comment by KimRasak** [comment]
> #289
> 
> Looks like `$ pip3 install networkx==2.3` will resolve.

That works for me too.

**Comment by lazarevevgeny** [comment]
The issue has been solved on the MO side. Now both `graph.node` and `graph.nodes` will work on any version of the networkX.

**Comment by mkdthanga** [comment]
> #289
> 
> Looks like `$ pip3 install networkx==2.3` will resolve.

worked for me too! Thanks a lot!
