### ISSUE TITLE
[Bug] inconsistent version requirement of numpy for POT

### ISSUE THREAD

**Issue by guoyejun** [openvinotoolkit/openvino#4099]
- OpenVINO => l_openvino_toolkit_p_2021.2.185.tgz
- Operating System / Platform => Ubuntu 18.04

python 3.7 with virtualenv
```
virtualenv -p python3.7 ~/pyenv/ov20212
source ~/pyenv/ov20212/bin/activate
```

##### Detailed description
accuracy_check requires numpy>=1.16.5 while pot requires numpy==1.16.3, following the steps at https://docs.openvinotoolkit.org/latest/pot_configs_examples_README.html

##### Steps to reproduce
```
~/example# accuracy_check -c mobilenet_v2_pytorch.yaml -m ./public/mobilenet-v2-pytorch/FP32/
Traceback (most recent call last):
  File "/root/pyenv/ov20212/lib/python3.7/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/root/pyenv/ov20212/lib/python3.7/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/root/pyenv/ov20212/lib/python3.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (numpy 1.16.3 (/root/pyenv/ov20212/lib/python3.7/site-packages), Requirement.parse('numpy>=1.16.5'), {'scikit-image'})
```

```
~/example# pot -c mobilenet_v2_pytorch_int8.json -e
Traceback (most recent call last):
  File "/root/pyenv/ov20212/lib/python3.7/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/root/pyenv/ov20212/lib/python3.7/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/root/pyenv/ov20212/lib/python3.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (numpy 1.16.5 (/root/pyenv/ov20212/lib/python3.7/site-packages), Requirement.parse('numpy==1.16.3'), {'pot'})
```

**Comment by ilya-lavrenov** [comment]
CC @eaidova @AlexKoff88

**Comment by AlexKoff88** [comment]
@guoyejun, thanks for submitting the issue. In the next release, we are going to have a common requirements file for Python dependencies across all OpenVINO components. This issue is going to be fixed. @mryzhov, this is one of the justifications why we need global requirements.

**Comment by AlexKoff88** [comment]
@guoyejun, can we close this?
