### ISSUE TITLE
[ValueError]  : Can't load save_path when it is None

### ISSUE THREAD

**Issue by waghts95** [openvinotoolkit/openvino#4306]
##### System information (version)
OpenVINO => openvino_2021.2.185
Operating System / Platform => Windows 64 Bit
Compiler => Visual Studio 2017
Problem classification: Model Conversion
Framework: TensorFlow
Model name: efficientdet-d0

First, thank you very much openvino team for your amazing work.
I have trained efficientdet-d0 (tensorflow) model. I am trying to convert it to IR.
My command is :
python converter.py --name efficientdet-d0-tf --output_dir D:\rough\custom_ed_ir --mo D:\intel\openvino_2021.2.185\deployment_tools\model_optimizer\mo.py --download_dir "D:\rough\downloaded_efficientdet-d0-tf - Copy"
download_dir contents are : 
1. checkpoint
2.  model.data-00000-of-00001
3. model.index
4. train   (this is folder)

console output : 

Skipping registering GPU devices...
2021-02-12 10:56:32.717221: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:196] None of the MLIR optimization passes are enabled (registered 0 passes)
WARNING:tensorflow:From D:\env_tensorflow_2\lib\site-packages\tensorflow\python\training\moving_averages.py:458: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
W0212 10:56:35.537713  7564 deprecation.py:339] From D:\env_tensorflow_2\lib\site-packages\tensorflow\python\training\moving_averages.py:458: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
2021-02-12 10:56:59.632946: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at save_restore_v2_ops.cc:205 : Not found: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
WARNING:tensorflow:Restoring an object-based checkpoint using a name-based saver. This may be somewhat fragile, and will re-build the Saver. Instead, consider loading object-based checkpoints using tf.train.Checkpoint().
W0212 10:56:59.984577  7564 saver.py:1319] Restoring an object-based checkpoint using a name-based saver. This may be somewhat fragile, and will re-build the Saver. Instead, consider loading object-based checkpoints using tf.train.Checkpoint().
Traceback (most recent call last):
  File "D:\env_tensorflow_2\lib\site-packages\tensorflow\python\client\session.py", line 1375, in _do_call
    return fn(*args)
  File "D:\env_tensorflow_2\lib\site-packages\tensorflow\python\client\session.py", line 1360, in _run_fn
    target_list, run_metadata)
  File "D:\env_tensorflow_2\lib\site-packages\tensorflow\python\client\session.py", line 1453, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
         [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\env_tensorflow_2\lib\site-packages\tensorflow\python\training\saver.py", line 1298, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "D:\env_tensorflow_2\lib\site-packages\tensorflow\python\client\session.py", line 968, in run
    run_metadata_ptr)
  File "D:\env_tensorflow_2\lib\site-packages\tensorflow\python\client\session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\env_tensorflow_2\lib\site-packages\tensorflow\python\client\session.py", line 1369, in _do_run
    run_metadata)
  File "D:\env_tensorflow_2\lib\site-packages\tensorflow\python\client\session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key box_net/box-0-bn-3/beta/ExponentialMovingAverage not found in checkpoint
         [[node save/RestoreV2 (defined at D:\rough\automl_\efficientdet\inference.py:196) ]]

Original stack trace for 'save/RestoreV2':
  File "model_inspect.py", line 520, in <module>
    app.run(main)
  File "D:\env_tensorflow_2\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "D:\env_tensorflow_2\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 513, in main
    trace_filename=FLAGS.trace_filename)
  File "model_inspect.py", line 462, in run_model
    self.export_saved_model(**config_dict)
  File "model_inspect.py", line 150, in export_saved_model
    driver.build()
  File "D:\rough\automl_\efficientdet\inference.py", line 444, in build
    export_ckpt=None)
  File "D:\rough\automl_\efficientdet\inference.py", line 196, in restore_ckpt
    saver = tf.train.Saver(var_dict, max_to_keep=1)
  File "D:\env_tensorflow_2\lib\site-packages\tensorflow\python\training\saver.py", line 835, in __init__
    self.build()
  File "D:\env_tensorflow_2\lib\site-packages\tensorflow\python\training\saver.py", line 847, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "D:\env_tensorflow_2\lib\site-packages\tensorflow\python\training\saver.py", line 885, in _build
    build_restore=build_restore)
  File "D:\env_tensorflow_2\lib\site-packages\tensorflow\python\training\saver.py", line 515, in _build_internal
    restore_sequentially, reshape)
  File "D:\env_tensorflow_2\lib\site-packages\tensorflow\python\training\saver.py", line 335, in _AddRestoreOps
    restore_sequentially)
  File "D:\env_tensorflow_2\lib\site-packages\tensorflow\python\training\saver.py", line 582, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "D:\env_tensorflow_2\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1510, in restore_v2
    name=name)
  File "D:\env_tensorflow_2\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 750, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "D:\env_tensorflow_2\lib\site-packages\tensorflow\python\framework\ops.py", line 3536, in _create_op_internal
    op_def=op_def)
  File "D:\env_tensorflow_2\lib\site-packages\tensorflow\python\framework\ops.py", line 1990, in __init__
    self._traceback = tf_stack.extract_stack()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model_inspect.py", line 520, in <module>
    app.run(main)
  File "D:\env_tensorflow_2\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "D:\env_tensorflow_2\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_inspect.py", line 513, in main
    trace_filename=FLAGS.trace_filename)
  File "model_inspect.py", line 462, in run_model
    self.export_saved_model(**config_dict)
  File "model_inspect.py", line 150, in export_saved_model
    driver.build()
  File "D:\rough\automl_\efficientdet\inference.py", line 444, in build
    export_ckpt=None)
  File "D:\rough\automl_\efficientdet\inference.py", line 202, in restore_ckpt
    saver.restore(sess, ckpt_path)
  File "D:\env_tensorflow_2\lib\site-packages\tensorflow\python\training\saver.py", line 1328, in restore
    cached_saver=self._object_restore_saver)
  File "D:\env_tensorflow_2\lib\site-packages\tensorflow\python\training\saver.py", line 1721, in saver_from_object_based_checkpoint
    sorted(extra_names)), len(intersecting_names)))
tensorflow.python.framework.errors_impl.NotFoundError:
.
.
.
.
.
Variables names when this checkpoint was written which don't exist now:

(0 variable name(s) did match)

Could not find some variables in the checkpoint (see names above). Saver was attempting to load an object-based checkpoint (saved using tf.train.Checkpoint or tf.keras.Model.save_weights) using variable names. If the checkpoint was written with eager execution enabled, it's possible that variable names have changed (for example missing a '_1' suffix). It's also possible that there are new variables which did not exist when the checkpoint was written. You can construct a Saver(var_list=...) with only the variables which previously existed, and if variable names have changed you may need to make this a dictionary with the old names as keys. If you're using an Estimator, you'll need to return a tf.train.Saver inside a tf.train.Scaffold from your model_fn.

**Comment by avitial** [comment]
@waghts95 not sure using converter.py with your own custom model will work as specified, you may need to add extra Model Optimizer flags for your custom trained model with `--add_mo_ar`. If possible it would be great if you can share the model files to try and see what could be. Also check response given in other filed issue: https://github.com/openvinotoolkit/openvino/issues/4305. 

Lets continue to discuss your issue in here, since the issue on both tickets is around converting the custom trained model.


~Luis

**Comment by avitial** [comment]
Issue related to #4305. 
PR has been merged to 2021.4 master branch with hash commit 522ad39, closing this.
