### ISSUE TITLE
Can't convert custom trained tensorflow 2 object detection model based on model zoo to IR [Bug]

### ISSUE THREAD

**Issue by jasrial** [openvinotoolkit/openvino#4694]
##### System information (version)

- OpenVINO=> 2021.2
- Operating System / Platform => Ubuntu 20.04
- Framework: Tensorflow 2
- Problem classification => Object Detection with SSD Mobilnet V2 320x320

##### Detailed description

I'm using Open Vino for my bachelor thesis at university. The goal is to recognize pedestrians on street pictures. For this I'm training a pre trained model from the [tensorflow object detection model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md) with custom data. After successful training, I wanted to convert the model to the IR and test the inference but the conversion failed. When I try this out with the original SSD Mobilenet V2 (which the custom model is based upon and not trained with my custom data), the conversion works without any issues. 

Is this a bug or is there something I am missing for example: 
- do I have to watch out for something specific while exporting the model after training?
- Is the fact that I am just training the network for one class (pedestrian) relevant?

Since the console output (see below) mentioned contacting Model Optimizer developers, I thought I'd submit an issue. 

##### Steps to reproduce

To convert the model, I've taken the newest version of Open Vino and used the Model Optimizer with the `custom_operations_config` by running:
``
python3 /home/ubuntu/projects/openvino/model-optimizer/mo_tf.py --saved_model_dir /home/ubuntu/Documents/models/tf2oda_ssdmobilenetv2_300x300_pedestrian_D100_LR08/saved_model --tensorflow_object_detection_api_pipeline_config /home/ubuntu/Documents/models/tf2oda_ssdmobilenetv2_300x300_pedestrian_D100_LR08/pipeline.config --tensorflow_use_custom_operations_config /home/ubuntu/projects/openvino/model-optimizer/extensions/front/tf/ssd_support_api_v2.0.json
``

<details>
<summary>Click here for the console output</summary>

[ WARNING ]  Use of deprecated cli option --tensorflow_use_custom_operations_config detected. Option use in the following releases will be fatal. Please use --transformations_config cli option instead
Model Optimizer arguments:
Common parameters:
- Path to the Input Model: None
- Path for generated IR: /home/ubuntu/projects/openvino/.
- IR output name: saved_model
- Log level: ERROR
- Batch: Not specified, inherited from the model
- Input layers: Not specified, inherited from the model
- Output layers: Not specified, inherited from the model
- Input shapes: Not specified, inherited from the model
- Mean values: Not specified
- Scale values: Not specified
- Scale factor: Not specified
- Precision of IR: FP32
- Enable fusing: True
- Enable grouped convolutions fusing: True
- Move mean values to preprocess section: None
- Reverse input channels: False
TensorFlow specific parameters:
- Input model in text protobuf format: False
- Path to model dump for TensorBoard: None
- List of shared libraries with TensorFlow custom layers implementation: None
- Update the configuration file with input/output node names: None
- Use configuration file used to generate the model with Object Detection API: /home/ubuntu/Documents/models/tf2oda_ssdmobilenetv2_300x300_pedestrian_D100_LR08/pipeline.config
- Use the config file: /home/ubuntu/projects/openvino/model-optimizer/extensions/front/tf/ssd_support_api_v2.0.json
Model Optimizer version: unknown version
2021-03-09 11:46:51.313406: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/intel/openvino_2021/data_processing/dl_streamer/lib:/opt/intel/openvino_2021/data_processing/gstreamer/lib:/opt/intel/openvino_2021/opencv/lib:/opt/intel/openvino_2021/deployment_tools/ngraph/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/external/hddl/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/external/gna/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/external/mkltiny_lnx/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/external/tbb/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/lib/intel64
2021-03-09 11:46:51.313499: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-03-09 11:46:52.369570: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/intel/openvino_2021/data_processing/dl_streamer/lib:/opt/intel/openvino_2021/data_processing/gstreamer/lib:/opt/intel/openvino_2021/opencv/lib:/opt/intel/openvino_2021/deployment_tools/ngraph/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/external/hddl/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/external/gna/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/external/mkltiny_lnx/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/external/tbb/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/lib/intel64
2021-03-09 11:46:52.369661: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2021-03-09 11:46:52.369707: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ubuntu-VirtualBox): /proc/driver/nvidia/version does not exist
2021-03-09 11:46:52.369840: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-03-09 11:46:52.373790: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 3599990000 Hz
2021-03-09 11:46:52.373998: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0xb485d50 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-03-09 11:46:52.374048: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-03-09 11:46:57.915061: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2021-03-09 11:46:57.915216: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2021-03-09 11:46:58.078849: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816] Optimization results for grappler item: graph_to_optimize
2021-03-09 11:46:58.078881: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: Graph size after: 3000 nodes (2666), 6204 edges (5863), time = 63.603ms.
2021-03-09 11:46:58.078886: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: Graph size after: 3000 nodes (0), 6204 edges (0), time = 29.128ms.
2021-03-09 11:46:58.078890: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816] Optimization results for grappler item: __inference_map_while_cond_6754_574
2021-03-09 11:46:58.078893: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2021-03-09 11:46:58.078896: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2021-03-09 11:46:58.078899: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816] Optimization results for grappler item: __inference_map_while_body_6755_14817
2021-03-09 11:46:58.078903: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2021-03-09 11:46:58.078906: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: function_optimizer did nothing. time = 0ms.
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Exception occurred during running replacer "ObjectDetectionAPIOutputReplacement (<class 'extensions.front.tf.ObjectDetectionAPI.ObjectDetectionAPIOutputReplacement'>)": 'inputs'
[ ERROR ]  Traceback (most recent call last):
  File "/home/ubuntu/projects/openvino/model-optimizer/mo/utils/class_registration.py", line 290, in apply_transform
    for_graph_and_each_sub_graph_recursively(graph, replacer.find_and_replace_pattern)
  File "/home/ubuntu/projects/openvino/model-optimizer/mo/middle/pattern_match.py", line 59, in for_graph_and_each_sub_graph_recursively
    for_each_sub_graph_recursively(graph, func)
  File "/home/ubuntu/projects/openvino/model-optimizer/mo/middle/pattern_match.py", line 53, in for_each_sub_graph_recursively
    for_each_sub_graph(graph, recursive_helper)
  File "/home/ubuntu/projects/openvino/model-optimizer/mo/middle/pattern_match.py", line 38, in for_each_sub_graph
    func(node[sub_graph_name])
  File "/home/ubuntu/projects/openvino/model-optimizer/mo/middle/pattern_match.py", line 49, in recursive_helper
    func(sub_graph)
  File "/home/ubuntu/projects/openvino/model-optimizer/mo/front/tf/replacement.py", line 48, in find_and_replace_pattern
    self.transform_graph(graph, desc._replacement_desc['custom_attributes'])
  File "/home/ubuntu/projects/openvino/model-optimizer/extensions/front/tf/ObjectDetectionAPI.py", line 1216, in transform_graph
    add_output_ops(graph, _outputs, graph.graph['inputs'])
KeyError: 'inputs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/projects/openvino/model-optimizer/mo/main.py", line 297, in main
    ret_code = driver(argv)
  File "/home/ubuntu/projects/openvino/model-optimizer/mo/main.py", line 264, in driver
    ret_res = emit_ir(prepare_ir(argv), argv)
  File "/home/ubuntu/projects/openvino/model-optimizer/mo/main.py", line 233, in prepare_ir
    graph = unified_pipeline(argv)
  File "/home/ubuntu/projects/openvino/model-optimizer/mo/pipeline/unified.py", line 25, in unified_pipeline
    class_registration.apply_replacements(graph, [
  File "/home/ubuntu/projects/openvino/model-optimizer/mo/utils/class_registration.py", line 340, in apply_replacements
    apply_replacements_list(graph, replacers_order)
  File "/home/ubuntu/projects/openvino/model-optimizer/mo/utils/class_registration.py", line 326, in apply_replacements_list
    apply_transform(
  File "/home/ubuntu/projects/openvino/model-optimizer/mo/utils/logger.py", line 124, in wrapper
    function(*args, **kwargs)
  File "/home/ubuntu/projects/openvino/model-optimizer/mo/utils/class_registration.py", line 314, in apply_transform
    raise Exception('Exception occurred during running replacer "{} ({})": {}'.format(
Exception: Exception occurred during running replacer "ObjectDetectionAPIOutputReplacement (<class 'extensions.front.tf.ObjectDetectionAPI.ObjectDetectionAPIOutputReplacement'>)": 'inputs'

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------

</details>

**Comment by alexanderwendt** [comment]
Remark 1: This set only has 1 output class instead of 90 in the coco dataset.

**Comment by alexanderwendt** [comment]
Her are models that are retrained from the TF2ODA Model Zoo original models.
https://owncloud.tuwien.ac.at/index.php/s/V6Skw5PeqZxhZHT

**Comment by jasrial** [comment]
any updates? :)

**Comment by Iffa-Meah** [comment]
Hi, 
I've tried to convert your [saved model format](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html#savedmodel_format) as you had provided. Unfortunately, it doesn't come up with successful result.

There are 2 ways to do IR conversion:
1. Non-frozen model : checkpoint/MetaGraph/saved model
2. Frozen model can be used directly with the Model Optimizer
You may refer to the hyperlink above.

To use the Saved Model, you need to genuinely know your input and output layer.
To really check this, you can use the [summarize graph utility](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_Slim_Library_Models.html)

I tried to check your saved model with the summarize graph utility to ensure input & output layer but it seems that your saved model is incorrect Tensorflow model file.

Try to properly check & re-generate your model according to this [guide](https://www.youtube.com/watch?v=QW6532LtiTc).

**Comment by jasrial** [comment]
Hello, 

So I have a few questions:

>     1. Non-frozen model : checkpoint/MetaGraph/saved model

That is what I tried to use.

>     2. Frozen model can be used directly with the Model Optimizer

As far as I know, freezing models is deprecated in Tensorflow 2 and since our training server runs with Tensorflow 2 unfortunately this does not help me.

> To use the Saved Model, you need to genuinely know your input and output layer.

Isn't that what the `tensorflow_custom_operations_config` is for? I'm asking because I'm basing my model on a model that is officially supported and where the conversion works without any problem (SSD MobilenetV2). It should be the same except for the fact that my model is trained to recognize one single class (pedestrians) instead of the 80 something from the official COCO dataset. Does this change the structure of the graph in a way that the conversion doesn't work anymore? 

> I tried to check your saved model with the summarize graph utility to ensure input & output layer but it seems that your saved model is incorrect Tensorflow model file.

What do you mean it is an incorrect Tensorflow model file? Because we can run the native tensorflow inference, do measurements without any problems...

**Comment by Iffa-Meah** [comment]
can you share the working model instead?

**Comment by alexanderwendt** [comment]
Thank you for looking at this problem. We use the standard exporting method of TF2, which they mention in the guide: https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html#exporting-a-trained-model

Here is the original model: http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_320x320_coco17_tpu-8.tar.gz

Here is a retrained model with our data, unexported:
https://owncloud.tuwien.ac.at/index.php/s/sdUrU09K4kh23X6

Here are some exported models: 
https://owncloud.tuwien.ac.at/index.php/s/V6Skw5PeqZxhZHT

**Comment by mahehu** [comment]
This [issue](https://github.com/openvinotoolkit/openvino/issues/4830) might be related. 

There is also PR in the thread that should enable using SavedModel format created with TF2.4.

**Comment by Iffa-Meah** [comment]
Hey, there is a new version released.
The issue mentioned had been merged in that version.
Please help to try it out and see whether the problem still persists.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
