### ISSUE TITLE
from .ie_api import * ImportError: DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by qbTrible** [openvinotoolkit/openvino#478]
I try to inference YOLOv3 by openvino, there is an ie "api.pyd" file in the interface_engine folder of python3.6 folder.
Any method shown in this thread,all done.
Please teach me the tip to solve the error.
_________________
OpenVINO 2020.1
OS:Windows10 Pro v1909 OS build 18363.418
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
_________________
>python object_detection_demo_yolov3_async.py -m pf/yolov3.xml -i test.jpg

   from modules.inference_engine import InferenceEngine
  File "C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\open_model_zoo\demos\python_demos\human_pose_estimation_3d_demo\modules\inference_engine.py", line 19, in <module>
    from openvino.inference_engine import IENetwork, IECore
  File "C:\Program Files (x86)\IntelSWTools\openvino\python\python3.6\openvino\inference_engine\__init__.py", line 1, in <module>
    from .ie_api import *
ImportError: DLL load failed: The specified module could not be found

**Comment by leavim** [comment]
@qbTrible is not very clear what the steps are to get to this problem. Make sure if you are running the _object_detection_demo_yolov3_async.py_ script on a CMD terminal to setup the environment variables running the _setupvars.bat_ script under _C:\Program Files (x86)\IntelSWTools\openvino\bin\_ directory. 

Have you verified your installation of OpenVINO using verification scripts prior to running YoloV3 demo app? This error looks like a configuration mistake in environment, please make sure to complete all steps given on 2020.1 [installation guide for Windows](https://docs.openvinotoolkit.org/2020.1/_docs_install_guides_installing_openvino_windows.html)*. Please note there is a newer release available ([2020.2 release notes](https://software.intel.com/content/www/us/en/develop/articles/openvino-relnotes.html)).

Regards,
Luis

**Comment by jiwaszki** [comment]
Hi @qbTrible! Is the issue resolved? 

I had similar error (DLL for OpenCV) when running cross_check_tool. Make sure you have everything set (link in @avitial comment). If problem is still present then **manually fix _openvino\scripts\setupvars\setupvars.bat_ commands,** so they match your folder structure.

Hope it helps!

-Jan

**Comment by ogilg** [comment]
I got the same exact error when trying "from openvino.inference_engine import IENetwork". However I don't think this is an installation error because when I run the exact same command from the command prompt it works just fine. Also I have run setupvars.bat.
@jiwaszki  what do you mean by manually fix the files to match your folder structure? I've looked at them and they seem to have the right folders.

I am running this on PyCharm.
OpenVINO 2020.4.287
Windows 10

from openvino.inference_engine import IECore
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition with Anaconda plugin 2020.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Program Files (x86)\IntelSWTools\openvino\python\python3.6\openvino\inference_engine\__init__.py", line 1, in <module>
    from .ie_api import *
  File "C:\Program Files\JetBrains\PyCharm Community Edition with Anaconda plugin 2020.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: DLL load failed: The specified module could not be found.

**Comment by issaiass** [comment]
> I try to inference YOLOv3 by openvino, there is an ie "api.pyd" file in the interface_engine folder of python3.6 folder.
> Any method shown in this thread,all done.
> Please teach me the tip to solve the error.
> 
> OpenVINO 2020.1
> OS:Windows10 Pro v1909 OS build 18363.418
> Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
> 
> > python object_detection_demo_yolov3_async.py -m pf/yolov3.xml -i test.jpg
> 
> from modules.inference_engine import InferenceEngine
> File "C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\open_model_zoo\demos\python_demos\human_pose_estimation_3d_demo\modules\inference_engine.py", line 19, in
> from openvino.inference_engine import IENetwork, IECore
> File "C:\Program Files (x86)\IntelSWTools\openvino\python\python3.6\openvino\inference_engine__init__.py", line 1, in
> from .ie_api import *
> ImportError: DLL load failed: The specified module could not be found

Hello i had the same problems.
The problem is that your bindings are not found, probably you are also mixing something:
Another problem could be if you do not have Visual Studio Redistributable 2015 or above installed, but i will assume that is not the case.

This was what i tested and worked, please do the tests:

1 - Create an environment with python 3.5, 3.6, 3.7, in your case will be python 3.6 and install cython, opencv-contrib-python too.

>>conda create -n opencv-openvino python=3.6
>>activate opencv-openvino
(opencv-openvino)>>python --version
Python 3.6 :: Anaconda, Inc.
(opencv-openvino)>>pip install cython>=0.29
>> pip install opencv-contrib-python
quit()

2 - Copy the openvino python version folder to the packages folder

2.1- Check the location of the site-packages

(opencv-openvino)>>pip show pip
Name: pip
Version: 20.2
Summary: The PyPA recommended tool for installing Python packages.
Home-page: https://pip.pypa.io/
Author: The pip developers
Author-email: distutils-sig@python.org
License: MIT
Location: c:\users\issai\anaconda3\envs\opencv-openvino\lib\site-packages
Requires:
Required-by:

2.2 - Copy the openvino folder to the site packages folder

For example:
copy this folder: C:\Program Files (x86)\IntelSWTools\openvino_2020.3.194\python\python3.6\openvino
throw to this location: c:\users\issai\anaconda3\envs\opencv-openvino\lib\site-packages

3 - Run the setupvars:

NOTE: i made a special change to see the environmental variables, see the pasetbin; https://pastebin.com/4xcce26F
NOTE: OpenCV_DIR must exist on your environmental variables to run the script correctly

(opencv-openvino)>> C:\Program Files (x86)\IntelSWTools\openvino_2020.3.194\bin\setupvars.bat
OpenCV Directory exists at C:\OpenCV\OpenCV-4.4.0\opencv\build\install\
Below a list of the PYTHONPATH variable

C:\Program Files (x86)\IntelSWTools\openvino_2020.3.194\deployment_tools\open_model_zoo\tools\accuracy_checker;C:\Program Files (x86)\IntelSWTools\openvino_2020.3.194\python\python3.5;C:\Program Files (x86)\IntelSWTools\openvino_2020.3.194\python\python3;C:\Program Files (x86)\IntelSWTools\openvino_2020.3.194\deployment_tools\model_optimizer;

4 - Try to see if you can import IECore and IENetwork

(opencv-openvino)>>python
Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 16:05:27) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from openvino.inference_engine import IENetwork, IECore

5 - If above gives no error you are ok.


BONUS: The "probably" easiest way
1 - Created a virtual environment with python=3.5 (IMPORTANT!)
2 - Activate the virtual environment
3 - Install openvino with opencv: pip install opencv-openvino-contrib-python
4 - Run the setupvars
5 - Try to see if you can load IENetwork and IECore

------------------------------------------------------------------------------------------------------------------------------------

Graphical Steps after the first step (created the virtual environment):
NOTE: Remember i changed the setupvars.bat to see the output
NOTE: Remember OpenCV_DIR is created
NOTE: I have created an environment with python=3.5

2 - Copy the openvino python version folder to the packages folder

2.1 - Check the location of the site-packages
![image](https://user-images.githubusercontent.com/4116031/89091044-407bb800-d36c-11ea-8765-f45692cd2970.png)

2.2 - Copy the openvino folder to the site packages folder
![image](https://user-images.githubusercontent.com/4116031/89091104-8173cc80-d36c-11ea-8df9-6f7370da67c6.png)

![image](https://user-images.githubusercontent.com/4116031/89091115-99e3e700-d36c-11ea-8b42-f7f243f996ff.png)

3 - Run the setupvars.bat
![image](https://user-images.githubusercontent.com/4116031/89091132-c992ef00-d36c-11ea-9c97-40ef4f61fab8.png)

4 & 5 - Try to see if you can import IECore and IENetwork; If gives no error you are ok
![image](https://user-images.githubusercontent.com/4116031/89091163-02cb5f00-d36d-11ea-9891-02a9eb2d149f.png)

Result image:
![image](https://user-images.githubusercontent.com/4116031/89091190-3312fd80-d36d-11ea-9ef3-30631570c01d.png)



BONUS: The "probably" easiest way:

![image](https://user-images.githubusercontent.com/4116031/89091549-2643d900-d370-11ea-9c6f-88f7d2c1111b.png)

**Comment by issaiass** [comment]
Another, but ugly workaround in pycharm could be, if you completed above:

![image](https://user-images.githubusercontent.com/4116031/89107055-e7576700-d3f3-11ea-9454-4c057d05640b.png)

**Comment by 1165048017** [comment]
> Another, but ugly workaround in pycharm could be, if you completed above:
> 
> ![image](https://user-images.githubusercontent.com/4116031/89107150-a3189680-d3f4-11ea-9dbe-86572d6e2ad7.png)

It does work

**Comment by middlemall** [comment]
Reference resources setupvars.bat , and reconfigure the environment variables to solve the above problems

**Comment by issaiass** [comment]
> ![image](https://user-images.githubusercontent.com/36463683/90518322-3134a100-e199-11ea-87b8-9781dd3b65e1.png)
> 
> Reference resources setupvars.bat , and reconfigure the environment variables to solve the above problems
> ![image](https://user-images.githubusercontent.com/36463683/90518263-1b26e080-e199-11ea-8fdc-f8a835858627.png)

Yes, that's basically the problem always, that's why i put hte above solutions.  Thanks for sharing.

**Comment by akuporos** [comment]
In order to avoid this problem you should ```set PYTHONPATH=C:\..\openvino\bin\intel64\Release\python_api\python3.7``` and
```set PATH=C:\..\openvino\bin\intel64\Release;C:\..\openvino\inference-engine\temp\tbb\bin;%PATH%```

**Comment by PollenJain** [comment]
Follow the following steps to resolve the issue on Windows 10 :

1. Copy all the DLLs from **C:\Program Files (x86)\Intel\openvino_2021.2.185\deployment_tools\inference_engine\bin\intel64\Release\** to the same folder where the python file using the inference engine APIs are present (python file will contain statement such as **from openvino.inference_engine import IENetwork, IECore**).

2. Open a command prompt, navigate to **C:\Program Files (x86)\Intel\openvino_2021.2.185\bin** and execute setupvars.bat

3. If you have created a python environment and installed all the python runtimes inside it, then activate the python environment. Else use your default python installation.

4. Navigate to the folder containing your application's main python script. Execute your main python script.

**Comment by korhun** [comment]
Windows 10 -  openvino 2021.2.185
None of above worked for me.
"import openvino" works but "from openvino.inference_engine import IECore" raises "ImportError: Dll load failed" exception.

**Comment by gloomyfish1998** [comment]
version information 
openvino 2021.2.185
python SDK 3.8.5
VS2015 Pro
Windows 10 64bit
all above sw installed by default
======================================
i can run demo with VS2015

=======================
but when i run python, always get 👎 
-----------------------------------------------------------------------------------------------------------
Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from openvino.inference_engine import IECore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\openvino\inference_engine\__init__.py", line 1, in <module>
    from .ie_api import *
ImportError: DLL load failed while importing ie_api: 找不到指定的模块。
==============================================================

more information
i can run pervious openvino 2020.x in python3.6.5 on my machine 
but same configuration does not work for 3.8.5 + 2021.2.185 on windows 10 64bit

please confirm / any suggestion ??

**Comment by gloomyfish1998** [comment]
more explain, i already changed all config path, and remove python 3.6.5 and openvino2020.x versions

**Comment by jbrownkramer** [comment]
I have tried every suggestion on this page and I still get this error.  I believe there is simply a missing DLL that is neglected in the existing Windows 10 install.

**Comment by sparrow84001** [comment]
hy find those file 
and copy that path
then save Environment Variables 
then  you good to go (further if u any problem contact me .)
![lala](https://user-images.githubusercontent.com/37022413/115618164-ee226300-a30f-11eb-8fb9-f04f9b20f9da.PNG)

**Comment by Im-Himanshu** [comment]
> Another, but ugly workaround in pycharm could be, if you completed above:
> 
> ![image](https://user-images.githubusercontent.com/4116031/89107150-a3189680-d3f4-11ea-9dbe-86572d6e2ad7.png)
```

os.environ['path']  += 'C:\\Program Files (x86)\\IntelSWTools\\openvino_2021.2.185\\deployment_tools\\ngraph\\lib;' \
                       'C:\\Program Files (x86)\\IntelSWTools\\openvino_2021.2.185\\deployment_tools\\ngraph\\lib;'\
                       'C:\\Program Files (x86)\\IntelSWTools\\openvino_2021.2.185\\deployment_tools\\\inference_engine\\external\\tbb\\bin;'\
                       'C:\\Program Files (x86)\\IntelSWTools\\openvino_2021.2.185\\deployment_tools\\inference_engine\\bin\\intel64\\Release;'\
                       'C:\\Program Files (x86)\\IntelSWTools\\openvino_2021.2.185\\deployment_tools\\inference_engine\bin\\intel64\\Debug;'\
                       'C:\\Program Files (x86)\\IntelSWTools\\openvino_2021.2.185\\deployment_tools\\inference_engine\\external\\hddl\\bin;' \
                       'C:\\Program Files (x86)\\IntelSWTools\\openvino_2021.2.185\\deployment_tools\\model_optimizer;'
```

**Comment by evgenii-brovkin** [comment]
If you are using Python 3.8 or higher and installed openvino via pip **on Windows** then 

- go to `your\env\site-packages\openvino\inference_engine`
- open \_\_init\_\_.py
- look for those lines 
`25. if (3, 8) <= sys.version_info:`
`26.        os.add_dll_directory(os.path.abspath(lib_path))`
- add `os.environ['PATH'] = os.path.abspath(lib_path) + ';' + os.environ['PATH']` after the last line

or instead just add `your\env\site-packages\openvino\libs` folder to the PATH

**Comment by sahira-rizvi** [comment]
Closing, feel free to re-open or start a new issues if additional assistance is needed.

Sincerely,
Sahira
