### ISSUE TITLE
Getting error during inference with onnx built with openvino support

### ISSUE THREAD

**Issue by gpradhanm** [openvinotoolkit/openvino#5205]
##### System information (version)
- OpenVINO => 2021.1.110 
- Operating System / Platform => Linux (Ubuntu 18.04)
- Compiler => Python
- Problem classification: Inference
- Framework: ONNX build with openvino
- Model name: N/A

##### Detailed description
I have a onnx model that works OK with Onnx runtime. When I tried to run inference with ONNX built with openvino support, I get the below error.

```
2021-04-12 14:06:54.345055587 [E:onnxruntime:, sequential_executor.cc:338 Execute] Non-zero status code returned while running OpenVINO-EP-subgraph_3 node. Name:'OpenVINOExecutionProvider_OpenVINO-EP-subgraph_3_0' Status Message: /home/ubuntu/General_RnD/ONNX/onnxruntime/onnxruntime/core/providers/openvino/backend_utils.cc:113 std::shared_ptr<InferenceEngine::CNNNetwork> onnxruntime::openvino_ep::backend_utils::CreateCNNNetwork(const onnx::ModelProto&, const onnxruntime::openvino_ep::GlobalContext&, const onnxruntime::openvino_ep::SubGraphContext&, std::map<std::__cxx11::basic_string<char>, std::shared_ptr<ngraph::Node> >&) [OpenVINO-EP] [OpenVINO-EP] Exception while importing model to nGraph Func: While validating ONNX node '<Node(Unsqueeze): Unsqueeze_16>':
Check '!axes.empty()' failed at ngraph/core/src/op/unsqueeze.cpp:63:
While validating node 'v0::Unsqueeze Unsqueeze_17 (72[0]:i64{}, Constant_16[0]:i64{0}) -> (dynamic?)' with friendly_name 'Unsqueeze_17':
'axes' input is mandatory.


Traceback (most recent call last):
  File "reproducible.py", line 16, in <module>
    ort_outs_enc = ort_session_enc.run(None, {'xs_pad':xs_pad})
  File "/home/ubuntu/.local/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running OpenVINO-EP-subgraph_3 node. Name:'OpenVINOExecutionProvider_OpenVINO-EP-subgraph_3_0' Status Message: /home/ubuntu/General_RnD/ONNX/onnxruntime/onnxruntime/core/providers/openvino/backend_utils.cc:113 std::shared_ptr<InferenceEngine::CNNNetwork> onnxruntime::openvino_ep::backend_utils::CreateCNNNetwork(const onnx::ModelProto&, const onnxruntime::openvino_ep::GlobalContext&, const onnxruntime::openvino_ep::SubGraphContext&, std::map<std::__cxx11::basic_string<char>, std::shared_ptr<ngraph::Node> >&) [OpenVINO-EP] [OpenVINO-EP] Exception while importing model to nGraph Func: While validating ONNX node '<Node(Unsqueeze): Unsqueeze_16>':
Check '!axes.empty()' failed at ngraph/core/src/op/unsqueeze.cpp:63:
While validating node 'v0::Unsqueeze Unsqueeze_17 (72[0]:i64{}, Constant_16[0]:i64{0}) -> (dynamic?)' with friendly_name 'Unsqueeze_17':
'axes' input is mandatory.

```

##### Steps to reproduce

I have attached a code with weight file for error reproduction
   
https://we.tl/t-LAuSuS7dv0

**Comment by zulkifli-halim** [comment]
2021.3 is the recommended OpenVINO version. Can you try it on OpenVINO 2021.3?

**Comment by zulkifli-halim** [comment]
Hello. I will close this ticket. If you need any additional information, please open a new ticket.

**Comment by supercharleszhu** [comment]
Have had the same issue on this when using the OpenVINO EP in the onnx model. @zulkifli-halim do we have some off the shelf documentation on which kind of models are supported for OpenVINO EP in onnx runtime, or to convert it into OpenVINO IR format?
