### ISSUE TITLE
[Bug] OPENVINO supported by Pyinstaller?

### ISSUE THREAD

**Issue by sandeep406** [openvinotoolkit/openvino#5725]
##### Detailed description
My project is based on OPENVINO 2021.3.0 to detect faces from images. I am successfully running the application from the Pycharm IDE. When I have built executable using pytnstaller. when I run the executable following error shows up. I cannot run the application. 
I have looked up online and confused "Is OPENVINO supported by Pyinstaller?". Any help would be highly appreciated. 
 
# error
PS C:\Users\Embross Employee\Emvision Embedded\EmvisionEmbeddedAPP\Emvision\main> .\main.exe
Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "router\routes.py", line 6, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "face_detection_module\face_detection.py", line 17, in <module>
  File "face_detection_module\Paravision\paravision_model.py", line 9, in __init__
  File "paravision\recognition\session.py", line 76, in __init__
  File "paravision\recognition\_internal.py", line 157, in __init__
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "paravision\recognition\openvino\engine.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "openvino\inference_engine\__init__.py", line 34, in <module>
ImportError: DLL load failed: The specified module could not be found.
[17372] Failed to execute script main
PS C:\Users\Embross Employee\Emvision Embedded\EmvisionEmbeddedAPP\Emvision\main>

**Comment by Iffa-Meah** [comment]
Hi,

Currently, the Pyinstaller is not officially supported by OpenVINO.
If possible try to use the [OpenVINO Deployment Manager](https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_deployment_manager_tool.html) instead.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
