### ISSUE TITLE
Error converting TF-OD-API model to IR format with Model Optimizer

### ISSUE THREAD

**Issue by KrotAphanasiy** [openvinotoolkit/openvino#5749]
<h2>I have a trained from sketch ssd-mobile-net-v1_640x640 from tensorflow model garden. It correctly inferences on tf, but when I`m trying to freeze the graph and pass it to model optimizer I`m getting the following bug report.</h2> <br>
<h3>What may be the reason and how am I able to fix that stuff? I`ll provide any additional information required.</h3> <br>
[ ERROR ]  -------------------------------------------------<br>
[ ERROR ]  ----------------- INTERNAL ERROR ----------------<br>
[ ERROR ]  Unexpected exception happened.<br>
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:<br>
[ ERROR ]  Exception occurred during running replacer "ObjectDetectionAPIPreprocessor2Replacement <br>(<class 'extensions.front.tf.ObjectDetectionAPI.ObjectDetectionAPIPreprocessor2Replacement'>)": <br>
[ ERROR ]  Traceback (most recent call last):<br>
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/utils/class_registration.py",<br> line 290, in apply_transform<br>
    for_graph_and_each_sub_graph_recursively(graph, replacer.find_and_replace_pattern)<br>
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/middle/pattern_match.py", <br>line 59, in for_graph_and_each_sub_graph_recursively<br>
    func(graph)
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/front/tf/replacemen<br>t.py",<br> line 48, in find_and_replace_pattern<br>
    self.transform_graph(graph, desc._replacement_desc['custom_attributes'])<br>
  File <br>"/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/extensions/front/tf/ObjectDetection<br>API.py", line 604, in transform_graph<br>
    assert start_nodes[0] in graph.nodes<br>
AssertionError<br>

The above exception was the direct cause of the following exception:<br>

Traceback (most recent call last):<br>
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/main.py", line 345, in main<br>
    ret_code = driver(argv)<br>
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/main.py", line 309, in driver<br>
    ret_res = emit_ir(prepare_ir(argv), argv)<br>
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/main.py", line 252, in <br>prepare_ir<br>
    graph = unified_pipeline(argv)<br>
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/pipeline/unified.py", line<br> 25, in unified_pipeline<br>
    class_registration.apply_replacements(graph, [<br>
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/utils/class_registration.py",<br> line 340, in apply_replacements<br>
    apply_replacements_list(graph, replacers_order)<br>
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/utils/class_registration.py",<br> line 326, in apply_replacements_list<br>
    apply_transform(<br>
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/utils/logger.py", line 124, <br>in wrapper<br>
    function(*args, **kwargs)<br>
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/utils/class_registration.py",<br> line 314, in apply_transform<br>
    raise Exception('Exception occurred during running replacer "{} ({})": {}'.format(<br>
Exception: Exception occurred during running replacer "ObjectDetectionAPIPreprocessor2Replacement <br>(<class 'extensions.front.tf.ObjectDetectionAPI.ObjectDetectionAPIPreprocessor2Replacement'>)": <br>

[ ERROR ]  ---------------- END OF BUG REPORT --------------<br>
[ ERROR ]  -------------------------------------------------<br>

**Comment by ilya-lavrenov** [comment]
CC @lazarevevgeny

**Comment by lazarevevgeny** [comment]
@KrotAphanasiy , could you send the link to the repository and attach a model and a sample image? I guess that we don't support such a model flavour.

**Comment by Iffa-Meah** [comment]
Hi, we are closing this thread on GitHub since the answer had been provided on the [Intel Forums](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/Error-converting-TF-OD-API-model-to-IR-format-with-Model/m-p/1283655)
