### ISSUE TITLE
[Bug] Error converting Model that has been trained on Keras to IR

### ISSUE THREAD

**Issue by AryaB-1999** [openvinotoolkit/openvino#5770]
##### System information (version)

- OpenVINO=> 2021.3
- Operating System / Platform => Ubuntu 20.04
- Problem classification => Small Object Tracking 
- Model : Tracknet V2 => https://nol.cs.nctu.edu.tw:234/open-source/TrackNetv2/tree/master/3_in_3_out (gitlab)

##### Detailed description
I am trying to convert a Model that has been trained on Keras (not tf.keras) to Openvino IR. The model is already in N, C, H, W format hence when I am running model optimizer without disabling --disable_nhcw_to_nchw option, it converts it perfectly, but it is not useful. Hence I need to put the --disable_nhcw_to_nchw flag, and it gives the following error. Any help will be appretiated.

Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	/media/arya-bhivpathaki/Big Workspace/Hit Classification/frozen_models/simple_frozen_graph.pb
	- Path for generated IR: 	/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/.
	- IR output name: 	TrackNetv2
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	Not specified, inherited from the model
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP32
	- Enable fusing: 	True
	- Enable grouped convolutions fusing: 	True
	- Move mean values to preprocess section: 	None
	- Reverse input channels: 	False
TensorFlow specific parameters:
	- Input model in text protobuf format: 	False
	- Path to model dump for TensorBoard: 	None
	- List of shared libraries with TensorFlow custom layers implementation: 	None
	- Update the configuration file with input/output node names: 	None
	- Use configuration file used to generate the model with Object Detection API: 	None
	- Use the config file: 	None
[ WARNING ] Failed to import Inference Engine Python API in: /opt/intel/openvino_2021.3.394/python/python3.8
[ WARNING ] libinference_engine.so: cannot open shared object file: No such file or directory
	- Inference Engine found in: 	/opt/intel/openvino_2021.3.394/python/python3.8/openvino
Inference Engine version: 	2.1.2021.3.0-2787-60059f2c755-releases/2021/3
Model Optimizer version: 	    2021.3.0-2787-60059f2c755-releases/2021/3
2021-05-24 19:13:20.461871: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/utils/../../../inference_engine/lib/intel64:/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/utils/../../../inference_engine/external/tbb/lib:/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/utils/../../../ngraph/lib
2021-05-24 19:13:20.461892: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.4) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Exception occurred during running replacer "None (<class 'extensions.front.tf.InterpolateTransposes.InterpolateTranspose'>)": 
[ ERROR ]  Traceback (most recent call last):
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 290, in apply_transform
    for_graph_and_each_sub_graph_recursively(graph, replacer.find_and_replace_pattern)
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/middle/pattern_match.py", line 59, in for_graph_and_each_sub_graph_recursively
    func(graph)
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/front/common/replacement.py", line 148, in find_and_replace_pattern
    apply_pattern(graph, action=self.replace_sub_graph, **self.pattern())
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/middle/pattern_match.py", line 96, in apply_pattern
    action(graph, match)
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/extensions/front/tf/InterpolateTransposes.py", line 73, in replace_sub_graph
    axes = Interpolate.get_axes(interpolate)
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/extensions/ops/interpolate.py", line 177, in get_axes
    assert src_shape is not None
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/main.py", line 345, in main
    ret_code = driver(argv)
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/main.py", line 309, in driver
    ret_res = emit_ir(prepare_ir(argv), argv)
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/main.py", line 252, in prepare_ir
    graph = unified_pipeline(argv)
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/pipeline/unified.py", line 25, in unified_pipeline
    class_registration.apply_replacements(graph, [
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 340, in apply_replacements
    apply_replacements_list(graph, replacers_order)
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 326, in apply_replacements_list
    apply_transform(
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/utils/logger.py", line 124, in wrapper
    function(*args, **kwargs)
  File "/opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 314, in apply_transform
    raise Exception('Exception occurred during running replacer "{} ({})": {}'.format(
Exception: Exception occurred during running replacer "None (<class 'extensions.front.tf.InterpolateTransposes.InterpolateTranspose'>)": 

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------

##### Steps to reproduce

Download any of the 2 models from the above repository, there are 2 folders which contain 1 model each, I used 3_in_3_out, model_96... 

Convert it into frozen graph using : 

from tensorflow import keras
import tensorflow as tf
from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2
import numpy as np

def custom_loss(y_true, y_pred):
    loss = (-1)*(K.square(1 - y_pred) * y_true * K.log(K.clip(y_pred, K.epsilon(), 1)) + K.square(y_pred) * (1 - y_true) * K.log(K.clip(1 - y_pred, K.epsilon(), 1)))
    return K.mean(loss)

model = keras.models.load_model('Tracknet-Models/TN-v2-3in3out.h5', custom_objects={'custom_loss': custom_loss})

full_model = tf.function(lambda x: model(x))
full_model = full_model.get_concrete_function(
    x=tf.TensorSpec((1, 9, 288, 512), model.inputs[0].dtype))

frozen_func = convert_variables_to_constants_v2(full_model)
frozen_func.graph.as_graph_def()

layers = [op.name for op in frozen_func.graph.get_operations()]
print("-" * 50)
print("Frozen model layers: ")
for layer in layers:
    print(layer)

print("-" * 50)
print("Frozen model inputs: ")
print(frozen_func.inputs)
print("Frozen model outputs: ")
print(frozen_func.outputs)

tf.io.write_graph(graph_or_graph_def=frozen_func.graph,
                  logdir="./frozen_models",
                  name="simple_frozen_graph.pb",
                  as_text=False)

tf.io.write_graph(graph_or_graph_def=frozen_func.graph,
                  logdir="./frozen_models",
                  name="simple_frozen_graph.pbtxt",
                as_text=True)
model.summary()

And then run : 
python mo_tf.py -m simple_frozen_graph.pb --disable_nhwc_to_nchw --input_shape=[1,9,288,512]

**Comment by Iffa-Meah** [comment]
Hi,

It seems the link didn't work for me. Is there any other way for me to access the model?

![site](https://user-images.githubusercontent.com/79643476/120158982-4a3da880-c227-11eb-9d8f-901b73ca0028.png)



Would appreciate it if you could help to share the trained model which you have issue with.

**Comment by AryaB-1999** [comment]
Hi, here is the model

https://drive.google.com/file/d/1ghrE77LUkqKkpdSDBYmY95Iz4rpCiSz6/view?usp=sharing

**Comment by Iffa-Meah** [comment]
Hi,

I managed to freeze your model and convert it to IR. You may refer to the attached photo.
I run the IR with OpenVINO Benchmark app and it gave out some output. 
This means that your model works so far. Hence may I know what do you mean with "it converts it perfectly, but it is not useful"

![frozen_IR](https://user-images.githubusercontent.com/79643476/120690135-66677100-c4d7-11eb-8702-7c0b659a33ea.png)
![frozen_IR_benchmark](https://user-images.githubusercontent.com/79643476/120690162-6f584280-c4d7-11eb-8ee3-d203a24ccace.png)

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
