### ISSUE TITLE
[Bug] POT's custom Metric shows No metric values after running Round 1

### ISSUE THREAD

**Issue by dedoogong** [openvinotoolkit/openvino#5825]
##### System information (version)
- OpenVINO => 2021.3
- Operating System / Platform => Ubuntu 18.04
- Compiler => GCC/G++
- Problem classification: POT
- Framework: Pytorch, ONNX
- Model name: R2D2 

##### Files for Reproduce (code and model) 
[test.zip](https://github.com/openvinotoolkit/openvino/files/6545234/test.zip)

and for downloading calibration images, run belows
```
git clone https://github.com/mihaidusmanu/d2-net.git
cd d2-net/hpatches_sequences/
bash download.sh
bash download_cache.sh
cd ../..
ln -s d2-net/hpatches_sequences # finally create a soft-link
```
##### Detailed description
Hello!
I've running POT Python API with my own data loader and metric class(so using Accuracy Aware quantization). 
in the first pipeline.evaluate(), it shows a normal result of metric's update call as below;

```
Quantizing FP32 OpenVINO model to INT8
There are 647 samples in the test dataset 
Accuracy-aware quantization method
08:22:33 accuracy_checker WARNING: quantize.py:141: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:766.)
  return maxima.nonzero().t()[2:4]

index :  2  metric  :  68.834203794497  self.lastValue :  68.834203794497 
...
...
...
index :  644  metric  :  228.11963083147103  self.lastValue :  228.11963083147103
Round #1    Mean Accuracy = 149.28721726188328
metric_results_FP32 Done 
compressed_model Start! 
self.index:  648 len(self._values) == 0! / self._values :  [] self.lastValue :  228.11963083147103 
...
```
but from the Round #2 run, the pre calculated metric values are all gone(empty list!)
```
self.index:  1294 len(self._values) == 0! / self._values :  [] self.lastValue :  228.11963083147103
...
...
Round #2    Mean Accuracy = 228.11963083147103
```
and from Rount 3, it shows an error whie running pipeline.compress() step. 
```
...
index :  1296  metric  :  68.834203794497  self.lastValue :  68.834203794497
index :  1302  metric  :  142.20228903286582  self.lastValue :  142.20228903286582
Round #3    Mean Accuracy = 105.51824641368141
len(self._values) == 0! / self._values :  [] self.lastValue :  228.11963083147103

Traceback (most recent call last):
  File "quantize.py", line 371, in <module>
    compressed_model = pipeline.run(model)
  File "/opt/intel/openvino/deployment_tools/tools/post_training_optimization_toolkit/compression/pipeline/pipeline.py", line 54, in run
    model = self.collect_statistics_and_run(model, current_algo_seq)
  File "/opt/intel/openvino/deployment_tools/tools/post_training_optimization_toolkit/compression/pipeline/pipeline.py", line 67, in collect_statistics_and_run
    model = algo.run(model)
  File "/opt/intel/openvino/deployment_tools/tools/post_training_optimization_toolkit/compression/algorithms/quantization/accuracy_aware/algorithm.py", line 172, in run
    print_progress=print_progress)
  File "/opt/intel/openvino/deployment_tools/tools/post_training_optimization_toolkit/compression/algorithms/quantization/accuracy_aware/algorithm.py", line 470, in _quantize_and_evaluate
    quantized_model = quantization_algo(model)
  File "/opt/intel/openvino/deployment_tools/tools/post_training_optimization_toolkit/compression/algorithms/quantization/accuracy_aware/algorithm.py", line 458, in _quantize_model
    return self._quantization_algo.run(model)
  File "/opt/intel/openvino/deployment_tools/tools/post_training_optimization_toolkit/compression/algorithms/quantization/default/algorithm.py", line 99, in run
    model = algo.run(model)
  File "/opt/intel/openvino/deployment_tools/tools/post_training_optimization_toolkit/compression/algorithms/quantization/minmax/algorithm.py", line 63, in run
    self._config)
  File "/opt/intel/openvino/deployment_tools/tools/post_training_optimization_toolkit/compression/algorithms/quantization/fake_quantize.py", line 278, in get_quantized_model
    weights_stats = compute_weights_stats(model, weights_stats_layout)
  File "/opt/intel/openvino/deployment_tools/tools/post_training_optimization_toolkit/compression/algorithms/quantization/fake_quantize.py", line 307, in compute_weights_stats
    weights_stats[node.name][stat_name] = stat_fn(weights)
  File "/opt/intel/openvino/deployment_tools/tools/post_training_optimization_toolkit/compression/statistics/statistics.py", line 38, in __call__
    return self.compute(*argv, **kwargs)
  File "/opt/intel/openvino/deployment_tools/tools/post_training_optimization_toolkit/compression/statistics/statistics.py", line 49, in compute
    return self.func(*(input_tensor + self.argv), **self.kwargs)
  File "/opt/intel/openvino/deployment_tools/tools/post_training_optimization_toolkit/compression/statistics/functions/weights.py", line 72, in abs_max_per_filter
    return max_per_filter(np.abs(weights))
  File "/opt/intel/openvino/deployment_tools/tools/post_training_optimization_toolkit/compression/statistics/functions/weights.py", line 62, in max_per_filter
    return calculate_per_filter_stats(weights, np.max)
  File "/opt/intel/openvino/deployment_tools/tools/post_training_optimization_toolkit/compression/statistics/functions/weights.py", line 31, in calculate_per_filter_stats
    t = np.reshape(weights, (weights.shape[0], -1))
IndexError: tuple index out of range
```
Actually, I see above error in Default Quantization mode too while running model compression step. 

```
class MyDataLoader(DataLoader):

    def __init__(self, config):

        super().__init__(config)
        self.images = []
        self.labels = [] 
        
        idx=0 
          img_list_file='image_list_hpatches_sequences.txt'
          with open(img_list_file) as f:
              img_list=f.readlines()
              img_list=sorted(img_list)
              for img_path in img_list:
                  img_path=img_path[:-1]
                  img = Image.open(img_path).convert('RGB')
                  W, H = img.size
                  img = norm_RGB(img)[None]
                  img = F.interpolate(img, (580, 905), mode='bilinear', align_corners=False) #torch.Size([1, 3, 580, 905])
                  self.images.append(img)
                  im_idx=img_path.split('/')[-1].replace('.ppm','')
                  img_root_path = '/'.join(img_path.split('/')[:-1])+'/' 
                  self.labels.append((im_idx, img_root_path, W, H)) 
                  
                  idx += 1

        self.items = np.arange(idx - 1)
        print(bcolors.UNDERLINE + "\nQuantizing FP32 OpenVINO model to INT8\n" + bcolors.ENDC)
        print(bcolors.OKBLUE + "There are {:,} samples in the test dataset ".format(len(self.items)) + bcolors.ENDC)
        self.batch_size = 1

    def set_subset(self, indices):
        self._subset = None

    @property
    def batch_num(self):
        return ceil(self.size / self.batch_size)

    @property
    def size(self):
        return self.items.shape[0]

    def __len__(self):
        return self.size

    def __getitem__(self, item): 
 
        img=self.images[self.items[item]]
        label=self.labels[self.items[item]]

        return (item, label), img 

class NonMaxSuppression (torch.nn.Module):
    def __init__(self, rel_thr=0.7, rep_thr=0.7):
        nn.Module.__init__(self) 
         ...
    def forward(self, reliability, repeatability): 
         ...
class MyMetric(Metric):
    def __init__(self):
        super().__init__()
        self.name = "Accuracy"
        self._values = []
        self.lastValue=0
        self.round = 1
        self.detector = NonMaxSuppression(rel_thr = 0.7, rep_thr = 0.7 )
        self.firstOutput=[]
        self.secondOutput=[]
        self.index=0

    @property
    def value(self):
        if len(self._values)>0:
            return {self.name: [self._values[-1]]}
        else:
            print('self.index: ', self.index, 'len(self._values) == 0! / self._values : ', self._values, 'self.lastValue : ', self.lastValue)
            return {self.name: [self.lastValue]}

    @property
    def avg_value(self):
        if len(self._values)>0:
            value = np.ravel(self._values).mean()
            print("Round #{}    Mean {} = {}".format(self.round, self.name, value))
            #print("{} = {}".format(self.name, sum(self._values) / len(self._values)))
            self.round += 1

            return {self.name: value}
        else:
            value = self.lastValue
            print("Round #{}    Mean {} = {}".format(self.round, self.name, value))
            #print("{} = {}".format(self.name, sum(self._values) / len(self._values)))
            self.round += 1            
            return {self.name: value}

    def update(self, outputs, labels):  
        if (self.index % 2 == 0):
            self.firstOutput=[outputs, labels[0]]
        else:
            self.secondOutput=[outputs, labels[0]]
  
          metric = benchmark_features()  # this comes from a normal evaluation code           
          self._values.append(metric)

    def reset(self):
        """ Resets collected matches """
        self._values = []

    @property
    def higher_better(self):
        """Attribute whether the metric should be increased"""
        return False # as my metric is for getting "error" not "score".

    def get_attributes(self):
        return {self.name: {"direction": "higher-better", "type": ""}}
```
Please help me!
Plus, how can I print some debugging hint messages or print POT progress verbosely?
My configurations are simple 
```

model_config = Dict({
    "model_name": os.path.splitext(args.xml_file)[0],
    "model": args.xml_file,
    "weights": args.bin_file
})

engine_config = Dict({
    "device": "CPU",
    "stat_requests_number": 4,
    "eval_requests_number": 4,
    "print_progress" : True
})

dataset_config = {
    "images": "image",
    "labels": "label"
}

default_quantization_algorithm = [
    {
        "name": "DefaultQuantization",
        "params": {
            "target_device": "CPU",
            "preset": "performance",
            # "stat_subset_size": 10
            "print_progress" : True
        }
    }
]

accuracy_aware_quantization_algorithm = [
    {
        "name": "AccuracyAwareQuantization",  # compression algorithm name
        "params": {
            "target_device": "CPU",
            "preset": "performance",
            "stat_subset_size": 10,
            "metric_subset_ratio": 0.5,
            # A part of the validation set that is used to compare full-precision and quantized models
            "ranking_subset_size": 300,
            # A size of a subset which is used to rank layers by their contribution to the accuracy drop
            "max_iter_num": 10,
            # Maximum number of iterations of the algorithm (maximum of layers that may be reverted back to full-precision)
            "maximal_drop": args.maximum_metric_drop,
            # Maximum metric drop which has to be achieved after the quantization
            "drop_type": "absolute",  # Drop type of the accuracy metric: relative or absolute (default)
            "use_prev_if_drop_increase": True,
            # Whether to use NN snapshot from the previous algorithm iteration in case if drop increases
            "base_algorithm": "DefaultQuantization",  # Base algorithm that is used to quantize model at the beginning
            "print_progress" : True
        }
    }
]
```

**Comment by ilya-lavrenov** [comment]
Cc @AlexKoff88

**Comment by dedoogong** [comment]
I tried to print the weight values as below code and saw some weight of a layer is modified to 1e-12.
```
def calculate_per_filter_stats(weights, fn):
    """ Calculates per-filter statistics for weights using a specific function
    :param weights: model layer weights
    :param fn: function to calculate per-filter statistics
    :return statistics generated by fn
    """
    if len(weights.shape) == 1:
        print(weights[0], weights.shape)
    elif len(weights.shape) == 2:
        print(weights[0,:], weights.shape)
    elif len(weights.shape) == 3:
        print(weights[0,0,:], weights.shape)
    elif len(weights.shape) == 4:
        print(weights[0,0,0,:], weights.shape)
    else:
        print(weights, (weights.shape))
    t = np.reshape(weights, (weights.shape[0], -1))
    return fn(t, axis=1)
```
below is the whole printed values.
[1.] (1, 1, 1, 1)
[0.9966034  0.53278965 0.10373581] (48, 3, 3, 3)
[0.0611091  0.02412635] (192, 192, 2, 2)
[0.09748918] (2, 128, 1, 1)
[0.01203304 0.01828328] (128, 192, 2, 2)
[0.00044212 0.01363671 0.03863452] (96, 48, 3, 3)
[0.06255839 0.02859698 0.07023966] (96, 96, 3, 3)
1e-12 ()

**Comment by AlexKoff88** [comment]
@dedoogong, thanks for reporting the issue. We will look at it.

In the meantime, can you try "MinMaxQuantization" method instead of the "DefaultQuantization" method?

So, your config should look like this:

default_quantization_algorithm = [
    {
        "name": "**MinMaxQuantization**",
        "params": {
            "target_device": "CPU",
            "preset": "performance",
            # "stat_subset_size": 10
            "print_progress" : True
        }
    }
]

**Comment by dedoogong** [comment]
Thank you for kind reply! Yes I tried your suggestion but I got the same error;
Below is the log;
```
Quantizing FP32 OpenVINO model to INT8

There are 647 samples in the test dataset 
Accuracy-aware quantization method
08:19:02 accuracy_checker WARNING: quantize.py:145: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:766.)
  return maxima.nonzero().t()[2:4]

index :  2  metric  :  68.834203794497  self.lastValue :  68.834203794497
index :  8  metric  :  142.20228903286582  self.lastValue :  142.20228903286582
index :  14  metric  :  71.55138843238672  self.lastValue :  71.55138843238672
...
...
index :  632  metric  :  139.75350959909954  self.lastValue :  139.75350959909954
index :  638  metric  :  174.48644756529544  self.lastValue :  174.48644756529544
index :  644  metric  :  228.11963083147103  self.lastValue :  228.11963083147103
Round #1    Mean Accuracy = 149.28721726188328
metric_results_FP32 Done 
compressed_model Start! 
self.index:  648 len(self._values) == 0! / self._values :  [] self.lastValue :  228.11963083147103
self.index:  649 len(self._values) == 0! / self._values :  [] self.lastValue :  228.11963083147103 
...
...
self.index:  1294 len(self._values) == 0! / self._values :  [] self.lastValue :  228.11963083147103
Round #2    Mean Accuracy = 228.11963083147103
Round #3    Mean Accuracy = 228.11963083147103

[0.08090552 0.01859402 0.04378757] (48, 48, 3, 3)
[0.09748918] (2, 128, 1, 1)
[1.] (1, 1, 1, 1)
[0.01456609 0.01441863 0.00875619] (192, 192, 3, 3)
[0.06255839 0.02859698 0.07023966] (96, 96, 3, 3)
[0.00604426] (1, 128, 1, 1)
[0.01203304 0.01828328] (128, 192, 2, 2)
[0.9966034  0.53278965 0.10373581] (48, 3, 3, 3)
[0.00044212 0.01363671 0.03863452] (96, 48, 3, 3)
[0.0611091  0.02412635] (192, 192, 2, 2)
[0.05444468 0.03456011] (192, 192, 2, 2)
[0.03866693 0.00778453 0.00810784] (192, 96, 3, 3)
1e-12 ()

Traceback (most recent call last):
...
...
  File "/opt/intel/openvino/deployment_tools/tools/post_training_optimization_toolkit/compression/statistics/functions/weights.py", line 41, in calculate_per_filter_stats
    t = np.reshape(weights, (weights.shape[0], -1))
IndexError: tuple index out of range

```

**Comment by IndiraSalyahova** [comment]
Problem with Maximum and Minimum operations during quantization.
This will be fixed in POT 2021.4.
Now you can try to fix it yourself add 
1) /opt/intel/openvino/deployment_tools/tools/post_training_optimization_toolkit/compression/graph/passes.py 
Add `'Minimum', 'Maximum'` in array "jump_single_branch_ops" line 198

```python
jump_single_branch_ops = ['ReduceMax', 'MaxPool', 'Reshape', 'Flatten', 'Squeeze', 'Unsqueeze', 'Interpolate',
                              'Split', 'Crop', 'ReduceMean', 'AvgPool', 'Result', 'Tile', 'Transpose', 'StridedSlice',
                              'VariadicSplit', 'ShuffleChannels', 'Broadcast', 'Pad', 'Minimum', 'Maximum']
```

2) /opt/intel/openvino/deployment_tools/tools/post_training_optimization_toolkit/compression/graph/special_operations.py 
Add  ` {'type': 'Minimum'}, {'type': 'Maximum'}` in QUANTIZE_AGNOSTIC_OPERATIONS line 16

**Comment by dedoogong** [comment]
thank you really for your hard effort!!!
I will try your guide and report the result! it would take some time as I'm integrating openvino code with libtorch. 
thank you again!

**Comment by AlexKoff88** [comment]
Hi @dedoogong,

The work you are doing is really interesting. Is it an open-source project? If yes, can you share it?

**Comment by dedoogong** [comment]
Hi @AlexKoff88 
Oh, sorry it's not open source project but it's a company proejct where I joined in. 
I've been trying several optimization frame works to speed up the open/closed models using openvino, TensorRT, TFlite, libtorch, TF C++, Metal, so on. 

Thank you~!

**Comment by AlexKoff88** [comment]
Ok. No problem.

Can you close the issue if there are no questions?
