### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by suri21483** [openvinotoolkit/openvino#6254]
Hi, 

i am using Openvino version 2021.3.394 and using Ubuntu 20 version.

i am trying to run the accuracy_checker, following the README.md inside it and also inside the sample directory.

accuracy_check -c sample/sample_config.yml -m data/test_models -s sample

I am getting the following errors, can you please support to resolve this?

Processing info:
model: SampLeNet_example
launcher: dlsdk
device: CPU
dataset: sample_dataset
OpenCV version: 4.5.2-openvino
Annotation conversion for sample_dataset dataset has been started
Parameters to be used for conversion:
converter: cifar
data_batch_file: sample/cifar-10-batches-py/test_batch
convert_images: True
converted_images_dir: sample/sample_dataset/test
num_classes: 10
Annotation conversion for sample_dataset dataset has been finished
IE version: 2.1.2021.3.0-2787-60059f2c755-releases/2021/3
Loaded CPU plugin version:
    CPU - MKLDNNPlugin: 2.1.2021.3.0-2787-60059f2c755-releases/2021/3
21:48:38 accuracy_checker ERROR: Model optimizer not found. Please set MO_DIR environment variable to model optimizer folder installation or refer to help for command line options for providing Model optimizer
Traceback (most recent call last):
  File "/opt/intel/openvino_2021/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/main.py", line 386, in main
    evaluator = evaluator_class.from_configs(config_entry)
  File "/opt/intel/openvino_2021/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/evaluators/model_evaluator.py", line 81, in from_configs
    launcher = create_launcher(launcher_config, model_name, **launcher_kwargs)
  File "/opt/intel/openvino_2021/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/launcher.py", line 312, in create_launcher
    return Launcher.provide(
  File "/opt/intel/openvino_2021/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/dependency.py", line 75, in provide
    return root_provider(*args, **kwargs)
  File "/opt/intel/openvino_2021/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py", line 164, in __init__
    self._model, self._weights = DLSDKLauncher.convert_model(self.config, dlsdk_launcher_config.framework)
  File "/opt/intel/openvino_2021/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/dlsdk_launcher.py", line 520, in convert_model
    return convert_model(
  File "/opt/intel/openvino_2021/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/launcher/model_conversion.py", line 58, in convert_model
    raise EnvironmentError(
OSError: Model optimizer not found. Please set MO_DIR environment variable to model optimizer folder installation or refer to help

regards,
Suresh

**Comment by suri21483** [comment]
In the README.md file inside the sample directory, correct name should be used. 

model: SampleNet.xml
weights: SampleNet.bin

we need to use SampLeNet.xml and SampLeNet.bin
