### ISSUE TITLE
Error when doing inference with "HETERO:GPU,CPU"

### ISSUE THREAD

**Issue by MouhammadEV** [openvinotoolkit/openvino#6645]
Hello,

 OS: Windows 10
openvino: 2021.4

I trained a mask rcnn model using tf OD API 2. I was able to use the openvino model optimizer to get the IR model.

I checked the model using the benchmark_tool in python with both Plugins"CPU" and "GPU" and both worked fine.

But when trying the "Hetero" plugin I get the following exception:

```[Step 1/11] Parsing and validating input arguments
[ WARNING ]  -nstreams default value is determined automatically for a device. Although the automatic selection usually provides a reasonable performance, but it still may be non-optimal for some cases, for more information look at README.
[Step 2/11] Loading Inference Engine
[ INFO ] InferenceEngine:
         API version............. 2021.4.0-3839-cd81789d294-releases/2021/4
[ INFO ] Device info
         CPU
         MKLDNNPlugin............ version 2.1
         Build................... 2021.4.0-3839-cd81789d294-releases/2021/4
         GPU
         clDNNPlugin............. version 2.1
         Build................... 2021.4.0-3839-cd81789d294-releases/2021/4
         HETERO
         heteroPlugin............ version 2.1
         Build................... 2021.4.0-3839-cd81789d294-releases/2021/4

[Step 3/11] Setting device configuration
[Step 4/11] Reading network files
[ INFO ] Read network took 75.03 ms
[Step 5/11] Resizing network to match image sizes and given batch
[ INFO ] Network batch size: 1
[Step 6/11] Configuring input of the model
[ INFO ] Network input 'image_info' precision FP32, dimensions (NC): 1 3
[ INFO ] Network input 'input_tensor' precision U8, dimensions (NCHW): 1 3 572 768
[ INFO ] Network output 'masks' precision FP32, dimensions (NCHW): 2 1 33 33
[ INFO ] Network output 'reshape_do_2d' precision FP32, dimensions (NC): 2 7
[Step 7/11] Loading the model to the device
[ ERROR ] Function contains several inputs and outputs with one friendly name!
Traceback (most recent call last):
  File "C:\Program Files (x86)\Intel\openvino_2021.4.582\python\python3.6\openvino\tools\benchmark\main.py", line 255, in run
    exe_network = benchmark.load_network(ie_network)
  File "C:\Program Files (x86)\Intel\openvino_2021.4.582\python\python3.6\openvino\tools\benchmark\benchmark.py", line 63, in load_network
    num_requests=1 if self.api_type == 'sync' else self.nireq or 0)
  File "ie_api.pyx", line 367, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 379, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: Function contains several inputs and outputs with one friendly name!
```

I ran the following command:

```
(tensorflow2) C:\Program Files (x86)\Intel\openvino_2021.4.582\deployment_tools\tools\benchmark_tool>python benchmark_app.py 
-m "C:\Users\Mouhammad\Documents\Intel\OpenVINO\openvino_models\ir\public\saved_model_smaller_FP16\saved_model.xml" 
-d HETERO:CPU,GPU 
-b 1 
-api sync
```

I also tried one of the mask rcnn models from the Open Model Zoo 
[https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/mask_rcnn_resnet50_atrous_coco](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/mask_rcnn_resnet50_atrous_coco
)

After converting it to IR format and testing it with benchmark_app using HETERO plugin, I got the same error:
```
[Step 1/11] Parsing and validating input arguments
[ WARNING ]  -nstreams default value is determined automatically for a device. Although the automatic selection usually provides a reasonable performance, but it still may be non-optimal for some cases, for more information look at README.
[Step 2/11] Loading Inference Engine
[ INFO ] InferenceEngine:
         API version............. 2021.4.0-3839-cd81789d294-releases/2021/4
[ INFO ] Device info
         CPU
         MKLDNNPlugin............ version 2.1
         Build................... 2021.4.0-3839-cd81789d294-releases/2021/4
         GPU
         clDNNPlugin............. version 2.1
         Build................... 2021.4.0-3839-cd81789d294-releases/2021/4
         HETERO
         heteroPlugin............ version 2.1
         Build................... 2021.4.0-3839-cd81789d294-releases/2021/4

[Step 3/11] Setting device configuration
[Step 4/11] Reading network files
[ INFO ] Read network took 244.48 ms
[Step 5/11] Resizing network to match image sizes and given batch
[ INFO ] Network batch size: 1
[Step 6/11] Configuring input of the model
[ INFO ] Network input 'image_info' precision FP32, dimensions (NC): 1 3
[ INFO ] Network input 'image_tensor' precision U8, dimensions (NCHW): 1 3 800 1365
[ INFO ] Network output 'masks' precision FP32, dimensions (NCHW): 100 90 33 33
[ INFO ] Network output 'reshape_do_2d' precision FP32, dimensions (NC): 100 7
[Step 7/11] Loading the model to the device
[ ERROR ] Function contains several inputs and outputs with one friendly name!
Traceback (most recent call last):
  File "C:\Program Files (x86)\Intel\openvino_2021.4.582\python\python3.6\openvino\tools\benchmark\main.py", line 255, in run
    exe_network = benchmark.load_network(ie_network)
  File "C:\Program Files (x86)\Intel\openvino_2021.4.582\python\python3.6\openvino\tools\benchmark\benchmark.py", line 63, in load_network
    num_requests=1 if self.api_type == 'sync' else self.nireq or 0)
  File "ie_api.pyx", line 367, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 379, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: Function contains several inputs and outputs with one friendly name!
```

But when testing it with CPU and GPU plugin seperatly it worked fine.

Is it possible that the HETERO Plugin doesn't support the mask rcnn model? or am I doing something wrong?
I hope someone could help me with this?

Thanks and regard,
Mouhammad

**Comment by zulkifli-halim** [comment]
Hi @MouhammadEV, the development will check on this and get back to you soon. 

Ref. 60378

**Comment by ilya-lavrenov** [comment]
@MouhammadEV could you please try current master?

**Comment by MouhammadEV** [comment]
I am not able to compile the master:

I used the follwoing command to compile:
`"C:\Program Files\CMake\bin\cmake.exe" -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release ..`
`"C:\Program Files\CMake\bin\cmake.exe" --build . --config Release --verbose -j8`

I got the following output:

`Fehler beim Buildvorgang.

       "C:\External_Libraries_Source\openvin-master_2021-09-24\openvino\build\ALL_BUILD.vcxproj" (Standardziel) (1) ->
       "C:\External_Libraries_Source\openvin-master_2021-09-24\openvino\build\inference-engine\src\cldnn_engine\clDNNPlugin.vcxproj" (Standardziel) (9) ->
       "C:\External_Libraries_Source\openvin-master_2021-09-24\openvino\build\inference-engine\thirdparty\clDNN\src\clDNN_lib.vcxproj" (Standardziel) (67) ->
       "C:\External_Libraries_Source\openvin-master_2021-09-24\openvino\build\inference-engine\thirdparty\clDNN\runtime\cldnn_runtime.vcxproj" (Standardziel) (75) ->
       "C:\External_Libraries_Source\openvin-master_2021-09-24\openvino\build\thirdparty\onednn_gpu_build.vcxproj" (Standardziel) (77) ->
       (CustomBuild Ziel) ->
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Der benutzerdefinierte Build fü
       r "C:\External_Libraries_Source\openvin-master_2021-09-24\openvino\build\CMakeFiles\8b08bde494be9bd424b81413a7b561b3\onednn_gpu_build-install.rule;C:\External_Libraries_Source
       \openvin-master_2021-09-24\openvino\build\CMakeFiles\f85244fb16f7ceab51d2934b45c7a32e\onednn_gpu_build-complete.rule;C:\External_Libraries_Source\openvin-master_2021-09-24\ope
       nvino\build\CMakeFiles\c0521d2d12dd9607f936d2082ee6f001\onednn_gpu_build.rule" wurde mit dem Code 1 beendet. [C:\External_Libraries_Source\openvin-master_2021-09-24\openvino\b
       uild\thirdparty\onednn_gpu_build.vcxproj]

    0 Warnung(en)
    1 Fehler
`

**Comment by ilya-lavrenov** [comment]
There is no error message in output log. Could you please provide exact error like line of code, etc?

**Comment by MouhammadEV** [comment]
Here is the full output of the build process

[build_output.txt](https://github.com/openvinotoolkit/openvino/files/7227165/build_output.txt)

**Comment by MouhammadEV** [comment]
I solved the compilation problem.
I just had to copy the file:
`"C:\External_Libraries_Source\openvin-master_2021-09-24\openvino\build\thirdparty\onednn_gpu_build\src\Release\onednn_gpu.lib"`
To
`"C:\External_Libraries_Source\openvin-master_2021-09-24\openvino\build\thirdparty\onednn_gpu_build\src\onednn_gpu.lib"`

**Comment by MouhammadEV** [comment]
The command:

```
python benchmark_app.py 
-m "C:\Users\Mouhammad\Documents\Intel\OpenVINO\openvino_models\ir\public\saved_model_smaller_FP16\saved_model.xml" 
-d HETERO:CPU,GPU 
-b 1 
-api sync
```

is working.


But when using` "-d HETERO:GPU,CPU"` instead of ` "-d HETERO:CPU,GPU"` I am getting the error

```
[Step 1/11] Parsing and validating input arguments
[ WARNING ]  -nstreams default value is determined automatically for a device. Although the automatic selection usually provides a reasonable performance, but it still may be non-optimal for some cases, for more information look at README.
[Step 2/11] Loading Inference Engine
[ INFO ] InferenceEngine:
         API version............. custom_master_920e58caba72bca6387b0c28e8dd7bb02f02ec9b
[ INFO ] Device info
         CPU
         MKLDNNPlugin............ version 2.1
         Build................... custom_master_920e58caba72bca6387b0c28e8dd7bb02f02ec9b
         GPU
         clDNNPlugin............. version 2.1
         Build................... custom_master_920e58caba72bca6387b0c28e8dd7bb02f02ec9b
         HETERO
         heteroPlugin............ version 2.1
         Build................... custom_master_920e58caba72bca6387b0c28e8dd7bb02f02ec9b

[Step 3/11] Setting device configuration
[Step 4/11] Reading network files
[ INFO ] Read network took 85.00 ms
[Step 5/11] Resizing network to match image sizes and given batch
[ INFO ] Network batch size: 1
[Step 6/11] Configuring input of the model
[ INFO ] Network input 'image_info' precision FP32, dimensions (NC): 1 3
[ INFO ] Network input 'input_tensor' precision U8, dimensions (NCHW): 1 3 572 768
[ INFO ] Network output 'masks' precision FP32, dimensions (NCHW): 2 1 33 33
[ INFO ] Network output 'reshape_do_2d' precision FP32, dimensions (NC): 2 7
[Step 7/11] Loading the model to the device
[ ERROR ] Unsupported operation of type: Gather name: Reshape_Transpose_Class/ShapeGather
Details:
Doesn't support op with dynamic shapes
Cannot fallback on ngraph reference implementation (Ngraph::Node::evaluate() is not implemented)
Traceback (most recent call last):
  File "C:\External_Libraries_Source\openvin-master_2021-09-24\installed\python\python3.6\openvino\tools\benchmark\main.py", line 262, in run
    exe_network = benchmark.load_network(ie_network)
  File "C:\External_Libraries_Source\openvin-master_2021-09-24\installed\python\python3.6\openvino\tools\benchmark\benchmark.py", line 66, in load_network
    num_requests=1 if self.api_type == 'sync' else self.nireq or 0)
  File "ie_api.pyx", line 374, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 391, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: Unsupported operation of type: Gather name: Reshape_Transpose_Class/ShapeGather
Details:
Doesn't support op with dynamic shapes
Cannot fallback on ngraph reference implementation (Ngraph::Node::evaluate() is not implemented)
```

**Comment by zulkifli-halim** [comment]
@MouhammadEV. it seems like some of the model layers are not supported by the GPU plugin.

**Comment by chccc1994** [comment]
> I solved the compilation problem. I just had to copy the file: `"C:\External_Libraries_Source\openvin-master_2021-09-24\openvino\build\thirdparty\onednn_gpu_build\src\Release\onednn_gpu.lib"` To `"C:\External_Libraries_Source\openvin-master_2021-09-24\openvino\build\thirdparty\onednn_gpu_build\src\onednn_gpu.lib"`

I have the same problem，But compiled without this  **“openvin-master_2021-09-24\openvino\build\thirdparty\onednn_gpu_build\src\Release\onednn_gpu.lib"**
