### ISSUE TITLE
[Bug] Error when using benchmark_app to test ssdlite_mobilenet_v2 with "HETERO:GPU,CPU" 

### ISSUE THREAD

**Issue by b04505009** [openvinotoolkit/openvino#6811]
##### System information (version)

- OpenVINO => 2021.4
- Operating System / Platform => Ubuntu 20.04
- Compiler => gcc
- Problem classification: Hetero plugin
- Framework: TensorFlow 
- Model name: ssd_mobilenet_v2 

##### Detailed description
I tried to use benchmark_app to test ssdlite_mobilenet_v2 in open_model_zoo with "HETERO:GPU,CPU", but it returned with error
```sh
[ ERROR ] Ngraph operation Transpose with name BoxPredictor_0/ClassPredictor/BiasAdd/Add/Transpose has dynamic output shape on 0 port, but CPU plug-in supports only static shape
Traceback (most recent call last):
  File "/opt/intel/openvino_2021/python/python3.8/openvino/tools/benchmark/main.py", line 255, in run
    exe_network = benchmark.load_network(ie_network)
  File "/opt/intel/openvino_2021/python/python3.8/openvino/tools/benchmark/benchmark.py", line 60, in load_network
    exe_network = self.ie.load_network(ie_network,
  File "ie_api.pyx", line 367, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 379, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: Ngraph operation Transpose with name BoxPredictor_0/ClassPredictor/BiasAdd/Add/Transpose has dynamic output shape on 0 port, but CPU plug-in supports only static shape
```

##### Steps to reproduce
Download and convert ssdlite_mobilenet_v2 from open_model_zoo
```
python /opt/intel/openvino_2021/deployment_tools/tools/benchmark_tool/benchmark_app.py \
-m ~/open_model_zoo/public/ssdlite_mobilenet_v2/FP16/ssdlite_mobilenet_v2.xml \
-d HETERO:GPU,CPU
```

**Comment by zulkifli-halim** [comment]
Hello @b04505009. This is a known issue and we're trying to fix it as soon as possible. 

Ref. 60378

**Comment by zulkifli-halim** [comment]
@b04505009 could you please try the current master?
