### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by zongking123** [openvinotoolkit/openvino#7591]
##### System information (version)
- OpenVINO => 2021.4.689
- Operating System / Platform => Mac 10.14.6 (18G9216)
- import cv2 error
Traceback (most recent call last):
  File "./image_inpainting_demo.py", line 19, in <module>
    import cv2
  File "/opt/intel/openvino_2021.4.689/python/python3/cv2/__init__.py", line 129, in <module>
    bootstrap()
  File "/opt/intel/openvino_2021.4.689/python/python3/cv2/__init__.py", line 112, in bootstrap
    import cv2
ImportError: dlopen(/opt/intel/openvino_2021.4.689/python/python3/cv2/python-3/cv2.so, 2): Symbol not found: _objc_opt_respondsToSelector
  Referenced from: /opt/intel/openvino_2021.4.689/python/python3/cv2/python-3/../../../../opencv/lib/libopencv_highgui.4.5.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib
 in /opt/intel/openvino_2021.4.689/python/python3/cv2/python-3/../../../../opencv/lib/libopencv_highgui.4.5.dylib

**Comment by Iffa-Meah** [comment]
Hi,

From what I can see, you are trying to run ./image_inpainting_demo.py and encountered "import cv2 error", right?

Just to clarify, are you building from source or using OpenVINO toolkit?
If you are building from source, to build the Python API wrapper, you must enable the -**DENABLE_PYTHON=ON** option
You may refer [here](https://github.com/openvinotoolkit/openvino/wiki/BuildingForMacOS).

If you are using the toolkit, everything should be automatically installed by the installer. 
Ensure to run the setupvars before running any other things.
You may refer [here](https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_macos.html).

**Comment by alalek** [comment]
> Mac 10.14.6 (18G9216)

> libopencv_highgui.4.5.dylib (which was built for Mac OS X 10.15)

Refer to this document: https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_macos.html

> The Intel® Distribution of OpenVINO™ is supported on macOS* 10.15.x versions.

---

You need re-build OpenCV for your system version (check opencv/build_params.txt for used options) or try to use [`opencv-python` from PyPi](https://pypi.org/project/opencv-python/) (community version - some Intel-specific optimizations or integration with InferenceEngine may be unavailable).

BTW, do not forget to remove/rename "opencv" directory in openvino (or uninstall "opencv" component) to use own opencv version.
