### ISSUE TITLE
[custom op] Attribute adapter can not be found for output_size parameter

### ISSUE THREAD

**Issue by handoku** [openvinotoolkit/openvino#7678]
I have added a custom operation following [this](https://docs.openvinotoolkit.org/2021.2/openvino_docs_HOWTO_Custom_Layers_Guide.html#inference_engine_extension_implementation).

however, I get the error when load model with inference engine (test with benchmark_app.py):
```
[Step 1/11] Parsing and validating input arguments
/opt/intel/openvino/python/python3.6/openvino/tools/benchmark/main.py:29: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn(" -nstreams default value is determined automatically for a device. "
[ WARNING ]  -nstreams default value is determined automatically for a device. Although the automatic selection usually provides a reasonable performance, but it still may be non-optimal for some cases, for more information look at README. 
[Step 2/11] Loading Inference Engine
[ INFO ] CPU extensions is loaded ../ie_extension/build/libautovision_extension.so
[ INFO ] InferenceEngine:
         API version............. 2.1.2021.2.0-1877-176bdf51370-releases/2021/2
[ INFO ] Device info
         CPU
         MKLDNNPlugin............ version 2.1
         Build................... 2021.2.0-1877-176bdf51370-releases/2021/2

[Step 3/11] Setting device configuration
[ WARNING ] -nstreams default value is determined automatically for CPU device. Although the automatic selection usually provides a reasonable performance,but it still may be non-optimal for some cases, for more information look at README.
[Step 4/11] Reading network files
[ ERROR ] Error IR reading. Attribute adapter can not be found for output_size parameter
Traceback (most recent call last):
  File "/opt/intel/openvino/python/python3.6/openvino/tools/benchmark/main.py", line 182, in run
    ie_network = benchmark.read_network(args.path_to_model)
  File "/opt/intel/openvino/python/python3.6/openvino/tools/benchmark/benchmark.py", line 66, in read_network
    ie_network = self.ie.read_network(model_filename, weights_filename)
  File "ie_api.pyx", line 261, in openvino.inference_engine.ie_api.IECore.read_network
  File "ie_api.pyx", line 285, in openvino.inference_engine.ie_api.IECore.read_network
RuntimeError: Error IR reading. Attribute adapter can not be found for output_size parameter
```

Could you help me, what is the `attribute adapter`, did I miss something?

or just because my converted IR model is incorrect? here is IR model.xml:
```
<?xml version="1.0" ?>
<net name="ada_avg_pool" version="10">
	<layers>
		<layer id="0" name="input" type="Parameter" version="opset1">
			<data element_type="f32" shape="1,1,4,4"/>
			<output>
				<port id="0" precision="FP32">
					<dim>1</dim>
					<dim>1</dim>
					<dim>4</dim>
					<dim>4</dim>
				</port>
			</output>
		</layer>
		<layer id="1" name="out" type="adaptive_avg_pool2d" version="autovision_extension">
			<data output_size="[2 2]"/>
			<input>
				<port id="0">
					<dim>1</dim>
					<dim>1</dim>
					<dim>4</dim>
					<dim>4</dim>
				</port>
			</input>
			<output>
				<port id="1" precision="FP32">
					<dim>1</dim>
					<dim>1</dim>
					<dim>2</dim>
					<dim>2</dim>
				</port>
			</output>
		</layer>
		<layer id="2" name="out/sink_port_0" type="Result" version="opset1">
			<input>
				<port id="0">
					<dim>1</dim>
					<dim>1</dim>
					<dim>2</dim>
					<dim>2</dim>
				</port>
			</input>
		</layer>
	</layers>
	<edges>
		<edge from-layer="0" from-port="0" to-layer="1" to-port="0"/>
		<edge from-layer="1" from-port="1" to-layer="2" to-port="0"/>
	</edges>
	<meta_data>
		<MO_version value="2021.2.0-1877-176bdf51370-releases/2021/2"/>
		<cli_parameters>
			<caffe_parser_path value="DIR"/>
			<data_type value="float"/>
			<disable_nhwc_to_nchw value="False"/>
			<disable_omitting_optional value="False"/>
			<disable_resnet_optimization value="False"/>
			<disable_weights_compression value="False"/>
			<enable_concat_optimization value="False"/>
			<enable_flattening_nested_params value="False"/>
			<enable_ssd_gluoncv value="False"/>
			<extensions value="DIR"/>
			<framework value="onnx"/>
			<freeze_placeholder_with_value value="{}"/>
			<generate_deprecated_IR_V7 value="False"/>
			<input_model value="DIR/ada_avg_pool.onnx"/>
			<input_model_is_text value="False"/>
			<k value="DIR/CustomLayersMapping.xml"/>
			<keep_shape_ops value="True"/>
			<legacy_mxnet_model value="False"/>
			<log_level value="ERROR"/>
			<mean_scale_values value="{}"/>
			<mean_values value="()"/>
			<model_name value="ada_avg_pool"/>
			<output_dir value="DIR"/>
			<placeholder_data_types value="{}"/>
			<progress value="False"/>
			<remove_memory value="False"/>
			<remove_output_softmax value="False"/>
			<reverse_input_channels value="False"/>
			<save_params_from_nd value="False"/>
			<scale_values value="()"/>
			<silent value="False"/>
			<static_shape value="False"/>
			<stream_output value="False"/>
			<unset unset_cli_parameters="batch, counts, disable_fusing, disable_gfusing, finegrain_fusing, input, input_checkpoint, input_meta_graph, input_proto, input_shape, input_symbol, mean_file, mean_file_offsets, move_to_preprocess, nd_prefix_name, output, placeholder_shapes, pretrained_model_name, saved_model_dir, saved_model_tags, scale, tensorboard_logdir, tensorflow_custom_layer_libraries, tensorflow_custom_operations_config_update, tensorflow_object_detection_api_pipeline_config, tensorflow_use_custom_operations_config, transformations_config"/>
		</cli_parameters>
	</meta_data>
</net>

```

**Comment by GlebKazantaev** [comment]
Looks like your operation has some unusual type so it was serialized like `[2 2]`. It would be really helpful if you attach the code of your extensions.

**Comment by handoku** [comment]
I found that too.

my extractor code:
```
from mo.front.common.partial_infer.utils import int64_array
from ...ops.adaptive_avg_pool2d import adaptive_avg_pool2d
from mo.front.extractor import FrontExtractorOp
from mo.front.onnx.extractors.utils import onnx_attr
from mo.utils.error import Error

class adaptive_avg_pool2d_extractor(FrontExtractorOp):
    op = "adaptive_avg_pool2d"
    enabled = True

    @classmethod
    def extract(cls, node):
        output_size = onnx_attr(node, 'output_size', 'ints', default=None, dst_type=int64_array)
        attrs = {
            "output_size" : output_size
        }
        adaptive_avg_pool2d.update_node_stat(node, attrs)
        return cls.enabled

```

ngraph op definition:
```
class Operation : public ngraph::op::Op {
public:
    static constexpr ngraph::NodeTypeInfo type_info{"adaptive_avg_pool2d", 1};
    const ngraph::NodeTypeInfo& get_type_info() const override { return type_info;  }

    Operation() = default;
    Operation(const ngraph::Output<ngraph::Node>& arg, const std::vector<int64_t>& output_size);
    void validate_and_infer_types() override;
    std::shared_ptr<ngraph::Node> clone_with_new_inputs(const ngraph::OutputVector& new_args) const override;
    bool visit_attributes(ngraph::AttributeVisitor& visitor) override;
    const std::vector<int64_t>& getOutputSizeAttr() const { return output_size;}
    bool evaluate(const ngraph::HostTensorVector& outputs,
                  const ngraph::HostTensorVector& inputs) const override;

private:
    std::vector<int64_t> output_size;
};
```

I found that I must use `std::vector<size_t> output_size` in ngraph op, and the serialized value must be `2,2` (in which case I hava to modify .xml manually because I can't get it with my extractor code, I also hava tried export `output_size` with int tuple which will result in `(2, 2)`, or np.array([x, x] , dtype=np.uint64) result in `[2 2]`). only in this case, the program runs well.

**Comment by GlebKazantaev** [comment]
To have correct attribute serialization you have to extend your MO operation class with supported_attrs method like this:
```py
    def supported_attrs(self):
        return [
            ('output_size', lambda node: ','.join([str(i) for i in node.output_size])),
        ]
```

You can find more information in ["Model Optimizer Operation"](https://docs.openvinotoolkit.org/2021.2/openvino_docs_MO_DG_prepare_model_customize_model_optimizer_Customize_Model_Optimizer.html#extension-operation) section.

**Comment by handoku** [comment]
yeah，I missed that part. Thanks.

**Comment by GlebKazantaev** [comment]
Great! If you don't have any questions could you please resolve this issue?
