### ISSUE TITLE
[Bug] Failed to convert onnx model using mo.py

### ISSUE THREAD

**Issue by liwang54321** [openvinotoolkit/openvino#7993]
I am using the ppyolov2 model of paddlepaddle. I used the following command to convert, but it failed. The log is as follows. How can I fix this problem? Thanks

```bash
(base) PS D:\Program Files (x86)\Intel\openvino_2021\deployment_tools\model_optimizer>  python mo_onnx.py --input_model=./rc.onnx --output_dir=D:\ --input_shape=[1,2],[1,3,640,640],[1,2] --input=im_shape,image,scale_factor
Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      D:\Program Files (x86)\Intel\openvino_2021\deployment_tools\model_optimizer\./rc.onnx
        - Path for generated IR:        D:\
        - IR output name:       rc
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         im_shape,image,scale_factor
        - Output layers:        Not specified, inherited from the model
        - Input shapes:         [1,2],[1,3,640,640],[1,2]
        - Mean values:  Not specified
        - Scale values:         Not specified
        - Scale factor:         Not specified
        - Precision of IR:      FP32
        - Enable fusing:        True
        - Enable grouped convolutions fusing:   True
        - Move mean values to preprocess section:       None
        - Reverse input channels:       False
ONNX specific parameters:
        - Inference Engine found in:    D:\Program Files (x86)\Intel\openvino_2021.4.689\python\python3.8\openvino
Inference Engine version:       2021.4.1-3926-14e67d86634-releases/2021/4
Model Optimizer version:        2021.4.1-3926-14e67d86634-releases/2021/4
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID (<class 'extensions.back.ClampNormalizer.ClampNormalizer'>)": Clamp node should have either min or max input used
[ ERROR ]  Traceback (most recent call last):
  File "D:\Program Files (x86)\Intel\openvino_2021\deployment_tools\model_optimizer\mo\utils\class_registration.py", line 278, in apply_transform
    for_graph_and_each_sub_graph_recursively(graph, replacer.find_and_replace_pattern)
  File "D:\Program Files (x86)\Intel\openvino_2021\deployment_tools\model_optimizer\mo\middle\pattern_match.py", line 46, in for_graph_and_each_sub_graph_recursively
    func(graph)
  File "D:\Program Files (x86)\Intel\openvino_2021\deployment_tools\model_optimizer\mo\utils\replacement_pattern.py", line 14, in find_and_replace_pattern
    apply_pattern(graph, **self.pattern(), action=self.replace_pattern)  # pylint: disable=no-member
  File "D:\Program Files (x86)\Intel\openvino_2021\deployment_tools\model_optimizer\mo\middle\pattern_match.py", line 83, in apply_pattern
    action(graph, match)
  File "D:\Program Files (x86)\Intel\openvino_2021\deployment_tools\model_optimizer\extensions\back\ClampNormalizer.py", line 52, in replace_pattern
    assert min_node is not None or max_node is not None, 'Clamp node should have either min or max input used'
AssertionError: Clamp node should have either min or max input used

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Program Files (x86)\Intel\openvino_2021\deployment_tools\model_optimizer\mo\main.py", line 394, in main
    ret_code = driver(argv)
  File "D:\Program Files (x86)\Intel\openvino_2021\deployment_tools\model_optimizer\mo\main.py", line 356, in driver
    ret_res = emit_ir(prepare_ir(argv), argv)
  File "D:\Program Files (x86)\Intel\openvino_2021\deployment_tools\model_optimizer\mo\main.py", line 252, in prepare_ir
    graph = unified_pipeline(argv)
  File "D:\Program Files (x86)\Intel\openvino_2021\deployment_tools\model_optimizer\mo\pipeline\unified.py", line 13, in unified_pipeline
    class_registration.apply_replacements(graph, [
  File "D:\Program Files (x86)\Intel\openvino_2021\deployment_tools\model_optimizer\mo\utils\class_registration.py", line 328, in apply_replacements
    apply_replacements_list(graph, replacers_order)
  File "D:\Program Files (x86)\Intel\openvino_2021\deployment_tools\model_optimizer\mo\utils\class_registration.py", line 314, in apply_replacements_list
    apply_transform(
  File "D:\Program Files (x86)\Intel\openvino_2021\deployment_tools\model_optimizer\mo\utils\logger.py", line 111, in wrapper
    function(*args, **kwargs)
  File "D:\Program Files (x86)\Intel\openvino_2021\deployment_tools\model_optimizer\mo\utils\class_registration.py", line 302, in apply_transform
    raise Exception('Exception occurred during running replacer "{} ({})": {}'.format(
Exception: Exception occurred during running replacer "REPLACEMENT_ID (<class 'extensions.back.ClampNormalizer.ClampNormalizer'>)": Clamp node should have either min or max input used

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------

```

**Comment by brmarkus** [comment]
Can you provide more details about your environment, please? Which operating system (MS-Windows looks like) are you using, on which HW, which OpenVINO version have you installed (pre-built version of OpenVINO or built from source)?

Could you provide more details about where to get the model-files (like rc.onnx) from - so that the reproduction and further analysis is using exactly the same as your are using?
