### ISSUE TITLE
[Question] How to cross compile OpenVINO for limited ARM platform

### ISSUE THREAD

**Issue by yeshuanova** [openvinotoolkit/openvino#8343]
I want to run OpenVINO with Neural Compute Stick 2 on an embedded linux system with Cortex-A53 and 2GB RAM.
But, when I build OpenVINO by this tutorial [BuildingForLinux](https://github.com/openvinotoolkit/openvino/wiki/BuildingForLinux) on this platform, building process is always failed. (I think problem is small RAM size)

I had built OpenVINO on Raspberry Pi 4B (8G RAM) and x86_86 linux system (13G RAM), and run program successfully.

Can I build OpenVINO and it's Python API wrapper on other system and run it on embedded system?

## Target Platform

- CPU: Cortex-A53
- Operating System/Platform => Ubuntu 18.04
- RAM => **2GB**
- GCC => 7.5
- Python => 3.6.9

## Build Platform (1): Desktop

- CPU: x86_64
- Operating System / Platform => Ubuntu 18.04
- GCC => 7.5
- Python 3.6.9

## Build Platform (2): Raspberry Pi 4B

- Operating System/Platform => Ubuntu MATE 20.04
- RAM: 8GB
- GCC: 7.5
- python 3.6.15

**Comment by Iffa-Meah** [comment]
Hi,

As a workaround, you could try to compile your IR model with the compile_tool on a higher computing capability device (In your case, make sure the device is running Linux OS).
Then, copy the compiled blob file to the target device, and import the blob.

You may refer [here](https://docs.openvino.ai/2021.4/openvino_inference_engine_tools_compile_tool_README.html?highlight=compile).

**Comment by yeshuanova** [comment]
Hi @Iffa-Meah 

I think this is not my problem. I need OpenVINO runtime library that can be executed on ARM device with NCS2, but official download site does not have support this platform. [Compile Tool](https://docs.openvino.ai/2021.4/openvino_inference_engine_tools_compile_tool_README.html?highlight=compile) need runtime library, so this method can't help me.

Now, I find this paper [BuildingForRaspbianStretchOS](https://github.com/openvinotoolkit/openvino/wiki/BuildingForRaspbianStretchOS#cross-compilation-using-docker) and show how to compile OpenVINO for ARM platform on x86_64 machine using docker.

I edit it's `Dockerfile` as

```dockerfile
FROM ubuntu:18.04

USER root

COPY ./sources.list /etc/apt/sources.list

RUN dpkg --add-architecture arm64 && apt-get update
RUN apt-get install -y --no-install-recommends \
    build-essential \
    crossbuild-essential-arm64 \
    git \
    wget \
    libusb-1.0-0-dev:arm64 \
    libgtk-3-dev:arm64 \
    libavcodec-dev:arm64 \
    libavformat-dev:arm64 \
    libswscale-dev:arm64 \
    libgstreamer1.0-dev:arm64 \
    libgstreamer-plugins-base1.0-dev:arm64 \
    libpython3-dev:arm64 \
    libtbb-dev:arm64 \
    python3-pip \
    python-minimal \
    python-argparse

RUN apt-get autoremove

RUN wget https://www.cmake.org/files/v3.14/cmake-3.14.3.tar.gz && \
    tar xf cmake-3.14.3.tar.gz && \
    (cd cmake-3.14.3 && ./bootstrap --parallel=$(nproc --all) && make --jobs=$(nproc --all) && make install) && \
    rm -rf cmake-3.14.3 cmake-3.14.3.tar.gz

RUN pip3 install numpy Cython
```

and edit `/etc/apt/sources.list` to avoid 404 Forbidden error.

```txt
deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ bionic main restricted
deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ bionic-updates main restricted
deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ bionic universe
deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ bionic-updates universe
deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ bionic multiverse
deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ bionic-updates multiverse
deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
deb [arch=amd64,i386] http://security.ubuntu.com/ubuntu/ bionic-security main restricted
deb [arch=amd64,i386] http://security.ubuntu.com/ubuntu/ bionic-security universe
deb [arch=amd64,i386] http://security.ubuntu.com/ubuntu/ bionic-security multiverse

deb [arch=armhf,arm64] http://ports.ubuntu.com/ bionic main restricted
deb [arch=armhf,arm64] http://ports.ubuntu.com/ bionic-updates main restricted
deb [arch=armhf,arm64] http://ports.ubuntu.com/ bionic universe
deb [arch=armhf,arm64] http://ports.ubuntu.com/ bionic-updates universe
deb [arch=armhf,arm64] http://ports.ubuntu.com/ bionic multiverse
deb [arch=armhf,arm64] http://ports.ubuntu.com/ bionic-updates multiverse
deb [arch=armhf,arm64] http://ports.ubuntu.com/ bionic-backports main restricted universe multiverse
```

But, when I build OpenVINO, make process show errror message


```log
[ 88%] Building CXX object inference-engine/samples/style_transfer_sample/CMakeFiles/style_transfer_sample.dir/main.cpp.o
[ 88%] Building CXX object inference-engine/src/vpu/common/CMakeFiles/vpu_common_lib.dir/src/ngraph/operations/static_shape_nonzero.cpp.o
[ 88%] Linking CXX executable ../../../../bin/aarch64/Release/style_transfer_sample
../../../../bin/aarch64/Release/lib/libinference_engine.so: undefined reference to `tbb::internal::numa_topology::fill(int*)'
../../../../bin/aarch64/Release/lib/libinference_engine.so: undefined reference to `tbb::internal::numa_topology::default_concurrency(int)'
../../../../bin/aarch64/Release/lib/libinference_engine.so: undefined reference to `tbb::internal::numa_topology::nodes_count()'
collect2: error: ld returned 1 exit status
inference-engine/samples/style_transfer_sample/CMakeFiles/style_transfer_sample.dir/build.make:87: recipe for target '../bin/aarch64/Release/style_transfer_sample' failed
make[2]: *** [../bin/aarch64/Release/style_transfer_sample] Error 1
CMakeFiles/Makefile2:6442: recipe for target 'inference-engine/samples/style_transfer_sample/CMakeFiles/style_transfer_sample.dir/all' failed
make[1]: *** [inference-engine/samples/style_transfer_sample/CMakeFiles/style_transfer_sample.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 88%] Building CXX object inference-engine/src/vpu/common/CMakeFiles/vpu_common_lib.dir/src/ngraph/operations/static_shape_reshape.cpp.o
[ 88%] Building CXX object inference-engine/src/vpu/common/CMakeFiles/vpu_common_lib.dir/src/ngraph/operations/static_shape_topk.cpp.o
```

and finally stop building process.

```
[ 90%] Linking CXX static library ../../../../../bin/aarch64/Release/lib/libvpu_common_lib.a
[ 90%] Built target vpu_common_lib
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```

How can I solve this error?

**Comment by Iffa-Meah** [comment]
You'll need to import "FROM debian:stretch", it uses the Debian* Stretch (Debian 9) OS for compilation because it is a **base of the Raspbian* Stretch**.

However, we'll investigate your issue further and get back to you asap.

**Comment by yeshuanova** [comment]
Because I want to execute OpenVINO on **Ubuntu 18.04**, not Debian Stretch.  So I just refer to [this document](https://github.com/openvinotoolkit/openvino/wiki/BuildingForRaspbianStretchOS) and modify it for custom requirements.

I sure that OpenVINO can be built x86_64 version successfully using native steps on x86_64 ubuntu 18.04 platform and python 3.6.9 wrapper.

**Comment by avitial** [comment]
@yeshuanova this should be possible, however I don't have a target board in my possession to test and verify the results of my compilation attempt. Check the following and let us know if it works for you:

```
git clone https://github.com/openvinotoolkit/openvino ~/openvino
cd ~/openvino && git checkout tags/2021.4.1
git submodule update --init --recursive
```

`mkdir ~/arm64 && vi ~/arm64/Dockerfile`

Make sure to include the referenced _sources.list_ file from your previous post as part of _arm64_ contents.
```
# Contents of Dockerfile
FROM ubuntu:18.04
USER root
COPY ./sources.list /etc/apt/sources.list

RUN dpkg --add-architecture arm64 && apt-get update
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    crossbuild-essential-arm64 \
    git \
    wget \
    libusb-1.0-0-dev:arm64 \
    libgtk-3-dev:arm64 \
    libavcodec-dev:arm64 \
    libavformat-dev:arm64 \
    libswscale-dev:arm64 \
    libgstreamer1.0-dev:arm64 \
    libgstreamer-plugins-base1.0-dev:arm64 \
    libgstreamer-plugins-base1.0-dev:arm64 \
    libpython3-dev:arm64 \
    libtbb-dev:arm64 \
    python-minimal \
    python3-distutils:arm64 \
    python3-pip \
    python3-setuptools \
    python-argparse \
    libglib2.0-dev-bin:arm64 \
    libglib2.0-dev:arm64  \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://www.cmake.org/files/v3.14/cmake-3.14.3.tar.gz && \
    tar xf cmake-3.14.3.tar.gz && \
    (cd cmake-3.14.3 && ./bootstrap --parallel=$(nproc --all) && make --jobs=$(nproc --all) && make install) && \
    rm -rf cmake-3.14.3 cmake-3.14.3.tar.gz

RUN python3 -m pip install pip --upgrade
RUN python3 -m pip install numpy cython scikit-build opencv-python==4.5.3.56

RUN git config --global user.name "Your Name" && \
    git config --global user.email "you@example.com"
```

```
docker image build -t arm64 arm64
docker run -it -v /home/user/openvino/:/openvino arm64 /bin/bash
```
```
python3 -m pip install -r openvino/inference-engine/ie_bridges/python/requirements.txt
python3 -m pip install -r openvino/inference-engine/ie_bridges/python/wheel/requirements-dev.txt
python3 -m pip install -r openvino/inference-engine/ie_bridges/python/src/requirements-dev.txt
```
```
cmake -DCMAKE_BUILD_TYPE=Release \
-DCMAKE_TOOLCHAIN_FILE="../cmake/arm64.toolchain.cmake" \
-DENABLE_MKL_DNN=OFF \
-DTHREADS_PTHREAD_ARG="-pthread" \
-DENABLE_CLDNN=OFF \
-DENABLE_GNA=OFF \
-DENABLE_SSE42=OFF \
-DTHREADING=SEQ \
-DENABLE_OPENCV=ON \
-DNGRAPH_PYTHON_BUILD_ENABLE=ON \
-DNGRAPH_ONNX_IMPORT_ENABLE=ON \
-DENABLE_PYTHON=ON \
-DPYTHON_EXECUTABLE=/usr/bin/python3.6 \
-DPYTHON_LIBRARY=/usr/lib/aarch64-linux-gnu/libpython3.6m.so \
-DPYTHON_INCLUDE_DIR=/usr/include/python3.6 ..
```
`make --jobs=$(nproc --all)`

```
...
...
# Build output success
[100%] Built target myriadPlugin
Scanning dependencies of target myriad_compile
Scanning dependencies of target myriad_perfcheck
[100%] Building CXX object inference-engine/tools/vpu/vpu_perfcheck/CMakeFiles/myriad_perfcheck.dir/main.cpp.o
[100%] Building CXX object inference-engine/tools/vpu/vpu_compile/CMakeFiles/myriad_compile.dir/__/common/vpu_tools_common.cpp.o
[100%] Building CXX object inference-engine/tools/vpu/vpu_compile/CMakeFiles/myriad_compile.dir/main.cpp.o
[100%] Linking CXX executable ../../../../../bin/aarch64/Release/myriad_compile
[100%] Built target myriad_compile
[100%] Linking CXX executable ../../../../../bin/aarch64/Release/myriad_perfcheck
[100%] Built target myriad_perfcheck
...
...
```

After exiting Docker (by pressing Ctrl+D), you can find the resulting binaries in the `~/openvino/bin/aarch64/` directory and the OpenCV* installation in the `~/openvino/inference-engine/temp`. Do not forget to complete the [additional steps](https://github.com/openvinotoolkit/openvino/wiki/BuildingForRaspbianStretchOS#optional-additional-installation-steps-for-the-intel-neural-compute-stick-2) section under instructions for NCS2.

Regards,
Luis

**Comment by yeshuanova** [comment]
Hi @avitial

Thanks your post. This process works and OpenVINO  is built successfully. But I don't find OpenCV* installation in the `~/openvino/inference-engine/temp`. This folder only have three directories

```
download 
protoc-3.7.1-linux-x86_64
vpu
```

Next, I move all files in the `~/openvino/bin/aarch64/` to target ARM board and set following environment variables

```sh
export LD_LIBRARY_PATH=$HOME/openvino/bin/aarch64/Release/lib:$LD_LIBRARY_PATH
export PYTHONPATH=$HOME/openvino/bin/aarch64/Release/lib/python_api/python3.6:$PYTHONPATH
```

and run [additional steps](https://github.com/openvinotoolkit/openvino/wiki/BuildingForRaspbianStretchOS#optional-additional-installation-steps-for-the-intel-neural-compute-stick-2) for NCS2.

But, when I run my test_ov.py file, some errors occur and show following message

```sh
E: [global] [    555834] [Scheduler00Thr] dispatcherEventSend:53    Write failed (header) (err -1) | event XLINK_PING_REQ

E: [xLink] [    555834] [Scheduler00Thr] sendEvents:998 Event sending failed
E: [global] [    556835] [Scheduler00Thr] dispatcherEventSend:53    Write failed (header) (err -4) | event XLINK_CREATE_STREAM_REQ

E: [xLink] [    556835] [Scheduler00Thr] sendEvents:998 Event sending failed
E: [global] [    556835] [python3.6] XLinkOpenStream:87 Cannot find stream id by the "deviceMonitor" name
E: [global] [    556835] [python3.6] XLinkOpenStream:88 Max streamId reached!
E: [ncAPI] [    556835] [python3.6] ncDeviceOpen:1095   can't open deviceMonitor stream due to unknown error

/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "test_ov.py", line 34, in <module>
    plate_model = YoloOV(plate_weight, plate_config, device_name, ie_core=ie)
  File "/userdata/plate-recognition-example/alpr/yoloalpr_ov.py", line 29, in __init__
    self._load_model(model_path, device_name)
  File "/userdata/plate-recognition-example/alpr/yoloalpr_ov.py", line 41, in _load_model
    exec_net = ie.load_network(network=net, device_name=device_name)
  File "ie_api.pyx", line 372, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 390, in openvino.inference_engine.ie_api.IECore.load_network
```

The `YoloOV` class is defined as

```python
import logging
import numpy as np
import cv2
import yaml
import time

# from math import exp as exp

from openvino.inference_engine import IECore

log = logging.getLogger()


class YoloOV:
    def __init__(
        self,
        model_path,
        config_path,
        device_name,
        ie_core=None,
    ) -> None:

        if ie_core is None:
            self.ie_core = IECore()
        else:
            self.ie_core = ie_core

        self.ie_core = ie_core
        self._load_model(model_path, device_name)
        self._load_config(config_path)

    def _load_model(self, model_path, device_name):
        log.info(f"Load Model {model_path}")

        ie = self.ie_core
        net = ie.read_network(model=model_path)
        net.batch_size = 1

        input_blob = next(iter(net.input_info))

        exec_net = ie.load_network(network=net, device_name=device_name)
        input_size = net.input_info[input_blob].input_data.shape

        self._input_blob = input_blob
        self._exec_net = exec_net
        self._input_size = input_size


...
```

I load ONNX model to create executable network object below in the `test_ov.py`

```python
ie = IECore()
device_name = "MYRIAD"

plate_weight = "model.onnx"
plate_config = "plate.yaml"
plate_model = YoloOV(plate_weight, plate_config, device_name, ie_core=ie)
```

How to fix this problem ?

**Comment by avitial** [comment]
@yeshuanova have you tried using C/C++ instead of Python and is the error the same? Not sure what to make out of the error here but looks like there is an issue interfacing with the Myriad device. Make sure there is enough power being supplied to the device as well with a powered USB hub. If you run the _lsusb_ utility, do you see the NCS2 device being detected?

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and provide additional information or ask any questions related to this topic.

**Comment by yeshuanova** [comment]
Hi @avitial 

I check usb device following reference  [Error - Could not open NCS device](https://www.intel.com/content/www/us/en/support/articles/000033151/boards-and-kits/neural-compute-sticks.html) and result is

```sh
$ lsusb | grep 03e7
Bus 007 Device 002: ID 03e7:2485
```

I I think this NCS2 device is detected. Beside, the development environment of our team is in python, c/c++ is not familiar.
Thank your responses and support. I will continue to find other methods to speed up runtime process if OpenVINO can't run on my device finally.

**Comment by dukezuoHZ** [comment]
I config with command : 
sudo cmake -DIE_EXTRA_MODULES=/home/duke/openvino_contrib-master/modules -DBUILD_java_api=OFF -DCMAKE_INSTALL_PREFIX=/opt/intel ..

openvino source is in path /home/duke/openvino ,but i met a issue when i built openvino again while i can build it ok only for openvino.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** No rule to make target '/home/duke/openvino_contrib-master/modules/arm_plugin/thirdparty/ComputeLibrary/SConstruct', needed by 'inference-engine/build-modules/arm_plugin/thirdparty/libarm_compute-static.a'. Stop.
CMakeFiles/Makefile2:5951: recipe for target 'inference-engine/build-modules/arm_plugin/thirdparty/CMakeFiles/arm_compute_static_libs.dir/all' failed
make[1]: *** [inference-engine/build-modules/arm_plugin/thirdparty/CMakeFiles/arm_compute_static_libs.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

~~~~~~~~~~~~~~~~~~~~~~~~~~
any hint will been appreciated.
